# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Christoph Wickert <christoph.wickert@gmail.com>, 2015
# Christoph Wickert <christoph.wickert@gmail.com>, 2011
# Colja Vendel <vendel.colja@googlemail.com>, 2016
# Dirk Marschner <info@marschner.cx>, 2015
# Dirk Marschner <info@marschner.cx>, 2015
# Ettore Atalan <atalanttore@googlemail.com>, 2014-2016
# Gerd Seyfarth <mail@netsecond.net>, 2015
# Torsten Grote <grote@kolabsys.com>, 2012
# Jeroen van Meeuwen <vanmeeuwen@kolabsys.com>, 2015
# balin <johannes_graumann@web.de>, 2012
# Jo <jo@caj-augsburg.de>, 2012
# Inperpetuammemoriam, 2016
# bitnukl, 2014
# Thomas Bruederli <roundcube@gmail.com>, 2014
# Till Savekoul <till@koul.de>, 2012
msgid ""
msgstr ""
"Project-Id-Version: Kolab Groupware Solution\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-12-02 15:22+0100\n"
"PO-Revision-Date: 2016-12-02 14:22+0000\n"
"Last-Translator: Jeroen van Meeuwen <vanmeeuwen@kolabsys.com>\n"
"Language-Team: German (http://www.transifex.com/kolab/kolab/language/de/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../bin/kolab_smtp_access_policy.py:214
#, python-format
msgid "Adding policy request to instance %s"
msgstr "Füge Richtlinien-Anfrage zu Instanz %s hinzu"

#: ../bin/kolab_smtp_access_policy.py:484
msgid "Unauthorized access not allowed"
msgstr "Unberechtigter Zugriff nicht erlaubt"

#: ../bin/kolab_smtp_access_policy.py:513
#: ../bin/kolab_smtp_access_policy.py:711
msgid "Could not find recipient"
msgstr "Konnte den Empfänger nicht finden"

#: ../bin/kolab_smtp_access_policy.py:532
#, python-format
msgid "Could not find envelope sender user %s (511)"
msgstr "Konnte Absender-Umschlag für Benutzer %s nicht finden (511)"

#: ../bin/kolab_smtp_access_policy.py:575
#, python-format
msgid "Obtained authenticated user details for %r: %r"
msgstr "Erhaltene Details des authentifizieren Benutzers %r: %r"

#: ../bin/kolab_smtp_access_policy.py:633
#, python-format
msgid "Could not find envelope sender user %s"
msgstr "Konnte den Absender-Umschlag für den Benutzer %s nicht finden"

#: ../bin/kolab_smtp_access_policy.py:666
#: ../bin/kolab_smtp_access_policy.py:694
#, python-format
msgid "%s is unauthorized to send on behalf of %s"
msgstr "Benutzer %s ist nicht berechtigt als Benutzer %s zu senden"

#: ../bin/kolab_smtp_access_policy.py:676
#, python-format
msgid ""
"User %s attempted to use envelope sender address %s without authorization"
msgstr "Benutzer %s versuchte die Absendeadresse %s ohne Berechtigung zu verwenden"

#: ../bin/kolab_smtp_access_policy.py:736
#: ../bin/kolab_smtp_access_policy.py:747
#, python-format
msgid "Found user %s to be a delegate user of %s"
msgstr "Benutzer %s ist ein delegierter Benutzer von %s"

#: ../bin/kolab_smtp_access_policy.py:767
#, python-format
msgid ""
"Verifying authenticated sender '%(sender)s' with sasl_username "
"'%(sasl_username)s' for recipient '%(recipient)s'"
msgstr "Überprüfe authentisierten Absender '%(sender)s' mit SASL-Benutzernamen '%(sasl_username)s' für Empfänger '%(recipient)s'"

#: ../bin/kolab_smtp_access_policy.py:770
#, python-format
msgid ""
"Verifying unauthenticated sender '%(sender)s' for recipient '%(recipient)s'"
msgstr "Überprüfe unauthentisierten Absender '%(sender)s' für Empfänger '%(recipient)s'"

#: ../bin/kolab_smtp_access_policy.py:786
#, python-format
msgid "Reproducing verify_recipient(%s, %s) from cache"
msgstr "Reproduziere verify_recipient(%s, %s) aus Cache"

#: ../bin/kolab_smtp_access_policy.py:823
#, python-format
msgid "Using authentication domain %s instead of %s"
msgstr "Authentisierungsdomain %s anstelle von %s wird verwendet"

#: ../bin/kolab_smtp_access_policy.py:833
#, python-format
msgid "Domain %s is a primary domain"
msgstr "Die Domain %s ist die primäre Domain"

#: ../bin/kolab_smtp_access_policy.py:841
#, python-format
msgid ""
"Checking the recipient for domain %s that is not ours. This is probably a "
"configuration error."
msgstr "Überprüfe Empfänger für fremde Domäne %s. Dies ist wahrscheinlich ein Konfigurationsfehler."

#: ../bin/kolab_smtp_access_policy.py:856
msgid ""
"This recipient address is related to multiple object entries and the SMTP "
"Access Policy can therefore not restrict message flow"
msgstr "Diese Empfänger-Adresse bezieht sich auf mehrere Objekt-Einträge. Die SMTP Access Policy kann deshalb den Nachrichtenfluss nicht einschränken."

#: ../bin/kolab_smtp_access_policy.py:873
#, python-format
msgid ""
"Recipient address %r not found. Allowing since the MTA was configured to "
"accept the recipient."
msgstr "Emfänger-Adresse %r nicht gefunden. Erlauben, da MTA konfiguriert wurde, diesen Empfänger zu akzeptieren."

#: ../bin/kolab_smtp_access_policy.py:909
msgid "Invalid recipient"
msgstr "Ungültiger Empfänger"

#: ../bin/kolab_smtp_access_policy.py:920
msgid "Could not find this user, accepting"
msgstr "Konnte keine Einschränkung für diesen Benutzer finden, akzeptiere Nachricht"

#: ../bin/kolab_smtp_access_policy.py:993
#: ../bin/kolab_smtp_access_policy.py:1070
#, python-format
msgid "Sender %s is not allowed to send to recipient %s"
msgstr "Absender %s darf nicht an Empfänger %s senden"

#: ../bin/kolab_smtp_access_policy.py:1057
#, python-format
msgid "Reproducing verify_sender(%r) from cache"
msgstr "Reproduziere verify_sender(%r) aus Cache"

#: ../bin/kolab_smtp_access_policy.py:1077
msgid "Unverifiable sender."
msgstr "Nicht überprüfbarer Absender."

#: ../bin/kolab_smtp_access_policy.py:1083
msgid "Sender is not using an alias"
msgstr "Absender nutzt keinen Alias"

#: ../bin/kolab_smtp_access_policy.py:1092
msgid "Sender uses unauthorized envelope sender address"
msgstr "Absender nutzt unerlaubte Absender-Umschlag Adresse"

#: ../bin/kolab_smtp_access_policy.py:1109
msgid "Could not verify sender"
msgstr "Konnte den Absender nicht verifizieren"

#: ../bin/kolab_smtp_access_policy.py:1116
msgid ""
"Verifying whether sender is allowed to send to recipient using sender policy"
msgstr "Überprüfe ob Absender an Empfänger gemäß Absender-Richtlinie senden darf"

#: ../bin/kolab_smtp_access_policy.py:1129
#, python-format
msgid "Result is %r"
msgstr "Das Ergebnis ist %r"

#: ../bin/kolab_smtp_access_policy.py:1134
msgid "No recipient policy restrictions exist for this sender"
msgstr "Es existiert keine Empfängerrichtlinie für diesen Absender"

#: ../bin/kolab_smtp_access_policy.py:1143
msgid "Found a recipient policy to apply for this sender."
msgstr "Empfänger-Richtlinie für diesen Benutzer gefunden"

#: ../bin/kolab_smtp_access_policy.py:1158
#, python-format
msgid "Sender %s not allowed to send to recipient %s"
msgstr "Absender %s darf nicht an Empfänger %s senden"

#: ../bin/kolab_smtp_access_policy.py:1186
msgid "Cleaning up the cache"
msgstr "Aufräumen des Cache"

#: ../bin/kolab_smtp_access_policy.py:1209
msgid ""
"The 'uri' setting in the kolab_smtp_access_policy section is soon going to "
"be deprecated in favor of 'cache_uri'"
msgstr "Die 'uri' Einstellung im Abschnitt kolab_smtp_access_policy wird bald überholt sein. Nutzen Sie 'cache_uri' stattdessen "

#: ../bin/kolab_smtp_access_policy.py:1225
#, python-format
msgid "Operational Error in caching: %s"
msgstr "Betriebsbedingter Fehler beim Cachen: %s"

#: ../bin/kolab_smtp_access_policy.py:1278
#, python-format
msgid "Caching the policy result with timestamp %d"
msgstr "Cachen des Richtlinienergebnisses mit Zeitstempel %d"

#: ../bin/kolab_smtp_access_policy.py:1355
#, python-format
msgid "Returning action DEFER_IF_PERMIT: %s"
msgstr "Antwort Aktion DEFER_IF_PERMIT: %s"

#: ../bin/kolab_smtp_access_policy.py:1360
#, python-format
msgid "Returning action DUNNO: %s"
msgstr "Antwort Aktion DUNNO: %s"

#: ../bin/kolab_smtp_access_policy.py:1365
#, python-format
msgid "Returning action HOLD: %s"
msgstr "Antwort Aktion HOLD: %s"

#: ../bin/kolab_smtp_access_policy.py:1370
#, python-format
msgid "Returning action PERMIT: %s"
msgstr "Antwort Aktion PERMIT: %s"

#: ../bin/kolab_smtp_access_policy.py:1498
#, python-format
msgid "Returning action REJECT: %s"
msgstr "Antwort Aktion REJECT: %s"

#: ../bin/kolab_smtp_access_policy.py:1544
msgid "Starting to loop for new request"
msgstr "Starte Schleife für neue Anfrage"

#: ../bin/kolab_smtp_access_policy.py:1551
msgid "Timeout for policy request reading exceeded"
msgstr "Zeitüberschreitung beim Lesen der Richtlinienanfrage"

#: ../bin/kolab_smtp_access_policy.py:1557
msgid "End of current request"
msgstr "Ende der aktuellen Anfrage"

#: ../bin/kolab_smtp_access_policy.py:1561
#, python-format
msgid "Getting line: %s"
msgstr "Lese Zeile: %s"

#: ../bin/kolab_smtp_access_policy.py:1565
msgid "Returning request"
msgstr "Rückgabe Richtlinenanfordung"

#: ../bin/kolab_smtp_access_policy.py:1594
msgid "Access Policy Options"
msgstr "Zugriffsrichtlinien-Einstellungen"

#: ../bin/kolab_smtp_access_policy.py:1601
msgid "SMTP Policy request timeout."
msgstr "Zeitüberschreitung der SMTP Richtlinien-Anfrage"

#: ../bin/kolab_smtp_access_policy.py:1607
msgid "Verify the recipient access policy."
msgstr "Verifiziere die Empfänger-Zugriffs-Richtlinie."

#: ../bin/kolab_smtp_access_policy.py:1613
msgid "Verify the sender access policy."
msgstr "Verifiziere die Sender-Zugriffs-Richtlinie."

#: ../bin/kolab_smtp_access_policy.py:1619
msgid "Allow unauthenticated senders."
msgstr "Erlaube nicht authentisierte Sender."

#: ../bin/kolab_smtp_access_policy.py:1633
#, python-format
msgid "Got request instance %s"
msgstr "Anfrage bekommen für Instanz %s"

#: ../bin/kolab_smtp_access_policy.py:1642
#, python-format
msgid "Request instance %s is in state %s"
msgstr "Anfrage-Instanz %s ist im Status %s"

#: ../bin/kolab_smtp_access_policy.py:1674
#, python-format
msgid "Unhandled exception caught: %r"
msgstr "Unbehandelte Ausnahme abgefangen: %r"

#: ../bin/kolab_smtp_access_policy.py:1678
msgid "Sender access denied"
msgstr "Sender Zugriff verweigert"

#: ../bin/kolab_smtp_access_policy.py:1680
msgid "Recipient access denied"
msgstr "Empfänger Zugriff verweigert"

#: ../bin/kolab_smtp_access_policy.py:1682
msgid "No objections"
msgstr "Keine Einwände"

#: ../conf.py:36 ../kolab-cli.py:34 ../saslauthd.py:33
msgid "Cannot load pykolab/logger.py:"
msgstr "Laden von pykolab/logger.py nicht möglich:"

#: ../kolabd/__init__.py:50 ../saslauthd/__init__.py:52
#: ../wallace/__init__.py:108
msgid "Daemon Options"
msgstr "Daemon Optionen"

#: ../kolabd/__init__.py:57 ../saslauthd/__init__.py:59
#: ../wallace/__init__.py:115
msgid "Fork to the background."
msgstr "In den Hintergrund abtauchen"

#: ../kolabd/__init__.py:66 ../saslauthd/__init__.py:68
#: ../wallace/__init__.py:150
msgid "Path to the PID file to use."
msgstr "Pfad zur PID-Datei"

#: ../kolabd/__init__.py:75 ../saslauthd/__init__.py:86
#: ../wallace/__init__.py:168
msgid "Run as user USERNAME"
msgstr "Als Benutzer USERNAME ausführen"

#: ../kolabd/__init__.py:85 ../saslauthd/__init__.py:96
#: ../wallace/__init__.py:132
msgid "Run as group GROUPNAME"
msgstr "Als Gruppe GROUPNAME ausführen"

#: ../kolabd/__init__.py:123 ../pykolab/utils.py:254
#: ../saslauthd/__init__.py:327 ../wallace/__init__.py:373
#, python-format
msgid "Group %s does not exist"
msgstr "Gruppe %s exisitert nicht"

#: ../kolabd/__init__.py:132 ../saslauthd/__init__.py:336
#: ../wallace/__init__.py:382
#, python-format
msgid "Switching real and effective group id to %d"
msgstr "Wechsle reale und effektive Gruppen-ID zu %d"

#: ../kolabd/__init__.py:154 ../pykolab/utils.py:278
#: ../saslauthd/__init__.py:358 ../wallace/__init__.py:404
#, python-format
msgid "User %s does not exist"
msgstr "Benutzer %s existiert nicht"

#: ../kolabd/__init__.py:163 ../saslauthd/__init__.py:367
#: ../wallace/__init__.py:414
#, python-format
msgid "Switching real and effective user id to %d"
msgstr "Wechsle reale und effektive Benutzer-ID zu %d"

#: ../kolabd/__init__.py:172 ../saslauthd/__init__.py:376
#: ../wallace/__init__.py:423
msgid "Could not change real and effective uid and/or gid"
msgstr "Konnte reale und effektive UID und/oder GID nicht ändern"

#: ../kolabd/__init__.py:215 ../saslauthd/__init__.py:166
#: ../wallace/__init__.py:465
msgid "Interrupted by user"
msgstr "Vom Benutzer unterbrochen"

#: ../kolabd/__init__.py:220 ../kolabd/__init__.py:231
#: ../saslauthd/__init__.py:170 ../saslauthd/__init__.py:179
#: ../wallace/__init__.py:469 ../wallace/__init__.py:478
msgid "Traceback occurred, please report a bug at https://issues.kolab.org"
msgstr "Traceback Softwarefehler aufgetreten, bitte auf https://issues.kolab.org einen Fehlerreport erstellen."

#: ../kolabd/__init__.py:226 ../saslauthd/__init__.py:175
#: ../wallace/__init__.py:474
#, python-format
msgid "Type Error: %s"
msgstr "Typ-Fehler: %s"

#: ../kolabd/__init__.py:253
msgid "Could not connect to LDAP, is it running?"
msgstr "Konnte nicht zu LDAP verbinden, läuft es?"

#: ../kolabd/__init__.py:256 ../pykolab/auth/ldap/__init__.py:2528
#: ../pykolab/cli/cmd_sync.py:77
msgid "Listing domains..."
msgstr "Liste Domains auf..."

#: ../kolabd/__init__.py:267
msgid "No domains. Not syncing"
msgstr "Keine Domänen. Keine Synchronisation"

#: ../kolabd/__init__.py:290
#, python-format
msgid "Domain %r naming context: %r, root dn: %r"
msgstr ""

#: ../kolabd/__init__.py:302
#, python-format
msgid "Naming contexts to synchronize: %r"
msgstr ""

#: ../kolabd/__init__.py:320
#, python-format
msgid "Result set of domains: %r"
msgstr ""

#: ../kolabd/__init__.py:323
#, python-format
msgid "Checking for domain %s"
msgstr ""

#: ../kolabd/__init__.py:327
#, python-format
msgid "Domain %s isn't alive anymore."
msgstr ""

#: ../kolabd/__init__.py:331
#, python-format
msgid "Domain %s already there and alive."
msgstr ""

#: ../kolabd/__init__.py:335
#, python-format
msgid "Domain %s should not exist any longer."
msgstr ""

#: ../kolabd/__init__.py:338
#, python-format
msgid "Domain %s does not have a process yet."
msgstr ""

#: ../kolabd/__init__.py:349
#, python-format
msgid "added domains: %r, removed domains: %r"
msgstr "Domänen hinzugefügt: %r, Domänen entfernt: %r"

#: ../kolabd/process.py:34
#, python-format
msgid "Process created for domain %s"
msgstr "Prozess gestartet für Domäne %s"

#: ../kolabd/process.py:43
#, python-format
msgid "Synchronizing for domain %s"
msgstr "Synchronisiere für Domäne %s"

#: ../kolabd/process.py:60
#, python-format
msgid ""
"Error in process %r, terminating:\n"
"\t%r"
msgstr "Fehler im Prozess %r, beende:\n\t%r"

#: ../kolabd.py:31 ../setup-kolab.py:37 ../wallace.py:31
msgid "Cannot load pykolab/constants.py:"
msgstr "Konnte nicht pykolab/constants.py laden:"

#: ../pykolab/auth/__init__.py:89
#, python-format
msgid "Called for domain %r"
msgstr "Aufgerufen für Domäne %r"

#: ../pykolab/auth/__init__.py:106 ../pykolab/auth/__init__.py:115
#, python-format
msgid "Using section %s and domain %s"
msgstr "Benutze Abschnitt %s und Domäne %s"

#: ../pykolab/auth/__init__.py:120
#, python-format
msgid "Connecting to Authentication backend for domain %s"
msgstr "Verbinde zu Authentifizierungsbackend für Domäne %s"

#: ../pykolab/auth/__init__.py:131
#, python-format
msgid "Section %s has no option 'auth_mechanism'"
msgstr "Abschnitt %s hat keinen Wert 'auth_mechanism'"

#: ../pykolab/auth/__init__.py:138
#, python-format
msgid "Section %s has auth_mechanism: %r"
msgstr "Abschnitt %s hat auth_mechanism: %r"

#: ../pykolab/auth/__init__.py:147 ../pykolab/auth/__init__.py:156
msgid "Starting LDAP..."
msgstr "Starte LDAP..."

#: ../pykolab/auth/ldap/cache.py:126
#, python-format
msgid "Inserting cache entry %r"
msgstr "Hinzufügen Cacheeintrag %r"

#: ../pykolab/auth/ldap/cache.py:147
#, python-format
msgid "Updating timestamp for cache entry %r"
msgstr "Aktualisiere Zeitstempel für Cacheeintrag %r"

#: ../pykolab/auth/ldap/cache.py:155
#, python-format
msgid "Updating result_attribute for cache entry %r"
msgstr "Aktualisiere result_attribute für Cacheeintrag %r"

#: ../pykolab/auth/ldap/__init__.py:54
msgid "Python LDAP library does not support persistent search"
msgstr "Die Python LDAP Bibliothek unterstützt keine persistente Suche"

#: ../pykolab/auth/ldap/__init__.py:147
#, python-format
msgid "Attempting to authenticate user %s in realm %s"
msgstr "Versuche Benutzer %s in Bereich %s zu authentisieren"

#: ../pykolab/auth/ldap/__init__.py:165 ../pykolab/auth/ldap/__init__.py:180
#: ../pykolab/auth/ldap/__init__.py:207 ../pykolab/auth/ldap/__init__.py:324
#, python-format
msgid "Authentication cache failed: %r"
msgstr "Authentifizierungscache fehlgeschlagen: %r"

#: ../pykolab/auth/ldap/__init__.py:229 ../pykolab/auth/ldap/__init__.py:1445
#: ../pykolab/auth/ldap/__init__.py:1471 ../pykolab/auth/ldap/__init__.py:3070
#, python-format
msgid "LDAP server unavailable: %r"
msgstr "LDAP-Server nicht erreichbar: %r"

#: ../pykolab/auth/ldap/__init__.py:230 ../pykolab/auth/ldap/__init__.py:237
#: ../pykolab/auth/ldap/__init__.py:1320 ../pykolab/auth/ldap/__init__.py:1446
#: ../pykolab/auth/ldap/__init__.py:1472 ../pykolab/auth/ldap/__init__.py:1760
#: ../pykolab/auth/ldap/__init__.py:3071 ../pykolab/auth/ldap/__init__.py:3081
#, python-format
msgid "%s"
msgstr "%s"

#: ../pykolab/auth/ldap/__init__.py:236
#, python-format
msgid "Exception occurred: %r"
msgstr "Ausnahme aufgetreten: %r"

#: ../pykolab/auth/ldap/__init__.py:243
#, python-format
msgid "Length of entries found: %r"
msgstr "Länge der gefundenen Einträge: %r"

#: ../pykolab/auth/ldap/__init__.py:255
#, python-format
msgid "Authentication for %r failed (multiple entries)"
msgstr "Authentifizierung für %r fehlgeschlagen (mehrfache Einträge)"

#: ../pykolab/auth/ldap/__init__.py:269
#, python-format
msgid "Authentication for %r failed (no entry)"
msgstr "Authentifizierung für %r fehlgeschlagen (kein Eintrag)"

#: ../pykolab/auth/ldap/__init__.py:282
#, python-format
msgid "Authentication for %r failed (LDAP error?)"
msgstr "Authentifizierung für %r fehlgeschlagen (LDAP-Fehler?)"

#: ../pykolab/auth/ldap/__init__.py:300 ../pykolab/auth/ldap/__init__.py:354
#, python-format
msgid "Authentication for %r succeeded"
msgstr "Authentifizierung für %r erfolgreich"

#: ../pykolab/auth/ldap/__init__.py:311
#, python-format
msgid "Authentication for %r failed (error)"
msgstr "Authentifizierung für %r fehlgeschlagen (Fehler)"

#: ../pykolab/auth/ldap/__init__.py:328
msgid "Authentication failed, LDAP server unavailable"
msgstr "Authentifizierung fehlgeschlagen, LDAP-Server nicht erreichbar"

#: ../pykolab/auth/ldap/__init__.py:336 ../pykolab/auth/ldap/__init__.py:391
#, python-format
msgid "Failed to authenticate as user %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:357
#, python-format
msgid "Authentication for %r failed (password)"
msgstr "Authentifizierung für %r fehlgeschlagen (Passwort)"

#: ../pykolab/auth/ldap/__init__.py:369
#, python-format
msgid "Error occured, there is no such object: %r"
msgstr "Ausnahme aufgetreten, es gibt kein solches Objekt: %r"

#: ../pykolab/auth/ldap/__init__.py:381
msgid "Authentication cache failed to clear entry"
msgstr "Authentifizierungscache konnte Eintrag nicht entfernen"

#: ../pykolab/auth/ldap/__init__.py:387
#, python-format
msgid "Exception occured: %r"
msgstr "Ausnahme aufgetreten: %r"

#: ../pykolab/auth/ldap/__init__.py:419
msgid "Connecting to LDAP..."
msgstr "Verbinde zum LDAP..."

#: ../pykolab/auth/ldap/__init__.py:423
#, python-format
msgid "Attempting to use LDAP URI %s"
msgstr "Versuche LDAP URI %s zu benutzen"

#: ../pykolab/auth/ldap/__init__.py:525
#, python-format
msgid "Entry ID: %r"
msgstr "Eintragkennung: %r"

#: ../pykolab/auth/ldap/__init__.py:527
#, python-format
msgid "Entry DN: %r"
msgstr "Eintrag DN: %r"

#: ../pykolab/auth/ldap/__init__.py:530
#, python-format
msgid ""
"ldap search: (%r, %r, filterstr='(objectclass=*)', attrlist=[ 'dn' ] + %r"
msgstr "LDAP Suche: (%r, %r, filterstr='(objectclass=*)', attrlist=[ 'dn' ] + %r"

#: ../pykolab/auth/ldap/__init__.py:649 ../pykolab/auth/ldap/__init__.py:805
#, python-format
msgid "Finding resource with filter %r"
msgstr "Finde Ressource mit Filter %r"

#: ../pykolab/auth/ldap/__init__.py:729
#, python-format
msgid "Finding recipient with filter %r"
msgstr "Finde Empfänger mit Filter %r"

#: ../pykolab/auth/ldap/__init__.py:836
#, python-format
msgid "Using timestamp %r"
msgstr "Zeitstempel %r wird verwendet"

#: ../pykolab/auth/ldap/__init__.py:873
#, python-format
msgid "Not applying recipient policy for %s (disabled through configuration)"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:883
#, python-format
msgid "Applying recipient policy to %r"
msgstr "Anwendung Empfängerrichtlinie zu %r"

#: ../pykolab/auth/ldap/__init__.py:900
#, python-format
msgid "Using mail attributes: %r, with primary %r and secondary %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:911
#, python-format
msgid "key %r not in entry"
msgstr "Key %r nicht im Eintrag"

#: ../pykolab/auth/ldap/__init__.py:913
#, python-format
msgid "key %r is the prim. mail attr."
msgstr "Key %r ist das primäre Mailattr."

#: ../pykolab/auth/ldap/__init__.py:915
msgid "prim. mail pol. is not empty"
msgstr "Primäre Mailrichtlinie ist nicht leer"

#: ../pykolab/auth/ldap/__init__.py:918
#, python-format
msgid "key %r is the sec. mail attr."
msgstr "Key %r ist das sekundäre Mailattr."

#: ../pykolab/auth/ldap/__init__.py:920
msgid "sec. mail pol. is not empty"
msgstr "Sekundäre Mailrichtlinie ist nicht leer"

#: ../pykolab/auth/ldap/__init__.py:924 ../pykolab/auth/ldap/__init__.py:938
#, python-format
msgid "Attributes %r are not yet available for entry %r"
msgstr "Attribute %r sind für Eintrag %r noch nicht verfügbar"

#: ../pykolab/auth/ldap/__init__.py:977
#, python-format
msgid "No results for mail address %s found"
msgstr "Keine Ergebnisse für E-Mail-Adresse %s gefunden"

#: ../pykolab/auth/ldap/__init__.py:988
#, python-format
msgid "1 result for address %s found, verifying"
msgstr "1 Ergebnis für Adresse %s gefunden, prüfe"

#: ../pykolab/auth/ldap/__init__.py:998
#, python-format
msgid "Too bad, primary email address %s already in use for %s (we are %s)"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1009 ../pykolab/auth/ldap/__init__.py:1098
msgid "Address assigned to us"
msgstr "Uns zugewiesene Adresse"

#: ../pykolab/auth/ldap/__init__.py:1064
#, python-format
msgid "No results for address %s found"
msgstr "Keine Ergebnisse für Adresse %s gefunden"

#: ../pykolab/auth/ldap/__init__.py:1075
#, python-format
msgid "1 result for address %s found, verifying..."
msgstr "1 Ergebnis für Adresse %s gefunden, wird überprüft..."

#: ../pykolab/auth/ldap/__init__.py:1086
#, python-format
msgid "Too bad, secondary email address %s already in use for %s (we are %s)"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1113
#, python-format
msgid ""
"Recipient policy composed the following set of secondary email addresses: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1124
#, python-format
msgid "Secondary mail addresses that we want is not None: %r"
msgstr "Gewünschte sekundäre E-Mail-Adresse ist nicht leer: %r"

#: ../pykolab/auth/ldap/__init__.py:1135
#, python-format
msgid ""
"Avoiding the duplication of the primary mail address %r in the list of "
"secondary mail addresses"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1146
#, python-format
msgid "Entry is getting secondary mail addresses: %r"
msgstr "Eintrag erhält die sekundären E-Mail-Adressen: %r"

#: ../pykolab/auth/ldap/__init__.py:1154
#, python-format
msgid "Entry did not have any secondary mail addresses in %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1171 ../pykolab/auth/ldap/__init__.py:1177
#, python-format
msgid "secondary_mail_addresses: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1172 ../pykolab/auth/ldap/__init__.py:1178
#, python-format
msgid "entry[%s]: %r"
msgstr "Eintrag[%s]: %r"

#: ../pykolab/auth/ldap/__init__.py:1189
#, python-format
msgid "Entry modifications list: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1223
#, python-format
msgid "Setting entry attribute %r to %r for %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1259
#, python-format
msgid ""
"Could not update dn %r:\n"
"%r"
msgstr "Konnte dn %r nicht aktualisieren:\n%r"

#: ../pykolab/auth/ldap/__init__.py:1285
#, python-format
msgid "Using filter %r"
msgstr "Filter %r wird verwendet"

#: ../pykolab/auth/ldap/__init__.py:1300
#, python-format
msgid "Synchronization is searching against base DN: %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1347
#, python-format
msgid ""
"About to consider the user quota for %r (used: %r, imap: %r, ldap: %r, "
"default: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1410
msgid "Attempting to bind without a DN but with a password"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1415
msgid "Attempting to bind with a DN but without a password"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1433
#, python-format
msgid "Binding with bind_dn: %s and password: %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1451 ../pykolab/auth/ldap/__init__.py:1475
msgid "Invalid DN, username and/or password."
msgstr "Ungültiger DN, Nutzername und/oder Passwort."

#: ../pykolab/auth/ldap/__init__.py:1456
msgid "bind() called but already bound"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1478
msgid "bind_priv() called but already bound"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1690
#, python-format
msgid "Entry %s attribute value: %r"
msgstr "Eintrag %s Attributwert: %r"

#: ../pykolab/auth/ldap/__init__.py:1698
#, python-format
msgid "imap.user_mailbox_server(%r) result: %r"
msgstr "imap.user_mailbox_server(%r)-Ergebnis: %r"

#: ../pykolab/auth/ldap/__init__.py:1759
#, python-format
msgid "An error occured: %r"
msgstr "Ein Fehler ist aufgetreten: %r"

#: ../pykolab/auth/ldap/__init__.py:1997 ../pykolab/auth/ldap/__init__.py:2191
#, python-format
msgid "Result from recipient policy: %r"
msgstr "Ergebnis der Empfängerrichtlinie: %r"

#: ../pykolab/auth/ldap/__init__.py:2246
#, python-format
msgid "Kolab user %s does not have a result attribute %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2271
#, python-format
msgid "Naming contexts found: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2278
#, python-format
msgid "Domains/Root DNs found: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2438
#, python-format
msgid "Searching root dn for domain %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2443
#, python-format
msgid "Returning from cache: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2448
#, python-format
msgid "Finding domain root dn for domain %s"
msgstr "Suche root dn für die Domain %s"

#: ../pykolab/auth/ldap/__init__.py:2478
#, python-format
msgid "Setting domain root dn from LDAP for domain %r: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2624 ../pykolab/auth/ldap/__init__.py:2672
#, python-format
msgid "Entry type: %s"
msgstr "Eintragtyp: %s"

#: ../pykolab/auth/ldap/__init__.py:2750
msgid "LDAP Search Result Data Entry:"
msgstr "LDAP-Suchergebnisdateneintrag:"

#: ../pykolab/auth/ldap/__init__.py:2766
msgid "Entry Change Notification attributes:"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2771
#, python-format
msgid "Change Type: %r (%r)"
msgstr "Typ ändern: %r (%r)"

#: ../pykolab/auth/ldap/__init__.py:2779
#, python-format
msgid "Previous DN: %r"
msgstr "Vorheriger DN: %r"

#: ../pykolab/auth/ldap/__init__.py:2834
#, python-format
msgid "Object %s searched no longer exists"
msgstr "Das gesuchte Objekt %s existiert nicht mehr"

#: ../pykolab/auth/ldap/__init__.py:2844
#, python-format
msgid "%d results..."
msgstr "%d Ergebnisse..."

#: ../pykolab/auth/ldap/__init__.py:2947
#, python-format
msgid "Searching with filter %r"
msgstr "Suchvorgang mit Filter %r"

#: ../pykolab/auth/ldap/__init__.py:2999
#, python-format
msgid "Checking for support for %s on %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:3018
#, python-format
msgid "Found support for %s"
msgstr "Unterstützung für %s gefunden"

#: ../pykolab/auth/ldap/__init__.py:3072
msgid "-- reconnecting in 10 seconds."
msgstr "-- erneuter Verbindungsaufbau in 10 Sekunden."

#: ../pykolab/auth/ldap/__init__.py:3080
#, python-format
msgid "An error occured using %s: %r"
msgstr ""

#: ../pykolab/auth/ldap/syncrepl.py:46
msgid ""
"The name of the persistent, unique attribute is very probably not compatible"
" with the use of syncrepl."
msgstr ""

#: ../pykolab/cli/cmd_acl_cleanup.py:34
msgid "Clean up ACLs that use identifiers that no longer exist"
msgstr ""

#: ../pykolab/cli/cmd_acl_cleanup.py:56
#: ../pykolab/cli/cmd_mailbox_cleanup.py:173
#, python-format
msgid "Deleting ACL %s for subject %s on folder %s"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:42
msgid "Specify the (new) alias address"
msgstr "Geben Sie eine (neue) Alias-Adresse an"

#: ../pykolab/cli/cmd_add_alias.py:45
msgid "Specify the existing recipient address"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:66 ../pykolab/cli/cmd_add_alias.py:70
#, python-format
msgid "Domain %r is not a local domain"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:75
msgid "Primary and secondary domain do not have the same parent domain"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:81
#, python-format
msgid "No such recipient %r"
msgstr "Kein solcher Benutzer %r"

#: ../pykolab/cli/cmd_add_alias.py:87
#, python-format
msgid "Recipient for alias %r already exists"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:97
msgid ""
"Environment is not configured for users to hold secondary mail attributes"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:105
#, python-format
msgid "Recipient %r is not the primary recipient for address %r"
msgstr "Empfänger %r ist nicht der primäre Empfänger für Adresse %r"

#: ../pykolab/cli/cmd_add_domain.py:36 ../pykolab/cli/cmd_check_quota.py:37
#: ../pykolab/cli/cmd_count_domain_mailboxes.py:38
#: ../pykolab/cli/cmd_create_mailbox.py:36
#: ../pykolab/cli/cmd_delete_domain.py:39
#: ../pykolab/cli/cmd_export_mailbox.py:33
#: ../pykolab/cli/cmd_list_deleted_mailboxes.py:38
#: ../pykolab/cli/cmd_list_domain_mailboxes.py:37
#: ../pykolab/cli/cmd_list_mailboxes.py:40
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:37
#: ../pykolab/cli/cmd_list_messages.py:37 ../pykolab/cli/cmd_list_quota.py:36
#: ../pykolab/cli/cmd_list_user_subscriptions.py:36
#: ../pykolab/cli/cmd_mailbox_cleanup.py:39
#: ../pykolab/cli/cmd_server_info.py:34
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:38
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:39 ../pykolab/cli/cmd_sync.py:45
#: ../pykolab/cli/cmd_undelete_mailbox.py:34
msgid "CLI Options"
msgstr "Kommandozeilen-Parameter"

#: ../pykolab/cli/cmd_add_domain.py:42
msgid "Add alias domain."
msgstr "Hinzufügen Alias-Domäne."

#: ../pykolab/cli/cmd_add_domain.py:47
msgid "Add a new domain."
msgstr "Hinzufügen einer neuen Domäne."

#: ../pykolab/cli/cmd_add_domain.py:55 ../pykolab/cli/cmd_delete_domain.py:55
#: ../pykolab/cli/cmd_find_domain.py:44
msgid ""
"Could not find credentials with sufficient permissionsto add a domain name "
"space."
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:67 ../pykolab/cli/cmd_delete_domain.py:67
#: ../pykolab/cli/cmd_find_domain.py:56
msgid "Domain name"
msgstr "Name der Domain"

#: ../pykolab/cli/cmd_add_user_subscription.py:37
msgid "Subscribe a user to a folder."
msgstr "Aboniere einen Ordner für einen Benutzer."

#: ../pykolab/cli/cmd_add_user_subscription.py:47
#: ../pykolab/cli/cmd_add_user_subscription.py:51
#: ../pykolab/cli/cmd_remove_user_subscription.py:47
#: ../pykolab/cli/cmd_remove_user_subscription.py:51
msgid "Folder pattern"
msgstr "Ordnermuster"

#: ../pykolab/cli/cmd_add_user_subscription.py:50
#: ../pykolab/cli/cmd_list_user_subscriptions.py:63
#: ../pykolab/cli/cmd_remove_user_subscription.py:50
msgid "User ID"
msgstr "Benutzer ID"

#: ../pykolab/cli/cmd_add_user_subscription.py:72
#: ../pykolab/cli/cmd_remove_user_subscription.py:72
#, python-format
msgid "Cannot subscribe user to folder %r:"
msgstr ""

#: ../pykolab/cli/cmd_add_user_subscription.py:73
#: ../pykolab/cli/cmd_delete_message.py:61
#: ../pykolab/cli/cmd_list_messages.py:100
#: ../pykolab/cli/cmd_remove_user_subscription.py:73
msgid "No such folder"
msgstr "Dieser Ordner ist nicht vorhanden"

#: ../pykolab/cli/cmd_check_quota.py:44
msgid "Do not apply any changes."
msgstr ""

#: ../pykolab/cli/cmd_check_quota.py:53
#: ../pykolab/cli/cmd_count_domain_mailboxes.py:44
#: ../pykolab/cli/cmd_list_deleted_mailboxes.py:50
#: ../pykolab/cli/cmd_list_domain_mailboxes.py:49
#: ../pykolab/cli/cmd_list_mailboxes.py:52
#: ../pykolab/cli/cmd_list_messages.py:52 ../pykolab/cli/cmd_list_quota.py:42
#: ../pykolab/cli/cmd_server_info.py:40
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:57
msgid "List mailboxes on server SERVER only."
msgstr ""

#: ../pykolab/cli/cmd_check_quota.py:57
msgid "Compare existing IMAP quota with LDAP quota."
msgstr "Vorhandenes IMAP-Kontingent mit LDAP-Kontingent vergleichen."

#: ../pykolab/cli/cmd_check_quota.py:84 ../pykolab/cli/cmd_user_info.py:51
#, python-format
msgid "No such user %s"
msgstr "Kein solcher Benutzer %s"

#: ../pykolab/cli/cmd_check_quota.py:98
#, python-format
msgid "No quota for user %s"
msgstr "Kein Kontingent für Benutzer %s"

#: ../pykolab/cli/cmd_check_quota.py:105
#, python-format
msgid "user quota does not match for %s (IMAP: %d, LDAP: %d)"
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:42
msgid "Set metadata for folder to ANNOTATION=VALUE"
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:50
msgid "Create folder on PARTITION."
msgstr "Verzeichnis anlegen auf PARTITION."

#: ../pykolab/cli/cmd_create_mailbox.py:60
msgid "Invalid argument"
msgstr "Ungültiges Argument"

#: ../pykolab/cli/cmd_create_mailbox.py:68
msgid "Invalid argument for metadata"
msgstr "Ungültiges Argument für die Metadaten"

#: ../pykolab/cli/cmd_delete_domain.py:36
msgid "Delete a domain."
msgstr "Domäne löschen."

#: ../pykolab/cli/cmd_delete_domain.py:46
msgid "Force deleting the domain even if it contains user accounts"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:45
#: ../pykolab/cli/cmd_delete_mailbox_acl.py:49
#: ../pykolab/cli/cmd_set_mailbox_acl.py:50
#: ../pykolab/cli/cmd_set_mailbox_acl.py:55
msgid "ACI Subject"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:48
#: ../pykolab/cli/cmd_list_mailbox_acls.py:43
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:54
#: ../pykolab/cli/cmd_set_mailbox_acl.py:54
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:66
#: ../pykolab/cli/cmd_set_quota.py:48 ../tests/unit/test-015-translate.py:15
#: ../tests/unit/test-015-translate.py:19
msgid "Folder name"
msgstr "Ordnername"

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:60
#: ../pykolab/cli/cmd_list_mailbox_acls.py:54
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:80
#: ../pykolab/cli/cmd_set_mailbox_acl.py:67
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:94
#: ../pykolab/cli/cmd_set_quota.py:60
#, python-format
msgid "No such folder %r"
msgstr "Kein Ordner %r verfügbar"

#: ../pykolab/cli/cmd_delete_mailbox.py:44
msgid "No mailbox specified"
msgstr "Keine Mailbox angegeben"

#: ../pykolab/cli/cmd_delete_mailbox.py:57
#, python-format
msgid "No such folder(s): %s"
msgstr "Kein solch Verzeichnis: %s"

#: ../pykolab/cli/cmd_delete_mailbox.py:62
msgid "No folders to delete."
msgstr "Keine zu löschenden Ordner."

#: ../pykolab/cli/cmd_delete_mailbox.py:69
#, python-format
msgid "Could not delete mailbox '%s'"
msgstr "Konnte Postfach '%s' nicht löschen"

#: ../pykolab/cli/cmd_delete_message.py:36
msgid "Delete a message from a folder"
msgstr "Lösche eine Nachricht aus Verzeichnis"

#: ../pykolab/cli/cmd_delete_message.py:49
msgid "Specify a UID"
msgstr "Geben Sie eine Benutzerkennung an"

#: ../pykolab/cli/cmd_delete_message.py:52
#: ../pykolab/cli/cmd_list_messages.py:76
msgid "Specify a folder"
msgstr "Geben Sie einen Ordner an"

#: ../pykolab/cli/cmd_export_mailbox.py:38
msgid "All folders this user has access to"
msgstr "Alle Ordner auf die der Benutzer zugriff hat"

#: ../pykolab/cli/cmd_export_mailbox.py:108
#, python-format
msgid "%s is not a directory"
msgstr "%s ist kein Verzeichnis"

#: ../pykolab/cli/cmd_export_mailbox.py:118
#, python-format
msgid "ZIP file at %s.zip"
msgstr "ZIP-Datei unter %s.zip"

#: ../pykolab/cli/cmd_export_mailbox.py:120
#, python-format
msgid "No directories found for user %s"
msgstr "Keine Verzeichnisse für Benutzer %s gefunden"

#: ../pykolab/cli/cmd_find_domain.py:36
msgid "Find a domain."
msgstr "Domain finden."

#: ../pykolab/cli/cmd_list_deleted_mailboxes.py:43
#: ../pykolab/cli/cmd_list_domain_mailboxes.py:42
#: ../pykolab/cli/cmd_list_mailboxes.py:45
#: ../pykolab/cli/cmd_list_user_subscriptions.py:41
msgid "Display raw IMAP UTF-7 folder names"
msgstr ""

#: ../pykolab/cli/cmd_list_domain_mailboxes.py:59
msgid "Domain"
msgstr "Domäne"

#: ../pykolab/cli/cmd_list_mailboxes.py:87
#, python-format
msgid "Appending folder search for %r"
msgstr ""

#: ../pykolab/cli/cmd_list_mailbox_metadata.py:44
msgid "List annotations as user USER"
msgstr ""

#: ../pykolab/cli/cmd_list_messages.py:43
msgid "Include messages flagged as \\Deleted"
msgstr ""

#: ../pykolab/cli/cmd_list_messages.py:61
msgid "List messages as user USER"
msgstr ""

#: ../pykolab/cli/cmd_list_messages.py:65
msgid "List messages in a folder"
msgstr "Nachrichten in einem Ordner auflisten"

#: ../pykolab/cli/cmd_list_quota.py:73 ../pykolab/cli/cmd_list_quota.py:89
#, python-format
msgid "The quota for folder %s is set to literally allow 0KB of storage."
msgstr ""

#: ../pykolab/cli/cmd_list_user_subscriptions.py:47
msgid "List unsubscribed folders"
msgstr "Liste nicht abonnierte Ordner"

#: ../pykolab/cli/cmd_list_user_subscriptions.py:50
msgid "List the folders a user is subscribed to."
msgstr "Liste die Ordner, die ein Benutzer abonniert hat."

#: ../pykolab/cli/cmd_list_user_subscriptions.py:98
#, python-format
msgid "No unsubscribed folders for user %s"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:45
msgid ""
"Do not actually delete mailboxes, but report what mailboxes would have been "
"deleted."
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:49
msgid "Clean up mailboxes that do no longer have an owner."
msgstr "Mailboxen bereinigen, die keinen Besitzer mehr haben."

#: ../pykolab/cli/cmd_mailbox_cleanup.py:85
#: ../pykolab/cli/cmd_mailbox_cleanup.py:95
#, python-format
msgid "Would have deleted folder 'user/%s' (dryrun)"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:87
#: ../pykolab/cli/cmd_mailbox_cleanup.py:97
#, python-format
msgid "Deleting folder 'user/%s'"
msgstr "Ordner 'user/%s' wird gelöscht"

#: ../pykolab/cli/cmd_mailbox_cleanup.py:101
#, python-format
msgid "Error deleting folder 'user/%s'"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:103
#, python-format
msgid "Valid recipient found for 'user/%s'"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:128
#: ../pykolab/cli/cmd_mailbox_cleanup.py:138
#, python-format
msgid "Would have deleted folder '%s' (dryrun)"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:130
#: ../pykolab/cli/cmd_mailbox_cleanup.py:140
#, python-format
msgid "Deleting folder '%s'"
msgstr "Ordner '%s' wird gelöscht"

#: ../pykolab/cli/cmd_mailbox_cleanup.py:134
#: ../pykolab/cli/cmd_mailbox_cleanup.py:144
#, python-format
msgid "Error deleting folder '%s'"
msgstr "Fehler beim Löschen des Ordners '%s'"

#: ../pykolab/cli/cmd_mailbox_cleanup.py:153
#, python-format
msgid "Skipping removal of ACL %s for subject %s on folder %s"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:165
#, python-format
msgid "Would have deleted ACL %s for subject %s on folder %s"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:184
#, python-format
msgid "Error removing ACL %s for subject %s from folder %s"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:49
msgid "Invalid or unqualified email address."
msgstr "Ungültige oder unqualifizierte E-Mail-Adresse."

#: ../pykolab/cli/cmd_remove_mailaddress.py:57
#, python-format
msgid "No recipient found for email address %r"
msgstr "Kein Empfänger gefunden für E-Mail-Adresse %r"

#: ../pykolab/cli/cmd_remove_mailaddress.py:60
#, python-format
msgid "Found the following recipient(s): %r"
msgstr "Folgende Empfänger gefunden: %r"

#: ../pykolab/cli/cmd_remove_mailaddress.py:66
#, python-format
msgid "Using the following mail attributes: %r"
msgstr "Nutze folgende Mail-Attribute: %r"

#: ../pykolab/cli/cmd_remove_mailaddress.py:90
msgid "Found the following recipients:"
msgstr "Folgende Empfänger gefunden:"

#: ../pykolab/cli/cmd_remove_user_subscription.py:37
msgid "Unsubscribe a user from a folder."
msgstr "Entferne einen Benutzer-Abonement von einem Ordner."

#: ../pykolab/cli/cmd_remove_user_subscription.py:86
#, python-format
msgid "Successfully unsubscribed user %s from the following folders:"
msgstr "Für Benutzer %s wurde das Abonnement folgender Ordner erfolgreich beendet:"

#: ../pykolab/cli/cmd_remove_user_subscription.py:92
#, python-format
msgid "User %s was not unsubscribed from any folders."
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:52
msgid "No target mailbox name specified"
msgstr "Keine Name für Ziel-Postfach angegeben"

#: ../pykolab/cli/cmd_rename_mailbox.py:54
msgid "No source mailbox name specified"
msgstr "Keine Name für Quell-Postfach angegeben"

#: ../pykolab/cli/cmd_rename_mailbox.py:66
#, python-format
msgid "Source folder %r does not exist"
msgstr "Ursprungsordner %r existiert nicht"

#: ../pykolab/cli/cmd_rename_mailbox.py:70
#, python-format
msgid "Target folder %r already exists"
msgstr "Zielordner %r existiert bereits"

#: ../pykolab/cli/cmd_set_mailbox_acl.py:47
#: ../pykolab/cli/cmd_set_mailbox_acl.py:51
#: ../pykolab/cli/cmd_set_mailbox_acl.py:56
msgid "ACI Permissions"
msgstr "ACI-Berechtigungen"

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:45
msgid "Set annotation as user USER"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:59
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:63
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:68
msgid "Metadata value"
msgstr "Metadatenwert"

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:62
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:67
msgid "Metadata path"
msgstr "Metadatenpfad"

#: ../pykolab/cli/cmd_set_quota.py:45 ../pykolab/cli/cmd_set_quota.py:49
msgid "New quota"
msgstr "Neues Kontingent"

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:44
msgid "Delete mailboxes for recipients that do not appear to exist in LDAP."
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:50
msgid "Display changes, do not apply them."
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:91
#, python-format
msgid "Domains in IMAP not in LDAP: %r"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:108
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:156
#, python-format
msgid ""
"No recipients for '%s' (would have deleted the mailbox if not for --dry-"
"run)!"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:113
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:161
#, python-format
msgid "Deleting mailbox '%s' because it has no recipients"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:117
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:165
#, python-format
msgid "An error occurred removing mailbox %r: %r"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:119
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:167
#, python-format
msgid "Not automatically deleting shared folder '%s'"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:121
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:169
#, python-format
msgid "No recipients for '%s' (use --delete to delete)!"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:150
#, python-format
msgid "Multiple recipients for '%s'!"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:52
msgid "Synchronize LDAP and IMAP"
msgstr "Synchronisiere LDAP und IMAP"

#: ../pykolab/cli/cmd_sync.py:60
msgid "Resync from the beginning"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:68
msgid "Only sync the specified domain"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:82
#, python-format
msgid "Found %d domains in %d seconds"
msgstr "%d Domains in %d Sekunden gefunden"

#: ../pykolab/cli/cmd_sync.py:98
#, python-format
msgid "Running for domain %s"
msgstr "Starte für Domain %s"

#: ../pykolab/cli/cmd_sync.py:105
#, python-format
msgid "Synchronizing users for %s took %d seconds"
msgstr "Benutzer für %s zu synchronisieren dauerte %d Sekunden"

#: ../pykolab/cli/cmd_sync.py:123
#, python-format
msgid "Worker process %s handling %s"
msgstr ""

#: ../pykolab/cli/cmd_undelete_mailbox.py:39
msgid "Do not actually execute, but state what would have been executed."
msgstr ""

#: ../pykolab/cli/cmd_undelete_mailbox.py:42
msgid "Recover mailboxes previously deleted."
msgstr "Kürzlich gelöschte Mailboxen wiederherstellen."

#: ../pykolab/cli/cmd_user_info.py:41
msgid "Email address"
msgstr "E-Mail-Adresse"

#. This is a nested command
#. This is a nested component
#: ../pykolab/cli/commands.py:97 ../pykolab/setup/components.py:90
#, python-format
msgid "Command Group: %s"
msgstr "Befehlsgruppe: %s"

#: ../pykolab/cli/commands.py:112 ../pykolab/cli/commands.py:117
msgid "No such command."
msgstr "Dieses Kommando existiert nicht."

#: ../pykolab/cli/commands.py:167 ../pykolab/setup/components.py:231
#, python-format
msgid "Command '%s' already registered"
msgstr "Befehl '%s' ist bereits registriert"

#: ../pykolab/cli/commands.py:192 ../pykolab/setup/components.py:257
#: ../wallace/modules.py:391
#, python-format
msgid "Alias for %s"
msgstr "Alias für %s"

#: ../pykolab/cli/commands.py:200 ../pykolab/setup/components.py:265
msgid "Not yet implemented"
msgstr "Diese Funktion ist noch nicht implementiert"

#: ../pykolab/cli/sieve/cmd_list.py:49 ../pykolab/cli/sieve/cmd_put.py:42
#: ../pykolab/cli/sieve/cmd_refresh.py:44 ../pykolab/cli/sieve/cmd_test.py:43
msgid "Email Address"
msgstr "E-mail-Adresse"

#: ../pykolab/cli/sieve/cmd_refresh.py:99
#: ../pykolab/plugins/sievemgmt/__init__.py:111
#, python-format
msgid "Found the following scripts for user %s: %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:100
#: ../pykolab/plugins/sievemgmt/__init__.py:112
#, python-format
msgid "And the following script is active for user %s: %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:178
#: ../pykolab/plugins/sievemgmt/__init__.py:190
#, python-format
msgid ""
"Delivery to folder active, but no folder name attribute available for user "
"%r"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:181
#: ../pykolab/plugins/sievemgmt/__init__.py:193
msgid "Delivery to folder active, but no folder name attribute configured"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:359
#, python-format
msgid "MANAGEMENT script for user %s contents: %r"
msgstr "VERWALTUNGS-Skript für Benutzer %s enthält: %r"

#: ../pykolab/cli/sieve/cmd_refresh.py:364
#: ../pykolab/plugins/sievemgmt/__init__.py:374
#, python-format
msgid "Uploading script MANAGEMENT failed for user %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:366
#: ../pykolab/plugins/sievemgmt/__init__.py:376
#, python-format
msgid "Uploading script MANAGEMENT for user %s succeeded"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:377
#: ../pykolab/plugins/sievemgmt/__init__.py:387
#, python-format
msgid "Including script %s in USER (for user %s)"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:386
#: ../pykolab/plugins/sievemgmt/__init__.py:396
#, python-format
msgid "Uploading script USER failed for user %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:388
#: ../pykolab/plugins/sievemgmt/__init__.py:398
#, python-format
msgid "Uploading script USER for user %s succeeded"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:416
#: ../pykolab/plugins/sievemgmt/__init__.py:426
#, python-format
msgid "Uploading script MASTER failed for user %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:418
#: ../pykolab/plugins/sievemgmt/__init__.py:428
#, python-format
msgid "Uploading script MASTER for user %s succeeded"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:40
msgid "Unspecified command issue identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:50
msgid "Invalid command issue identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:60
#: ../pykolab/cli/telemetry/cmd_examine_session.py:65
msgid "Invalid session identifier"
msgstr "Ungültiger Sitzungsbezeichner"

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:75
#: ../pykolab/cli/telemetry/cmd_examine_session.py:100
#, python-format
msgid "Session by %s on server %s"
msgstr "Sitzung von %s auf Server %s"

#: ../pykolab/cli/telemetry/cmd_examine_session.py:43
msgid "Unspecified session identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:35
msgid "List Options"
msgstr "Liste Optionen"

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:40
msgid "Display sessions since ..."
msgstr "Zeige Sitzungen seit..."

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:58
#, python-format
msgid "Session for user %s started at %s with ID %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:57 ../pykolab/conf/entitlement.py:80
#: ../pykolab/conf/entitlement.py:98 ../pykolab/conf/entitlement.py:116
#: ../pykolab/conf/entitlement.py:230 ../pykolab/conf/entitlement.py:246
#: ../pykolab/conf/entitlement.py:262
#, python-format
msgid "Invalid entitlement verification certificate at %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:120 ../pykolab/conf/entitlement.py:123
msgid "Invalid entitlement certificate"
msgstr ""

#: ../pykolab/conf/entitlement.py:132
#, python-format
msgid "Parsing entitlement file %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:141
#, python-format
msgid "License file %s not readable!"
msgstr "Lizenzdatei %s nicht lesbar!"

#: ../pykolab/conf/entitlement.py:147
msgid "No entitlement directory found"
msgstr ""

#: ../pykolab/conf/__init__.py:87
#, python-format
msgid "Setting %s to %r (from defaults)"
msgstr "Setze %s auf %r (aus den Standardeinstellungen)"

#: ../pykolab/conf/__init__.py:106
#, python-format
msgid "Setting %s to %r (from CLI, verified)"
msgstr "Setze %s auf %r (von der Kommandozeile, überprüft)"

#: ../pykolab/conf/__init__.py:109
#, python-format
msgid "Setting %s to %r (from CLI, not checked)"
msgstr "Setze %s auf %r (von der Kommandozeile, nicht überprüft)"

#: ../pykolab/conf/__init__.py:150 ../pykolab/conf/__init__.py:207
#, python-format
msgid "Setting %s_%s to '****' (from configuration file)"
msgstr "Setze %s_%s auf '****' (aus Konfigurationsdatei)"

#: ../pykolab/conf/__init__.py:152 ../pykolab/conf/__init__.py:209
#, python-format
msgid "Setting %s_%s to %r (from configuration file)"
msgstr "Setze %s_%s auf %r (aus Konfigurationsdatei)"

#: ../pykolab/conf/__init__.py:162
msgid "Setting options from configuration file"
msgstr "Hole Optionen aus Konfigurationsdatei"

#: ../pykolab/conf/__init__.py:223
#, python-format
msgid "Configuration file %s not readable"
msgstr "Konfigurationsdatei %s ist nicht lesbar"

#: ../pykolab/conf/__init__.py:226
#, python-format
msgid "Reading configuration file %s"
msgstr "Lese Konfigurationsdatei %s"

#: ../pykolab/conf/__init__.py:230
#, python-format
msgid "Invalid configuration file %s"
msgstr "Ungültige Konfigurationsdatei %s"

#: ../pykolab/conf/__init__.py:233
#, python-format
msgid "No master configuration section [kolab] in configuration file %s"
msgstr ""

#. #
#. # Runtime Options
#. #
#: ../pykolab/conf/__init__.py:267
msgid "Runtime Options"
msgstr "Laufzeit-Einstellungen"

#: ../pykolab/conf/__init__.py:272
msgid "Configuration file to use"
msgstr "Konfigurationsdatei, die benutzt werden soll"

#: ../pykolab/conf/__init__.py:278
msgid ""
"Set the debugging verbosity. Maximum is 9, tracing protocols like LDAP, SQL "
"and IMAP."
msgstr ""

#: ../pykolab/conf/__init__.py:286
msgid "Use the default answer to all questions."
msgstr ""

#: ../pykolab/conf/__init__.py:292
msgid "Set the logging level. One of info, warn, error, critical or debug"
msgstr ""

#: ../pykolab/conf/__init__.py:300
msgid "Log file to use"
msgstr "Protokolldatei"

#: ../pykolab/conf/__init__.py:306
msgid "Be quiet."
msgstr "Sei still."

#: ../pykolab/conf/__init__.py:312
msgid "Answer yes to all questions."
msgstr "Ja auf alle Fragen."

#: ../pykolab/conf/__init__.py:334
msgid "No command supplied"
msgstr "Kein Befehl angegeben"

#: ../pykolab/conf/__init__.py:422
msgid "Insufficient options. Need section, key and value -in that order."
msgstr "Unzureichende Optionen. Brauche Sektion, Schlüssel und Wert in dieser Reihenfolge."

#: ../pykolab/conf/__init__.py:425
#, python-format
msgid "No section '%s' exists."
msgstr "Es existiert keine Sektion '%s'."

#: ../pykolab/conf/__init__.py:467
#, python-format
msgid "Setting %s to %r (from the default values for CLI options)"
msgstr "Setze %s auf %r (aus den Standardwerten für Kommandozeilenoptionen)"

#: ../pykolab/conf/__init__.py:540
#, python-format
msgid "Could not execute configuration function: %s"
msgstr "Konnte die Konfigurationsfunktion nicht ausführen: %s"

#: ../pykolab/conf/__init__.py:548
#, python-format
msgid "Option %s/%s does not exist in config file %s, pulling from defaults"
msgstr "Die Option %s/%s existiert in der Konfigurationsdatei %s nicht, sie wird aus den Standardeinstellungen geholt"

#: ../pykolab/conf/__init__.py:556 ../pykolab/conf/__init__.py:559
msgid "Option does not exist in defaults."
msgstr "Diese Option hat keinen Standardwert."

#: ../pykolab/conf/__init__.py:569
#, python-format
msgid "Configuration file %s not readable."
msgstr "Konfigurationsdatei %s ist nicht lesbar."

#: ../pykolab/conf/__init__.py:572
#, python-format
msgid "Configuration file %s does not exist."
msgstr "Konfigurationsdatei %s existiert nicht."

#: ../pykolab/conf/__init__.py:577
msgid ""
"WARNING: A negative debug level value does not make this program be any more"
" silent."
msgstr "Warnung: Eine negative Fehlerprotokollierungszahl macht dieses Programm nicht noch stiller."

#: ../pykolab/conf/__init__.py:583
msgid "This program has 9 levels of verbosity. Using the maximum of 9."
msgstr "Dieses Programm hat 9 Ebenen der Detailliertheit. Benutze das Maximum 9."

#: ../pykolab/conf/__init__.py:591 ../pykolab/conf/__init__.py:597
#: ../pykolab/conf/__init__.py:601 ../pykolab/conf/__init__.py:607
msgid "Cannot start SASL authentication daemon"
msgstr "Konnte SASL Authentisierungsdaemon nicht starten"

#: ../pykolab/conf/__init__.py:618
msgid "No imaplib library found."
msgstr "Keine imaplib-Bibliothek gefunden."

#: ../pykolab/conf/__init__.py:628
msgid "No LMTP class found in the smtplib library."
msgstr "Keine Klasse namens LMTP in der smtplib-Bibliothek gefunden."

#: ../pykolab/conf/__init__.py:638
msgid "No SMTP class found in the smtplib library."
msgstr "Keine Klasse namens SMTP in der smtplib-Bibliothek gefunden."

#: ../pykolab/conf/__init__.py:652
#, python-format
msgid "Found you specified a specific set of items to test: %s"
msgstr ""

#: ../pykolab/conf/__init__.py:660
#, python-format
msgid "Selectively selecting: %s"
msgstr ""

#: ../pykolab/constants.py.in:40
msgid ""
"PyKolab is a Kolab Systems product. For more information about Kolab or "
"PyKolab, visit http://www.kolabsys.com"
msgstr ""

#: ../pykolab/constants.py.in:53
msgid "WARNING"
msgstr "WARNUNG"

#: ../pykolab/constants.py.in:53
msgid ""
"The Fully Qualified Domain Name or FQDN for this system is incorrect. "
"Falling back to 'localdomain'."
msgstr ""

#: ../pykolab/constants.py.in:72
msgid "389 Directory Server or Red Hat Directory Server"
msgstr "389 Verzeichnisserver oder Red Hat Verzeichnisserver"

#: ../pykolab/constants.py.in:76 ../pykolab/constants.py.in:80
msgid "OpenLDAP or compatible"
msgstr "OpenLDAP oder kompatibel"

#: ../pykolab/imap/cyrus.py:83
#, python-format
msgid "Could not connect to Cyrus IMAP server %r"
msgstr "Verbindung zum Cyrus IMAP-Server %r nicht möglich"

#: ../pykolab/imap/cyrus.py:150 ../pykolab/imap/dovecot.py:287
#, python-format
msgid "Continuing with separator: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:159
msgid "Detected we are running in a Murder topology"
msgstr "Dieses System läuft in einer Murder-Topologie"

#: ../pykolab/imap/cyrus.py:167
msgid "This system is not part of a murder topology"
msgstr "Dieses System ist nicht Teil einer Murder-Topologie"

#: ../pykolab/imap/cyrus.py:196
#, python-format
msgid "Checking actual backend server for folder %s through annotations"
msgstr ""

#: ../pykolab/imap/cyrus.py:206
#, python-format
msgid ""
"Possibly reproducing the find mailfolder server answer from previously "
"detected and stored annotation value: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:236
#, python-format
msgid "Could not get the annotations after %s tries."
msgstr ""

#: ../pykolab/imap/cyrus.py:250
#, python-format
msgid "No annotations for %s: %r"
msgstr "Keine Annotationen für %s: %r"

#: ../pykolab/imap/cyrus.py:262
#, python-format
msgid "Server for INBOX folder %s is %s"
msgstr "Server für EINGANGS-Ordner %s ist %s"

#. Removed server reconnection for dovecot, we only have one server
#: ../pykolab/imap/cyrus.py:294 ../pykolab/imap/dovecot.py:313
#, python-format
msgid "Setting quota for folder %s to %s"
msgstr "Kontingent für Ordner %s auf %s wird festgelegt"

#: ../pykolab/imap/cyrus.py:305 ../pykolab/imap/dovecot.py:317
#, python-format
msgid "Could not set quota for mailfolder %s"
msgstr "Kontingent für Mailordner %s konnte nicht festgelegt werden"

#: ../pykolab/imap/cyrus.py:319 ../pykolab/imap/dovecot.py:322
#, python-format
msgid "Moving INBOX folder %s to %s on partition %s"
msgstr "EINGANGS-Ordner wird von %s nach %s auf Partition %s verschoben"

#: ../pykolab/imap/cyrus.py:329 ../pykolab/imap/dovecot.py:324
#, python-format
msgid "Moving INBOX folder %s to %s"
msgstr "EINGANGS-Ordner wird von %s nach %s verschoben"

#: ../pykolab/imap/cyrus.py:355
#, python-format
msgid "Setting annotation %s on folder %s"
msgstr "Setze Annotation %s auf Verzeichnis %s"

#: ../pykolab/imap/cyrus.py:366
#, python-format
msgid "Could not set annotation %r on mail folder %r: %r"
msgstr "Konnte Annotation %r auf Verzeichnis %r nicht setzen: %r"

#: ../pykolab/imap/cyrus.py:376 ../pykolab/imap/dovecot.py:453
#, python-format
msgid "Transferring folder %s from %s to %s"
msgstr "Übertrage Verzeichnis %s von %s nach %s"

#: ../pykolab/imap/cyrus.py:464 ../pykolab/imap/dovecot.py:513
#, python-format
msgid "Undeleting %s to %s"
msgstr "Wiederherstellen %s nach %s"

#: ../pykolab/imap/cyrus.py:484
#, python-format
msgid "Would have transferred %s from %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:491 ../pykolab/imap/dovecot.py:526
#, python-format
msgid "Would have renamed %s to %s"
msgstr ""

#: ../pykolab/imap/dovecot.py:222
#, python-format
msgid "Could not connect to Dovecot IMAP server %r"
msgstr ""

#: ../pykolab/imap/dovecot.py:294
msgid "Detected METADATA support"
msgstr ""

#: ../pykolab/imap/dovecot.py:297
#, python-format
msgid "This system does not support METADATA: '%s'"
msgstr ""

#: ../pykolab/imap/dovecot.py:524
#, python-format
msgid "Would have transfered %s from %s to %s"
msgstr "Haben %s von %s nach %s übertragen"

#: ../pykolab/imap/__init__.py:46
#, python-format
msgid "Cleaning up ACL entries for %s across all folders"
msgstr ""

#: ../pykolab/imap/__init__.py:61
#, python-format
msgid "Cleaning up ACL entries referring to identifier %s"
msgstr ""

#: ../pykolab/imap/__init__.py:70
#, python-format
msgid "Iterating over %d folders"
msgstr "Iteriere über %d Verzeichnisse"

#. Set the ACL to '' (effectively deleting the ACL entry)
#: ../pykolab/imap/__init__.py:83
#, python-format
msgid "Removing acl %r for subject %r from folder %r"
msgstr ""

#: ../pykolab/imap/__init__.py:160
msgid "No administrator password is available."
msgstr ""

#: ../pykolab/imap/__init__.py:168
#, python-format
msgid "Logging on to Cyrus IMAP server %s"
msgstr "Anmeldung am Cyrus IMAP Server %s"

#: ../pykolab/imap/__init__.py:177
#, python-format
msgid "Logging on to Dovecot IMAP server %s"
msgstr "Anmeldung am Dovecot IMAP Server %s"

#: ../pykolab/imap/__init__.py:186
#, python-format
msgid "Logging on to generic IMAP server %s"
msgstr "Anmeldung am generischen IMAP Server %s"

#: ../pykolab/imap/__init__.py:204
#, python-format
msgid "Reusing existing IMAP server connection to %s"
msgstr "Verbindung zum IMAP-Server %s wird wieder verwendet"

#: ../pykolab/imap/__init__.py:206
#, python-format
msgid "Reconnecting to IMAP server %s"
msgstr "Verbinde nochmal zum IMAP Server %s"

#: ../pykolab/imap/__init__.py:223
msgid "Called imap.disconnect() on a server that we had no connection to."
msgstr ""

#: ../pykolab/imap/__init__.py:236
#, python-format
msgid "Could not create folder %r on server %r"
msgstr ""

#: ../pykolab/imap/__init__.py:247
#, python-format
msgid "Could not create folder %r"
msgstr "Ordner %r konnte nicht erstellt werden"

#: ../pykolab/imap/__init__.py:257 ../pykolab/imap/__init__.py:259
#, python-format
msgid "%r has no attribute %s"
msgstr "%r hat kein Attribut %s"

#: ../pykolab/imap/__init__.py:360
#, python-format
msgid "Invalid access identifier %r for subject %r"
msgstr ""

#: ../pykolab/imap/__init__.py:397
#, python-format
msgid "Could not set ACL for %s on folder %s: %r"
msgstr ""

#: ../pykolab/imap/__init__.py:429 ../pykolab/imap/__init__.py:465
#, python-format
msgid "Creating new shared folder %s"
msgstr "Erzeuge einen neuen geteilten Ordner %s"

#: ../pykolab/imap/__init__.py:494 ../pykolab/imap/__init__.py:786
#, python-format
msgid "Downcasing mailbox name %r"
msgstr ""

#: ../pykolab/imap/__init__.py:498
#, python-format
msgid "Creating new mailbox for user %s"
msgstr "Erzeuge eine neue Mailbox für Benutzer %s"

#: ../pykolab/imap/__init__.py:511
#, python-format
msgid "Could not create the mailbox for user %s, aborting."
msgstr ""

#: ../pykolab/imap/__init__.py:525 ../pykolab/imap/__init__.py:654
msgid "Waiting for the Cyrus IMAP Murder to settle..."
msgstr ""

#: ../pykolab/imap/__init__.py:600
#, python-format
msgid "Creating additional folders for user %s"
msgstr "Erzeuge weitere Order für Benutzer %s"

#: ../pykolab/imap/__init__.py:628
#, python-format
msgid "Waiting for the Cyrus murder to settle... %r"
msgstr ""

#: ../pykolab/imap/__init__.py:643
#, python-format
msgid "Correcting additional folder name from %r to %r"
msgstr ""

#: ../pykolab/imap/__init__.py:659
#, python-format
msgid "Mailbox already exists: %s"
msgstr "Mailbox existiert bereits: %s"

#: ../pykolab/imap/__init__.py:699
msgid "Subscribing user to the additional folders"
msgstr "Abonniere weitere Ordner für den Benutzer"

#: ../pykolab/imap/__init__.py:713
msgid "Using the following tests for folder subscriptions:"
msgstr ""

#: ../pykolab/imap/__init__.py:715
#, python-format
msgid "    %r"
msgstr "    %r"

#: ../pykolab/imap/__init__.py:718
#, python-format
msgid "Folder %s"
msgstr "Ordner %s"

#: ../pykolab/imap/__init__.py:730
#, python-format
msgid "Subscribing %s to folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:734
#, python-format
msgid "Subscribing %s to folder %s failed: %r"
msgstr ""

#: ../pykolab/imap/__init__.py:760
#, python-format
msgid "Could not set quota on %s"
msgstr "Kontingent auf %s konnte nicht festgelegt werden"

#: ../pykolab/imap/__init__.py:767
#, python-format
msgid "Could not rename %s to reside on partition %s"
msgstr ""

#: ../pykolab/imap/__init__.py:804
#, python-format
msgid "INBOX folder to rename (%s) does not exist"
msgstr "Umzubenennender EINGANGS-Ordner (%s) ist nicht vorhanden"

#: ../pykolab/imap/__init__.py:807 ../pykolab/imap/__init__.py:915
#, python-format
msgid "Renaming INBOX from %s to %s"
msgstr "EINGANGS-Ordner wird von %s in %s umbenannt"

#: ../pykolab/imap/__init__.py:811
#, python-format
msgid "Could not rename INBOX folder %s to %s"
msgstr "Konnte EINGANGS-Ordner nicht von %s in %s umbenennen"

#: ../pykolab/imap/__init__.py:813 ../pykolab/imap/__init__.py:919
#, python-format
msgid ""
"Moving INBOX folder %s won't succeed as target folder %s already exists"
msgstr "EINGANGS-Ordner %s kann nicht verschoben werden, weil der Zielordner %s bereits vorhanden ist"

#: ../pykolab/imap/__init__.py:817
#, python-format
msgid "Server for mailbox %r is %r"
msgstr "Server für Postfach %r ist %r"

#: ../pykolab/imap/__init__.py:825
#, python-format
msgid "Looking for folder '%s', we found folders: %r"
msgstr "Auf der Suche nach dem Ordner '%s' haben wir diese Ordner gefunden: %r"

#: ../pykolab/imap/__init__.py:839 ../pykolab/imap/__init__.py:882
#: ../pykolab/imap/__init__.py:896
#, python-format
msgid "Removing ACL rights %s for subject %s on folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:871
#, python-format
msgid "Setting ACL rights %s for subject %s on folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:912
#, python-format
msgid "Found old INBOX folder %s"
msgstr "Alter EINGANGS-Ordner %s gefunden"

#: ../pykolab/imap/__init__.py:921
#, python-format
msgid "Did not find old folder user/%s to rename"
msgstr "Konnte alten Ordner user/%s nicht zum umbenennen finden."

#: ../pykolab/imap/__init__.py:923
msgid "Value for user is not a dictionary"
msgstr "Der Wert für user ist kein dictionary"

#. TODO: Go in fact correct the quota.
#: ../pykolab/imap/__init__.py:991
#, python-format
msgid "Cannot get current IMAP quota for folder %s"
msgstr "Kann aktuelles IMAP-Kontingent für den Ordner %s nicht holen"

#: ../pykolab/imap/__init__.py:1004
#, python-format
msgid "Quota for %s currently is %s"
msgstr "Kontingent für %s ist aktuell %s"

#: ../pykolab/imap/__init__.py:1010
#, python-format
msgid "Adjusting authentication database quota for folder %s to %d"
msgstr ""

#: ../pykolab/imap/__init__.py:1015
#, python-format
msgid "Correcting quota for %s to %s (currently %s)"
msgstr "Kontingent für %s wird zu %s korrigiert (aktuell %s)"

#: ../pykolab/imap/__init__.py:1092
#, python-format
msgid "Checking folder: %s"
msgstr "Überprüfe Ordner: %s"

#: ../pykolab/imap/__init__.py:1097
#, python-format
msgid "Folder has no corresponding user (1): %s"
msgstr ""

#: ../pykolab/imap/__init__.py:1100
#, python-format
msgid "Folder has no corresponding user (2): %s"
msgstr ""

#. We got user identifier only
#: ../pykolab/imap/__init__.py:1115
msgid "Please don't give us just a user identifier"
msgstr ""

#: ../pykolab/imap/__init__.py:1118
#, python-format
msgid "Deleting folder %s"
msgstr "Lösche Verzeichnis %s"

#: ../pykolab/__init__.py:50
msgid "Returning thread local configuration"
msgstr ""

#: ../pykolab/itip/__init__.py:47
#, python-format
msgid "Method %r not really interesting for us."
msgstr ""

#: ../pykolab/itip/__init__.py:53
#, python-format
msgid "Raw iTip payload (%r): %r"
msgstr ""

#: ../pykolab/itip/__init__.py:66
msgid "Could not read iTip from message."
msgstr "Konnte iTip nicht aus Nachricht lesen."

#: ../pykolab/itip/__init__.py:74
#, python-format
msgid "Duplicate iTip object: %s"
msgstr "Verdopple iTip Objekt: %s"

#: ../pykolab/itip/__init__.py:99
msgid "iTip event without a start"
msgstr "iTip Termin ohne einen Beginn"

#: ../pykolab/itip/__init__.py:144
msgid "Message is not an iTip message (non-multipart message)"
msgstr "Nachricht ist keine iTip Nachricht (keine Multipart Nachricht)"

#: ../pykolab/itip/__init__.py:310
#, python-format
msgid "Send iTip reply %s for %s %r"
msgstr "Sende iTip Antwort %s für %s %r"

#: ../pykolab/itip/__init__.py:326
#, python-format
msgid "Failed to compose iTip reply message: %r: %s"
msgstr "Erstellung iTip Antwortnachricht fehlgeschlagen: %r: %s"

#: ../pykolab/itip/__init__.py:337 ../pykolab/itip/__init__.py:381
#: ../wallace/module_invitationpolicy.py:1253
#: ../wallace/module_invitationpolicy.py:1328
#: ../wallace/module_resources.py:1364
#, python-format
msgid "SMTP sendmail error: %r"
msgstr "SMTP sendmail-Fehler: %r"

#: ../pykolab/itip/__init__.py:369
#, python-format
msgid "Failed to compose iTip request message: %r"
msgstr "Erstellung iTip Anforderungsnachricht fehlgeschlagen: %r"

#: ../pykolab/logger.py:168 ../pykolab/logger.py:175
#, python-format
msgid "Could not change permissions on %s: %r"
msgstr "Konnte Berechtigungen auf %s nicht ändern: %r"

#: ../pykolab/logger.py:192
#, python-format
msgid "Cannot log to file %s: %s"
msgstr ""

#: ../pykolab/plugins/defaultfolders/__init__.py:47
#, python-format
msgid "Plugin %s called without required keyword %s."
msgstr ""

#: ../pykolab/plugins/defaultfolders/__init__.py:53
msgid "Could not parse additional_folders"
msgstr ""

#: ../pykolab/plugins/dynamicquota/__init__.py:58
#, python-format
msgid "No keyword %s passed to set_user_folder_quota"
msgstr ""

#: ../pykolab/plugins/dynamicquota/__init__.py:70
#, python-format
msgid "Quota '%s' not an integer!"
msgstr "Kontingent '%s' ist keine Ganzzahl!"

#: ../pykolab/plugins/__init__.py:70
#, python-format
msgid "ImportError for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:74
#, python-format
msgid "RuntimeError for plugin %s: %s"
msgstr "Laufzeitfehler von Plugin %s: %s"

#: ../pykolab/plugins/__init__.py:78
#, python-format
msgid "Plugin %s failed to load (%s: %s)"
msgstr "Plugin %s konnte nicht geladen werden (%s: %s)"

#: ../pykolab/plugins/__init__.py:116 ../pykolab/plugins/__init__.py:118
#, python-format
msgid "Cannot set defaults for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:120
#, python-format
msgid "Cannot set defaults for plugin %s: Unknown Error"
msgstr ""

#: ../pykolab/plugins/__init__.py:123
#, python-format
msgid "Not setting defaults for plugin %s: No function 'set_defaults()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:142
#, python-format
msgid "Cannot set runtime for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:144
#, python-format
msgid "Not setting runtime for plugin %s: No function 'set_runtime()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:163 ../pykolab/plugins/__init__.py:165
#, python-format
msgid "Cannot add options for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:167
#, python-format
msgid "Not adding options for plugin %s: No function 'add_options()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:187
#, python-format
msgid "Cannot check options for plugin %s: %s"
msgstr "Kein Zugriff auf Einstellungen des Plugins %s: %s"

#: ../pykolab/plugins/__init__.py:189
#, python-format
msgid "Not checking options for plugin %s: No function 'check_options()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:227
#, python-format
msgid "Executing hook %s for plugin %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:231 ../pykolab/plugins/__init__.py:233
#, python-format
msgid "Cannot execute hook %s for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:79
msgid "Attribute substitution for 'mail' failed in Recipient Policy"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:116
msgid "Could not parse the alternative mail routines"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:120
#, python-format
msgid "Alternative mail routines: %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:127
#, python-format
msgid ""
"An error occurred in composing the secondary mail attribute for entry %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:138
#: ../pykolab/plugins/recipientpolicy/__init__.py:153
#, python-format
msgid "Appending additional mail address: %s"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:142
#, python-format
msgid "Policy for secondary email address failed: %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:157
msgid ""
"Attribute substitution for 'alternative_mail' failed in Recipient Policy"
msgstr ""

#: ../pykolab/plugins/roundcubedb/__init__.py:48
#, python-format
msgid "user_delete: %r"
msgstr "user_delete: %r"

#: ../pykolab/plugins/roundcubedb/__init__.py:55
#: ../pykolab/setup/setup_roundcube.py:106
msgid "Roundcube installation path not found."
msgstr ""

#: ../pykolab/plugins/sievemgmt/__init__.py:51
msgid "Wrong number of arguments for sieve management plugin"
msgstr ""

#: ../pykolab/setup/components.py:58
msgid "Display this help."
msgstr "Zeige diese Hilfe."

#: ../pykolab/setup/components.py:149
msgid "No component selected, continuing for all components"
msgstr ""

#: ../pykolab/setup/components.py:187 ../pykolab/setup/components.py:192
msgid "No such component."
msgstr "Keine solche Komponente."

#: ../pykolab/setup/__init__.py:55
msgid "SELinux currently enforcing. Read https://git.kolab.org/u/1"
msgstr ""

#: ../pykolab/setup/__init__.py:67
msgid ""
"SELinux configured to enforce a policy on startup. Read "
"https://git.kolab.org/u/1"
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:47
msgid "Setup Free/Busy."
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:51
msgid "Free/Busy is not installed on this system"
msgstr ""

#: ../pykolab/setup/setup_guam.py:41
msgid "Setup Guam."
msgstr ""

#: ../pykolab/setup/setup_guam.py:45
msgid "Guam is not installed on this system"
msgstr ""

#: ../pykolab/setup/setup_guam.py:58
msgid "Could not start the guam service."
msgstr ""

#: ../pykolab/setup/setup_guam.py:63
msgid "Could not configure the guam service to start on boot"
msgstr ""

#: ../pykolab/setup/setup_imap.py:45
msgid "Setup IMAP."
msgstr "Richte IMAP ein."

#: ../pykolab/setup/setup_imap.py:89
msgid "Could not write out Cyrus IMAP configuration file /etc/imapd.conf"
msgstr ""

#: ../pykolab/setup/setup_imap.py:114
msgid "Could not write out Cyrus IMAP configuration file /etc/cyrus.conf"
msgstr ""

#: ../pykolab/setup/setup_imap.py:162
msgid "Could not start the cyrus-imapd and kolab-saslauthd services."
msgstr ""

#: ../pykolab/setup/setup_imap.py:177
msgid ""
"Could not configure to start on boot, the cyrus-imapd and kolab-saslauthd "
"services."
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:44
msgid "Setup the Kolab daemon."
msgstr "Richte den Kolab Daemon ein."

#: ../pykolab/setup/setup_kolabd.py:52
#, python-format
msgid ""
"\n"
"                            Copying the configuration section for 'example.org' over to\n"
"                            a section applicable to your domain '%s'.\n"
"                        "
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:84
msgid "Could not start the kolab server service."
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:96
msgid "Could not configure to start on boot, the kolab server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:45
msgid "LDAP Options"
msgstr "LDAP Optionen"

#: ../pykolab/setup/setup_ldap.py:52
msgid "Specify FQDN (overriding defaults)."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:60
msgid "Allow anonymous binds (default: no)."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:68
msgid "Skip setting up the LDAP server."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:76
msgid "Setup configuration for OpenLDAP compatibility."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:84
msgid "Setup configuration for Active Directory compatibility."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:92
msgid "Specify password for the Domain Manager."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:96
msgid "Setup LDAP."
msgstr "LDAP Einrichten"

#: ../pykolab/setup/setup_ldap.py:105
msgid "Skipping setup of LDAP, as specified"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:134
msgid ""
"\n"
"                        You can not configure Kolab to run against OpenLDAP\n"
"                        and Active Directory simultaneously.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:147
msgid ""
"\n"
"                                It seems 389 Directory Server has an existing\n"
"                                instance configured. This setup script does not\n"
"                                intend to destroy or overwrite your data. Please\n"
"                                make sure /etc/dirsrv/ and /var/lib/dirsrv/ are\n"
"                                clean so that this setup does not have to worry.\n"
"                            "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:162
msgid ""
"\n"
"                        Please supply a password for the LDAP administrator user\n"
"                        'admin', used to login to the graphical console of 389\n"
"                        Directory server.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:170
msgid "Administrator password"
msgstr "Administrator Passwort"

#: ../pykolab/setup/setup_ldap.py:180
msgid ""
"\n"
"                        Please supply a password for the LDAP Directory Manager\n"
"                        user, which is the administrator user you will be using\n"
"                        to at least initially log in to the Web Admin, and that\n"
"                        Kolab uses to perform administrative tasks.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:189
msgid "Directory Manager password"
msgstr "Verzeichnismanager Passwort"

#: ../pykolab/setup/setup_ldap.py:196
msgid ""
"\n"
"                        Please choose the system user and group the service\n"
"                        should use to run under. These should be existing,\n"
"                        unprivileged, local system POSIX accounts with no shell.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:206 ../pykolab/setup/setup_ldap.py:209
msgid "User"
msgstr "Benutzer"

#: ../pykolab/setup/setup_ldap.py:207 ../pykolab/setup/setup_ldap.py:210
msgid "Group"
msgstr "Gruppe"

#: ../pykolab/setup/setup_ldap.py:245
msgid ""
"\n"
"                        This setup procedure plans to set up Kolab Groupware for\n"
"                        the following domain name space. This domain name is\n"
"                        obtained from the reverse DNS entry on your network\n"
"                        interface. Please confirm this is the appropriate domain\n"
"                        name space.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:259
msgid "Domain name to use"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:264 ../pykolab/setup/setup_ldap.py:289
msgid ""
"\n"
"                                    Invalid input. Please try again.\n"
"                                "
msgstr "\n                                    Ungültige Eingabe. Bitte nochmals versuchen.\n                                "

#: ../pykolab/setup/setup_ldap.py:273
msgid ""
"\n"
"                        The standard root dn we composed for you follows. Please\n"
"                        confirm this is the root dn you wish to use.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:284
msgid "Root DN to use"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:336
msgid "No directory server setup tool available."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:348
msgid ""
"\n"
"                    Setup is now going to set up the 389 Directory Server. This\n"
"                    may take a little while (during which period there is no\n"
"                    output and no progress indication).\n"
"                "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:355
msgid "Setting up 389 Directory Server"
msgstr "Richte 389 Verzeichnisserver ein"

#: ../pykolab/setup/setup_ldap.py:367
msgid ""
"\n"
"                        An error was detected in the setup procedure for 389\n"
"                        Directory Server. This setup will write out stderr and\n"
"                        stdout to /var/log/kolab/setup.error.log and\n"
"                        /var/log/kolab/setup.out.log respectively, before it\n"
"                        exits.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:384
msgid "Setup DS stdout:"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:387
msgid "Setup DS stderr:"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:413
msgid "Could not copy the LDAP extensions for Kolab"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:416
msgid "Could not find the ldap Kolab schema file"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:429
msgid "Could not start the directory server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:438
msgid "Could not configure to start on boot, the directory server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:443
msgid ""
"\n"
"                        Please supply a Cyrus Administrator password. This\n"
"                        password is used by Kolab to execute administrative\n"
"                        tasks in Cyrus IMAP. You may also need the password\n"
"                        yourself to troubleshoot Cyrus IMAP and/or perform\n"
"                        other administrative tasks against Cyrus IMAP directly.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:453
msgid "Cyrus Administrator password"
msgstr "Cyrus Administrator Passwort"

#: ../pykolab/setup/setup_ldap.py:460
msgid ""
"\n"
"                        Please supply a Kolab Service account password. This\n"
"                        account is used by various services such as Postfix,\n"
"                        and Roundcube, as anonymous binds to the LDAP server\n"
"                        will not be allowed.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:469
msgid "Kolab Service password"
msgstr "Kolab-Dienst-Passwort"

#: ../pykolab/setup/setup_ldap.py:479
msgid "Writing out configuration to kolab.conf"
msgstr "Schreibe Einstellungen in kolab.conf"

#: ../pykolab/setup/setup_ldap.py:493
msgid "Inserting service users into LDAP."
msgstr "Füge Service-Benutzer ins LDAP ein."

#: ../pykolab/setup/setup_ldap.py:567
msgid "Writing out cn=kolab,cn=config"
msgstr "Schreibe cn=kolab,cn=config"

#: ../pykolab/setup/setup_ldap.py:583
#, python-format
msgid "Adding domain %s to list of domains for this deployment"
msgstr "Füge Domain %s zu dieser Installation hinzu"

#: ../pykolab/setup/setup_ldap.py:611
msgid "Disabling anonymous binds"
msgstr "Stelle anonymes Binden ab"

#. TODO: Ensure the uid attribute is unique
#. TODO^2: Consider renaming the general "attribute uniqueness to "uid
#. attribute uniqueness"
#: ../pykolab/setup/setup_ldap.py:619
msgid "Enabling attribute uniqueness plugin"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:625
msgid "Enabling referential integrity plugin"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:631
msgid "Enabling and configuring account policy plugin"
msgstr ""

#. Add kolab-admin role
#: ../pykolab/setup/setup_ldap.py:646
msgid "Adding the kolab-admin role"
msgstr "Füge Kolab-Admin Rolle hinzu"

#. User writeable attributes on root_dn
#: ../pykolab/setup/setup_ldap.py:657
#, python-format
msgid "Setting access control to %s"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:677
msgid "directory server admin service not available"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:685
msgid ""
"Could not start and configure to start on boot, the directory server admin "
"service."
msgstr ""

#: ../pykolab/setup/setup_manticore.py:44
msgid "Setup Manticore."
msgstr ""

#: ../pykolab/setup/setup_manticore.py:48
msgid "Manticore is not installed on this system"
msgstr ""

#: ../pykolab/setup/setup_manticore.py:94
msgid "Could not start the manticore service."
msgstr ""

#: ../pykolab/setup/setup_manticore.py:100
msgid "Could not configure the manticore service to start on boot"
msgstr ""

#: ../pykolab/setup/setup_mta.py:41
msgid "Setup MTA."
msgstr "Richte MTA ein."

#: ../pykolab/setup/setup_mta.py:317 ../pykolab/setup/setup_php.py:106
#, python-format
msgid "Setting key %r to %r"
msgstr "Schlüssel %r wird auf %r festgelegt"

#: ../pykolab/setup/setup_mta.py:350
msgid "Could not write out Postfix configuration file /etc/postfix/master.cf"
msgstr ""

#: ../pykolab/setup/setup_mta.py:413
msgid "Could not write out Amavis configuration file amavisd.conf"
msgstr ""

#: ../pykolab/setup/setup_mta.py:421
msgid "Not writing out any configuration for Amavis."
msgstr ""

#: ../pykolab/setup/setup_mta.py:459
msgid "Configuring and refreshing Anti-Virus..."
msgstr ""

#: ../pykolab/setup/setup_mta.py:472
msgid "Could not find a ClamAV update configuration file"
msgstr ""

#: ../pykolab/setup/setup_mta.py:515
msgid "Could not start the postfix, clamav and amavisd services services."
msgstr ""

#: ../pykolab/setup/setup_mta.py:533
msgid ""
"Could not configure to start on boot, the postfix, clamav and amavisd "
"services."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:40
msgid "MySQL Options"
msgstr ""

#: ../pykolab/setup/setup_mysql.py:46
msgid "Specify whether to use an (existing) or (new) MySQL server."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:50
msgid "Setup MySQL."
msgstr "Richte MySQL ein."

#: ../pykolab/setup/setup_mysql.py:78
msgid "Could not start the MySQL database service."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:87
msgid "Could not configure to start on boot, the MySQL database service."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:90
msgid "Waiting for at most 30 seconds for MySQL/MariaDB to settle..."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:114
msgid "What MySQL server are we setting up?"
msgstr ""

#: ../pykolab/setup/setup_mysql.py:118
msgid ""
"\n"
"                        Please supply the root password for MySQL, so we can set\n"
"                        up user accounts for other components that use MySQL.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:125 ../pykolab/setup/setup_mysql.py:142
#: ../pykolab/setup/setup_roundcube.py:218
#: ../pykolab/setup/setup_syncroton.py:66
msgid "MySQL root password"
msgstr "MySQL root Password"

#: ../pykolab/setup/setup_mysql.py:131
msgid ""
"\n"
"                        Please supply a root password for MySQL. This password\n"
"                        will be the administrative user for this MySQL server,\n"
"                        and it should be kept a secret. After this setup process\n"
"                        has completed, Kolab is going to discard and forget\n"
"                        about this password, but you will need it for\n"
"                        administrative tasks in MySQL.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:186
msgid ""
"\n"
"                        Please supply a password for the MySQL user 'kolab'.\n"
"                        This password will be used by Kolab services, such as\n"
"                        the Web Administration Panel.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:194
msgid "MySQL kolab password"
msgstr "MySQL-kolab Password"

#: ../pykolab/setup/setup_mysql.py:213
msgid "Could not find the MySQL Kolab schema file"
msgstr ""

#: ../pykolab/setup/setup_php.py:42
msgid "PHP Options"
msgstr "PHP Optionen"

#: ../pykolab/setup/setup_php.py:49
msgid "Specify the timezone for PHP."
msgstr "Zeitzone für PHP definieren."

#: ../pykolab/setup/setup_php.py:57
msgid "Specify the path to the php.ini file used with the webserver."
msgstr ""

#: ../pykolab/setup/setup_php.py:61
msgid "Setup PHP."
msgstr "Richte PHP ein."

#: ../pykolab/setup/setup_php.py:66
msgid ""
"\n"
"                        Please supply the timezone PHP should be using.\n"
"                        You have to use a Continent or Country / City locality name\n"
"                        like 'Europe/Berlin', but not just 'CEST'.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_php.py:74
msgid "Timezone ID"
msgstr "Zeitzonen ID"

#: ../pykolab/setup/setup_php.py:80
#, python-format
msgid "Cannot configure PHP through %r (No such file or directory)"
msgstr ""

#: ../pykolab/setup/setup_php.py:91
msgid "Could not find PHP configuration file php.ini"
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:45
msgid "Setup Roundcube."
msgstr "Stelle Roundcube ein."

#: ../pykolab/setup/setup_roundcube.py:49
msgid ""
"\n"
"                    Please supply a password for the MySQL user 'roundcube'.\n"
"                    This password will be used by the Roundcube webmail\n"
"                    interface.\n"
"                "
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:57
msgid "MySQL roundcube password"
msgstr "MySQL roundcube Passwort"

#: ../pykolab/setup/setup_roundcube.py:144
#, python-format
msgid "Using template file %r"
msgstr "Vorlagendatei %r wird verwendet"

#: ../pykolab/setup/setup_roundcube.py:151
#, python-format
msgid "Successfully compiled template %r, writing out to %r"
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:263
msgid "Cannot find the configuration directory for roundcube."
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:305
#: ../pykolab/setup/setup_syncroton.py:104
msgid "Could not start the webserver server service."
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:314
#: ../pykolab/setup/setup_syncroton.py:113
msgid "Could not configure to start on boot, the webserver server service."
msgstr ""

#: ../pykolab/setup/setup_syncroton.py:40
msgid "Setup Syncroton."
msgstr "Richte Syncroton ein."

#. start_max = (int)(time.time())
#: ../pykolab/telemetry.py:588
#, python-format
msgid "Expiring sessions that started before or on %d"
msgstr ""

#: ../pykolab/telemetry.py:601
#, python-format
msgid "Expiring session ID: %d"
msgstr ""

#: ../pykolab/telemetry.py:620
#, python-format
msgid "Session with ID %d expired from database"
msgstr ""

#: ../pykolab/telemetry.py:646
#, python-format
msgid "Operational Error in telemetry database: %s"
msgstr ""

#: ../pykolab/telemetry.py:652
msgid "No database available"
msgstr "Keine Datenbank verfügbar"

#: ../pykolab/utils.py:69 ../pykolab/utils.py:71
#, python-format
msgid "Confirm %s: "
msgstr "Bestätige %s:"

#: ../pykolab/utils.py:74
msgid "Incorrect confirmation. Please try again."
msgstr ""

#: ../pykolab/utils.py:79 ../pykolab/utils.py:84
#, python-format
msgid "%s: "
msgstr "%s:"

#: ../pykolab/utils.py:81 ../pykolab/utils.py:86
#, python-format
msgid "%s [%s]: "
msgstr "%s [%s]: "

#: ../pykolab/utils.py:139
msgid "Please answer 'yes' or 'no'."
msgstr "Bitte antworten Sie mit 'yes' (ja) oder 'no' (nein)."

#: ../pykolab/utils.py:184
msgid "Choice"
msgstr ""

#: ../pykolab/utils.py:187
msgid "Choice (type '?' for options)"
msgstr ""

#: ../pykolab/utils.py:288
#, python-format
msgid "Could not change the permissions on %s"
msgstr ""

#: ../pykolab/utils.py:526
#, python-format
msgid "Transliterating string %r with locale %r"
msgstr ""

#: ../pykolab/utils.py:534
msgid "Attempting to set locale"
msgstr ""

#: ../pykolab/utils.py:536
msgid "Success setting locale"
msgstr ""

#: ../pykolab/utils.py:538
msgid "Failure to set locale"
msgstr ""

#: ../pykolab/utils.py:546
#, python-format
msgid "Executing '%s | %s'"
msgstr ""

#: ../pykolab/utils.py:557
#, python-format
msgid "Could not translate %s using locale %s"
msgstr ""

#: ../pykolab/wap_client/__init__.py:416
#, python-format
msgid "Requesting %r with params %r"
msgstr ""

#: ../pykolab/wap_client/__init__.py:424
#, python-format
msgid "Got response: %r"
msgstr ""

#: ../pykolab/wap_client/__init__.py:429
#, python-format
msgid "Connection error: %r; re-connecting..."
msgstr ""

#. Some data is not JSON
#: ../pykolab/wap_client/__init__.py:441
msgid "Response data is not JSON"
msgstr ""

#. support integer values, too
#: ../pykolab/xml/attendee.py:9 ../pykolab/xml/attendee.py:18
msgid "Needs Action"
msgstr ""

#: ../pykolab/xml/attendee.py:10 ../pykolab/xml/attendee.py:19
msgid "Accepted"
msgstr "Akzeptiert"

#: ../pykolab/xml/attendee.py:11 ../pykolab/xml/attendee.py:20
msgid "Declined"
msgstr "Abgelehnt"

#: ../pykolab/xml/attendee.py:12 ../pykolab/xml/attendee.py:21
msgid "Tentatively Accepted"
msgstr "Provisorisch Akzeptiert"

#: ../pykolab/xml/attendee.py:13 ../pykolab/xml/attendee.py:22
msgid "Delegated"
msgstr "Delegiert"

#: ../pykolab/xml/attendee.py:14 ../pykolab/xml/attendee.py:23
msgid "Started"
msgstr "Gestarted"

#: ../pykolab/xml/attendee.py:15 ../pykolab/xml/attendee.py:24
msgid "Completed"
msgstr "Erledigt"

#: ../pykolab/xml/attendee.py:16
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:914
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:926
msgid "Pending"
msgstr "Ausstehend"

#: ../pykolab/xml/attendee.py:133 ../pykolab/xml/attendee.py:155
msgid "Not a valid attendee"
msgstr ""

#: ../pykolab/xml/attendee.py:140
msgid "No valid delegator references found"
msgstr ""

#: ../pykolab/xml/attendee.py:160
msgid "No valid delegatee references found"
msgstr ""

#: ../pykolab/xml/attendee.py:220
#, python-format
msgid "Invalid cutype %r"
msgstr ""

#: ../pykolab/xml/attendee.py:232
#, python-format
msgid "Invalid participant status %r"
msgstr ""

#: ../pykolab/xml/attendee.py:240
#, python-format
msgid "Invalid role %r"
msgstr "Ungültige Rolle %r"

#: ../pykolab/xml/event.py:168
#, python-format
msgid "Rdate needs datetime.date or datetime.datetime instance, got %r"
msgstr ""

#: ../pykolab/xml/event.py:185
#, python-format
msgid "Exdate needs datetime.date or datetime.datetime instance, got %r"
msgstr ""

#: ../pykolab/xml/event.py:403
#, python-format
msgid "No attendee with email or name %r"
msgstr ""

#: ../pykolab/xml/event.py:411
#, python-format
msgid "Invalid argument value attendee %r, must be basestring or Attendee"
msgstr ""

#: ../pykolab/xml/event.py:423
#, python-format
msgid "No attendee with email %r"
msgstr ""

#: ../pykolab/xml/event.py:429
#, python-format
msgid "No attendee with name %r"
msgstr ""

#: ../pykolab/xml/event.py:479 ../pykolab/xml/utils.py:180
msgid "%Y-%m-%d"
msgstr "%Y-%m-%d"

#: ../pykolab/xml/event.py:481 ../pykolab/xml/utils.py:181
msgid "%H:%M (%Z)"
msgstr "%H:%M (%Z)"

#: ../pykolab/xml/event.py:614
msgid "Invalid participant status"
msgstr ""

#: ../pykolab/xml/event.py:820 ../pykolab/xml/note.py:94
#, python-format
msgid "Invalid classification %r"
msgstr ""

#: ../pykolab/xml/event.py:851
#, python-format
msgid "Event end needs datetime.date or datetime.datetime instance, got %r"
msgstr ""

#: ../pykolab/xml/event.py:865
#, python-format
msgid "Invalid custom property name %r"
msgstr ""

#: ../pykolab/xml/event.py:1017
#, python-format
msgid ""
"Event last-modified needs datetime.date or datetime.datetime instance, got "
"%r"
msgstr ""

#: ../pykolab/xml/event.py:1060
#, python-format
msgid "Event start needs datetime.date or datetime.datetime instance, got %r"
msgstr ""

#: ../pykolab/xml/event.py:1070
#, python-format
msgid "Invalid status set: %r"
msgstr "Ungültiger Status festgelegt: %r"

#: ../pykolab/xml/event.py:1093
msgid "Event recurrence-id needs datetime.datetime instance"
msgstr ""

#: ../pykolab/xml/event.py:1330
msgid "No sender specified"
msgstr "Kein Absender angegeben"

#: ../pykolab/xml/event.py:1339
#, python-format
msgid "Invitation for %s was %s"
msgstr "Einladung für %s war %s"

#: ../pykolab/xml/event.py:1344
msgid "This is an automated response to one of your event requests."
msgstr ""

#: ../pykolab/xml/recurrence_rule.py:41
#, python-format
msgid "Every %d year(s)"
msgstr "Alle %d Jahr(e)"

#: ../pykolab/xml/recurrence_rule.py:42
#, python-format
msgid "Every %d month(s)"
msgstr "Alle %d Monat(e)"

#: ../pykolab/xml/recurrence_rule.py:43
#, python-format
msgid "Every %d week(s)"
msgstr "Alle %d Woche(n)"

#: ../pykolab/xml/recurrence_rule.py:44
#, python-format
msgid "Every %d day(s)"
msgstr "Alle %d Tag(e)"

#: ../pykolab/xml/recurrence_rule.py:45
#, python-format
msgid "Every %d hours"
msgstr "Alle %d Stunden"

#: ../pykolab/xml/recurrence_rule.py:46
#, python-format
msgid "Every %d minutes"
msgstr "Alle %d Minuten"

#: ../pykolab/xml/recurrence_rule.py:47
#, python-format
msgid "Every %d seconds"
msgstr "Alle %d Sekunden"

#: ../pykolab/xml/todo.py:165
msgid "Todo due needs datetime.date or datetime.datetime instance"
msgstr ""

#: ../pykolab/xml/utils.py:149
msgid "Name"
msgstr "Name"

#: ../pykolab/xml/utils.py:150
msgid "Summary"
msgstr "Zusammenfassung"

#: ../pykolab/xml/utils.py:151
msgid "Location"
msgstr "Ort"

#: ../pykolab/xml/utils.py:152
msgid "Description"
msgstr "Beschreibung"

#: ../pykolab/xml/utils.py:153
msgid "URL"
msgstr "URL"

#: ../pykolab/xml/utils.py:154
msgid "Status"
msgstr "Status"

#: ../pykolab/xml/utils.py:155
msgid "Priority"
msgstr "Priorität"

#: ../pykolab/xml/utils.py:156
msgid "Attendee"
msgstr "Teilnehmer"

#: ../pykolab/xml/utils.py:157
msgid "Start"
msgstr "Beginn"

#: ../pykolab/xml/utils.py:158
msgid "End"
msgstr "Ende"

#: ../pykolab/xml/utils.py:159
msgid "Due"
msgstr "Fällig"

#: ../pykolab/xml/utils.py:160
msgid "Repeat"
msgstr "Wiederholung"

#: ../pykolab/xml/utils.py:161
msgid "Repeat Exception"
msgstr ""

#: ../pykolab/xml/utils.py:162
msgid "Organizer"
msgstr "Organisator"

#: ../pykolab/xml/utils.py:163
msgid "Attachment"
msgstr "Anhang"

#: ../pykolab/xml/utils.py:164
msgid "Alarm"
msgstr "Alarm"

#: ../pykolab/xml/utils.py:165
msgid "Classification"
msgstr "Einstufung"

#: ../pykolab/xml/utils.py:166
msgid "Progress"
msgstr "Fortschritt"

#: ../pykolab/xml/utils.py:211
#, python-format
msgid "for %d times"
msgstr ""

#: ../pykolab/xml/utils.py:213
#, python-format
msgid "until %s"
msgstr "bis %s"

#: ../pykolab/xml/utils.py:218
msgid "Display message"
msgstr "Nachricht anzeigen"

#: ../pykolab/xml/utils.py:219
msgid "Send email"
msgstr "E-Mail senden"

#: ../pykolab/xml/utils.py:220
msgid "Play sound"
msgstr "Audio abspielen"

#: ../pykolab/xml/utils.py:226
#, python-format
msgid "%s after"
msgstr "%s danach"

#: ../pykolab/xml/utils.py:226
#, python-format
msgid "%s before"
msgstr "%s davor"

#: ../pykolab/xml/utils.py:235
#, python-format
msgid "%d day(s)"
msgstr "%d Tag(e)"

#: ../pykolab/xml/utils.py:241
#, python-format
msgid "%d hour(s)"
msgstr "%d Stunde(n)"

#: ../pykolab/xml/utils.py:243
#, python-format
msgid "%d minute(s)"
msgstr "%d Minute(n)"

#: ../saslauthd/__init__.py:77
msgid "Socket file to bind to."
msgstr ""

#: ../saslauthd/__init__.py:109
#, python-format
msgid "Could not create %r: %r"
msgstr ""

#: ../saslauthd/__init__.py:220
#, python-format
msgid "kolab-saslauthd could not accept connections on socket: %r"
msgstr ""

#: ../saslauthd/__init__.py:225
msgid "Maximum tries exceeded, exiting"
msgstr ""

#: ../tests/functional/test_wallace/test_005_resource_invitation.py:196
#: ../wallace/module_resources.py:1268
#, python-format
msgid "Reservation Request for %(summary)s was %(status)s"
msgstr ""

#. check notification message sent to resource owner (jane)
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:641
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:657
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:715
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:771
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:785
#: ../wallace/module_resources.py:1352
#, python-format
msgid "Booking for %s has been %s"
msgstr "Buchung für %s wurde %s"

#. check confirmation message sent to resource owner (jane)
#. check first confirmation message sent to resource owner (jane)
#. check second confirmation message sent to resource owner (jane)
#. check confirmation message sent to resource owner (jane)
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:677
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:704
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:742
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:759
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:814
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:968
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:984
#: ../wallace/module_resources.py:1450
#, python-format
msgid "Booking request for %s requires confirmation"
msgstr "Buchungsanfrage für %s benötigt eine Bestätigung"

#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:242
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:1267
#: ../wallace/module_invitationpolicy.py:479
#, python-format
msgid "\"%(summary)s\" has been %(status)s"
msgstr "\"%(summary)s\" wurde %(status)s"

#. this should trigger a notification message
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:886
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:1251
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:1396
#: ../wallace/module_invitationpolicy.py:1316
#, python-format
msgid "\"%s\" has been cancelled"
msgstr "\"%s\" wurde abgesagt"

#. check for notification message
#. this notification should be suppressed until mark has replied, too
#. this triggers an additional notification
#. this should also trigger an update notification
#. this should trigger an update notification
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:903
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:909
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:922
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:939
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:1039
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:1044
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:1377
#: ../wallace/module_invitationpolicy.py:1234
#, python-format
msgid "\"%s\" has been updated"
msgstr "\"%s\" wurde aktualisiert"

#: ../tests/unit/test-011-itip.py:534
#, python-format
msgid "Invitation for %(summary)s was %(status)s"
msgstr "Einladung für %(summary)s war %(status)s"

#: ../wallace/__init__.py:51
#, python-format
msgid "Wallace modules: %r"
msgstr "Wallace-Module: %r"

#: ../wallace/__init__.py:67
#, python-format
msgid "Module %s.execute() failed on message %r with error: %s"
msgstr ""

#: ../wallace/__init__.py:91
#, python-format
msgid "Module %s.heartbeat() failed with error: %s"
msgstr ""

#: ../wallace/__init__.py:100
#, python-format
msgid "Worker process %s initializing"
msgstr ""

#: ../wallace/__init__.py:123
msgid "Bind address for Wallace."
msgstr "Bind-Adresse für Wallace."

#: ../wallace/__init__.py:142
msgid "Number of threads to use."
msgstr ""

#: ../wallace/__init__.py:159
msgid "Port that Wallace is supposed to use."
msgstr "Port, den Wallace benutzen soll."

#: ../wallace/__init__.py:208
#, python-format
msgid "Could not bind to socket on port %d on bind address %s"
msgstr ""

#: ../wallace/__init__.py:220
msgid "Could not shut down socket"
msgstr "Konnte Socket nicht schließen"

#: ../wallace/__init__.py:289
msgid "Accepted connection"
msgstr "Verbindung akzeptiert"

#: ../wallace/__init__.py:494
#, python-format
msgid "Could not write pid file %s"
msgstr ""

#: ../wallace/module_footer.py:63 ../wallace/module_gpgencrypt.py:100
#: ../wallace/module_invitationpolicy.py:227 ../wallace/module_optout.py:61
#: ../wallace/module_resources.py:129
#, python-format
msgid "Issuing callback after processing to stage %s"
msgstr ""

#: ../wallace/module_footer.py:64 ../wallace/module_gpgencrypt.py:101
#: ../wallace/module_invitationpolicy.py:229 ../wallace/module_optout.py:62
#: ../wallace/module_resources.py:135
#, python-format
msgid "Testing cb_action_%s()"
msgstr ""

#: ../wallace/module_footer.py:66 ../wallace/module_gpgencrypt.py:103
#: ../wallace/module_invitationpolicy.py:231 ../wallace/module_optout.py:64
#: ../wallace/module_resources.py:138
#, python-format
msgid "Attempting to execute cb_action_%s()"
msgstr ""

#: ../wallace/module_footer.py:70
#, python-format
msgid "Executing module footer for %r, %r"
msgstr ""

#: ../wallace/module_footer.py:88
msgid "No contents configured for footer module"
msgstr ""

#: ../wallace/module_gpgencrypt.py:106
#, python-format
msgid "Executing module gpgencrypt for %r, %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:138
msgid "Message is already encrypted (app/pgp-enc content-type)"
msgstr ""

#: ../wallace/module_gpgencrypt.py:142
msgid "Message already encrypted by main content-type header"
msgstr ""

#: ../wallace/module_gpgencrypt.py:171
msgid ""
"Configured to encrypt to a key not configured, and strict policy enabled. "
"Bailing out."
msgstr ""

#: ../wallace/module_gpgencrypt.py:174
msgid ""
"Configured to encrypt to a key not configured, but continuing anyway (see "
"'gpgencrypt_strict')."
msgstr ""

#: ../wallace/module_gpgencrypt.py:211
#, python-format
msgid "Recipients: %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:222
#, python-format
msgid "Current keys: %r"
msgstr "Aktuelle Schlüssel: %r"

#: ../wallace/module_gpgencrypt.py:227
#, python-format
msgid "Retrieving key for recipient: %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:231 ../wallace/module_gpgencrypt.py:247
#, python-format
msgid "Found matching address %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:239
#, python-format
msgid "Found matching address %r in remote keys"
msgstr ""

#: ../wallace/module_gpgencrypt.py:259
msgid "Mime Message - we need to build multipart/encrypted structure"
msgstr ""

#: ../wallace/module_gpgencrypt.py:268
msgid "No Mime Message - encypt plain"
msgstr ""

#: ../wallace/module_gpgencrypt.py:284
#, python-format
msgid "An error occurred: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:213
#, python-format
msgid "Invitation policy called for %r, %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:275
#, python-format
msgid "Failed to parse iTip objects from message: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:279
msgid ""
"Message is not an iTip message or does not contain any (valid) iTip objects."
msgstr ""

#: ../wallace/module_invitationpolicy.py:283
#, python-format
msgid ""
"iTip objects attached to this message contain the following information: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:306
#, python-format
msgid "Recipient emails for %s: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:310
#, python-format
msgid "No itips, no users, pass along %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:313
#, python-format
msgid "iTips, but no users, pass along %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:331
#, python-format
msgid "No user attendee matching envelope recipient %s, skip message"
msgstr ""

#: ../wallace/module_invitationpolicy.py:334
#, python-format
msgid "Receiving user: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:362
#, python-format
msgid "Apply invitation policy %r for sender %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:373
#, python-format
msgid "Ignoring '%s' iTip method"
msgstr ""

#: ../wallace/module_invitationpolicy.py:377
#, python-format
msgid "iTip message %r consumed by the invitationpolicy module"
msgstr ""

#: ../wallace/module_invitationpolicy.py:393
msgid "Pass invitation for manual processing"
msgstr ""

#: ../wallace/module_invitationpolicy.py:398
#, python-format
msgid "Receiving Attendee: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:418
#, python-format
msgid "Existing %s: %r"
msgstr "Vorhanden %s: %r"

#: ../wallace/module_invitationpolicy.py:429
#, python-format
msgid "Precondition for object %r fulfilled: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:449
#, python-format
msgid ""
"The iTip request sequence (%r) doesn't match the referred object version "
"(%r). Ignoring."
msgstr ""

#: ../wallace/module_invitationpolicy.py:454
#, python-format
msgid "Auto-updating %s %r on iTip REQUEST (no re-scheduling)"
msgstr ""

#: ../wallace/module_invitationpolicy.py:505
msgid "Forward invitation for notification"
msgstr ""

#: ../wallace/module_invitationpolicy.py:520
msgid "Pass reply for manual processing"
msgstr ""

#: ../wallace/module_invitationpolicy.py:527
#, python-format
msgid "Sender Attendee: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:539
#, python-format
msgid ""
"The iTip reply sequence (%r) doesn't match the referred object version (%r)."
" Forwarding to Inbox."
msgstr ""

#: ../wallace/module_invitationpolicy.py:545
#, python-format
msgid "Auto-updating %s %r on iTip REPLY"
msgstr ""

#: ../wallace/module_invitationpolicy.py:572
#, python-format
msgid "Add delegatee: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:575
#, python-format
msgid "Update existing delegatee: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:582
#, python-format
msgid "Update delegator: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:600
msgid ""
"The object referred by this reply was not found in the user's folders. "
"Forwarding to Inbox."
msgstr ""

#: ../wallace/module_invitationpolicy.py:613
msgid "Pass cancellation for manual processing"
msgstr ""

#: ../wallace/module_invitationpolicy.py:636
#, python-format
msgid "Remove cancelled %s instance %s from %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:647
#, python-format
msgid "Update cancelled %s %r with STATUS=CANCELLED"
msgstr ""

#: ../wallace/module_invitationpolicy.py:662
msgid ""
"The object referred by this cancel request was not found in the user's "
"folders. Forwarding to Inbox."
msgstr ""

#: ../wallace/module_invitationpolicy.py:691
#, python-format
msgid "Checking if email address %r belongs to a local user"
msgstr ""

#: ../wallace/module_invitationpolicy.py:696
#, python-format
msgid "User DN: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:698
#, python-format
msgid "No user record(s) found for %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:754
#, python-format
msgid "User record doesn't have the mailbox attribute %r set"
msgstr ""

#: ../wallace/module_invitationpolicy.py:767
#, python-format
msgid "IMAP proxy authentication failed: %r"
msgstr "IMAP-Proxy Authentifizierung fehlgeschlagen: %r"

#: ../wallace/module_invitationpolicy.py:789
#, python-format
msgid "List %r folders for user %r: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:804
#, python-format
msgid "IMAP metadata for %r: %r"
msgstr "IMAP-Metadaten für %r: %r"

#: ../wallace/module_invitationpolicy.py:842
#, python-format
msgid "Searching folder %r for %s %r"
msgstr "Ordnersuche %r nach %s %r"

#: ../wallace/module_invitationpolicy.py:852
#: ../wallace/module_resources.py:691 ../wallace/module_resources.py:752
#, python-format
msgid "No UID found in IMAP response: %r"
msgstr "Keine UID in der IMAP Antwort gefunden: %r"

#: ../wallace/module_invitationpolicy.py:878
#, python-format
msgid "Failed to parse %s from message %s/%s: %s"
msgstr "Fehler beim Auslesen von %s aus Nachricht  %s/%s: %s"

#: ../wallace/module_invitationpolicy.py:906
#, python-format
msgid "Listing events from folder %r"
msgstr "Auflisten der Ereignisse aus Ordner \"%r\""

#: ../wallace/module_invitationpolicy.py:919
#: ../wallace/module_resources.py:498 ../wallace/module_resources.py:699
#: ../wallace/module_resources.py:779
#, python-format
msgid "Failed to parse event from message %s/%s: %r"
msgstr "Fehler beim Auslesen des Ereignisses aus Nachricht %s/%s: %r"

#: ../wallace/module_invitationpolicy.py:925
#, python-format
msgid "Existing event %r conflicts with invitation %r"
msgstr "Das bestehende Ereignis \"%r\" kollidiert mit der Einladung \"%r\""

#: ../wallace/module_invitationpolicy.py:932
#: ../wallace/module_resources.py:542
#, python-format
msgid "start: %r, end: %r, total: %r, messages: %d"
msgstr "Start: %r, Ende: %r, Gesamt: %r, Nachrichten: %d"

#: ../wallace/module_invitationpolicy.py:960
#, python-format
msgid "%r is locked, waiting..."
msgstr "%r ist gesperrt, warte..."

#: ../wallace/module_invitationpolicy.py:1040
#, python-format
msgid "Failed to save %s: no target folder found for user %r"
msgstr "Fehler beim Speichern von \"%s\" Zielordner für Benutzer %r nicht vorhanden."

#: ../wallace/module_invitationpolicy.py:1051
#, python-format
msgid "Save %s %r to user folder %r"
msgstr "%s %r in Benutzerordner %r speichern"

#: ../wallace/module_invitationpolicy.py:1064
#, python-format
msgid "Failed to save %s to user folder at %r: %r"
msgstr "Fehler beim Speichern von \"%s\" im Ordner %r: %r"

#: ../wallace/module_invitationpolicy.py:1083
#, python-format
msgid "Delete %s %r in %r by UID: %r"
msgstr "%s %r in %r von Benutzerkennung: %r löschen"

#: ../wallace/module_invitationpolicy.py:1091
#, python-format
msgid "Delete %s %r in %r: %r"
msgstr "%s %r in %r: %r löschen"

#: ../wallace/module_invitationpolicy.py:1102
#, python-format
msgid "Failed to delete %s from folder %r: %r"
msgstr "Fehler beim Löschen von \"%s\" aus dem Ordner %r: %r"

#: ../wallace/module_invitationpolicy.py:1130
#: ../wallace/module_invitationpolicy.py:1304
#, python-format
msgid "%s commented: %s"
msgstr "%s kommentiert: %s"

#: ../wallace/module_invitationpolicy.py:1133
#, python-format
msgid "Compose participation status summary for %s %r to user %r"
msgstr "Erzeuge Teilnahmestatusübersicht für \"%s\" %r an Benutzer %r"

#: ../wallace/module_invitationpolicy.py:1171
#, python-format
msgid ""
"Waiting for more automated replies (got %d of %d); skipping notification"
msgstr "Warte auf weitere automatische Antworten (bereits erhalten %d von %d); überspringe Benachrichtigung"

#: ../wallace/module_invitationpolicy.py:1192
#, python-format
msgid "Changes submitted by %s have been automatically applied."
msgstr "Die von %s durchgeführten Änderungen wurden automatischen angewendet."

#: ../wallace/module_invitationpolicy.py:1201
msgid "(removed)"
msgstr "(entfernt)"

#: ../wallace/module_invitationpolicy.py:1207
#, python-format
msgid ""
"\n"
"            The assignment for '%(summary)s' has been updated in your tasklist.\n"
"            %(roundup)s\n"
"        "
msgstr "\nDie Zuweisung für '%(summary)s' wurde in ihrer Aufgabenliste aktualisiert.\n%(roundup)s\n        "

#: ../wallace/module_invitationpolicy.py:1215
#, python-format
msgid ""
"\n"
"            The event '%(summary)s' at %(start)s has been updated in your calendar.\n"
"            %(roundup)s\n"
"        "
msgstr "\nDas Ereignis '%(summary)s' um %(start)s wurde in ihrem Kalender aktualisiert.\n%(roundup)s\n        "

#: ../wallace/module_invitationpolicy.py:1225
msgid "NOTE: This update only refers to this single occurrence!"
msgstr "BEACHTE: Die Änderung bezieht sich nur auf diesen einzelnen Eintrag."

#: ../wallace/module_invitationpolicy.py:1227
#: ../wallace/module_invitationpolicy.py:1309
#: ../wallace/module_invitationpolicy.py:1411
msgid "*** This is an automated message. Please do not reply. ***"
msgstr "*** Dies ist eine automatisierte Nachricht. Bitte antworten Sie nicht. ***"

#: ../wallace/module_invitationpolicy.py:1249
#, python-format
msgid "Sent update notification to %r: %r"
msgstr "Aktualisierungsbenachrichtigung an %r: %r gesendet"

#: ../wallace/module_invitationpolicy.py:1274
#, python-format
msgid "Send cancellation notification for %s %r to user %r"
msgstr "Benachrichtigung über die Absage von %s %r an Nutzer %r senden"

#: ../wallace/module_invitationpolicy.py:1284
#, python-format
msgid "The assignment for '%(summary)s' has been cancelled by %(organizer)s."
msgstr "Die Zuweisung für '%(summary)s' wurde von %(organizer)s zurückgezogen."

#: ../wallace/module_invitationpolicy.py:1289
msgid "The copy in your tasklist has been removed accordingly."
msgstr "Der Eintrag wurde entsprechend aus Ihrer Aufgabenliste entfernt."

#: ../wallace/module_invitationpolicy.py:1291
msgid "The copy in your tasklist has been marked as cancelled accordingly."
msgstr "Daher wurde die Aufgabe aus Iher Aufgabenliste storniert."

#: ../wallace/module_invitationpolicy.py:1293
#, python-format
msgid ""
"The event '%(summary)s' at %(start)s has been cancelled by %(organizer)s."
msgstr "Der Termin '%(summary)s' am/um %(start)s wurde von %(organizer)s abgesagt."

#: ../wallace/module_invitationpolicy.py:1299
msgid "The copy in your calendar has been removed accordingly."
msgstr "Der Eintrag wurde entsprechend aus Ihrem Kalender entfernt."

#: ../wallace/module_invitationpolicy.py:1301
msgid "The copy in your calendar has been marked as cancelled accordingly."
msgstr "Der Eintrag in Ihrem Kalender wurde als abgesagt gekennzeichnet."

#: ../wallace/module_invitationpolicy.py:1307
msgid "NOTE: This cancellation only refers to this single occurrence!"
msgstr "BEACHTE: Die Absage bezieht sich nur auf diesen einzelnen Eintrag."

#: ../wallace/module_invitationpolicy.py:1401
#, python-format
msgid "Updated %s's copy of %r: %r"
msgstr "%s's Kopie von %r wurde aktualisiert: %r"

#: ../wallace/module_invitationpolicy.py:1404
#, python-format
msgid "Attendee %s's copy of %r not found"
msgstr "Die Kopie des Teilnehmers %s von %r wurde nicht gefunden"

#: ../wallace/module_invitationpolicy.py:1407
#, python-format
msgid "Attendee %r not found in LDAP"
msgstr "Teilnehmer %r wurde nicht in LDAP gefunden"

#: ../wallace/module_invitationpolicy.py:1414
#, python-format
msgid "%(name)s has %(status)s your assignment for %(summary)s."
msgstr "%(name)s hat die Zuweisung für \"%(summary)s\" %(status)s."

#: ../wallace/module_invitationpolicy.py:1416
#, python-format
msgid "%(name)s has %(status)s your invitation for %(summary)s."
msgstr "%(name)s hat ihre Einladung für den Termin \"%(summary)s\" %(status)s."

#. modules.next_module('optout')
#: ../wallace/module_optout.py:70
#, python-format
msgid "Consulting opt-out service for %r, %r"
msgstr ""

#: ../wallace/module_optout.py:96
#, python-format
msgid ""
"Running opt-out consult from envelope sender '%s <%s>' to recipient %s <%s>"
msgstr ""

#: ../wallace/module_optout.py:160
#, python-format
msgid "Attempting to execute cb_action_%s(%r, %r)"
msgstr ""

#: ../wallace/module_optout.py:181
#, python-format
msgid "Could not send request to optout_url %s"
msgstr ""

#: ../wallace/module_resources.py:119
#, python-format
msgid "Resource Management called for %r, %r"
msgstr ""

#: ../wallace/module_resources.py:184
#, python-format
msgid "Failed to parse iTip events from message: %r"
msgstr ""

#: ../wallace/module_resources.py:189
msgid "Message is not an iTip message or does not contain any (valid) iTip."
msgstr ""

#: ../wallace/module_resources.py:197
#, python-format
msgid ""
"iTip events attached to this message contain the following information: %r"
msgstr ""

#: ../wallace/module_resources.py:228
msgid "Not an iTip message, but sent to resource nonetheless. Reject message"
msgstr ""

#: ../wallace/module_resources.py:236
#, python-format
msgid "No itips, no resources, pass along %r"
msgstr ""

#: ../wallace/module_resources.py:239
#, python-format
msgid "iTips, but no resources, pass along %r"
msgstr ""

#: ../wallace/module_resources.py:248
#, python-format
msgid "No resource attendees matching envelope recipient %s, Reject message"
msgstr ""

#: ../wallace/module_resources.py:258
#, python-format
msgid "Resources: %r; %r"
msgstr "Ressourcen: %r; %r"

#: ../wallace/module_resources.py:272
#, python-format
msgid "iTip REPLY to %r, %r; matches %r"
msgstr ""

#: ../wallace/module_resources.py:278
#, python-format
msgid "Sender Attendee: %r => %r"
msgstr ""

#: ../wallace/module_resources.py:280
#, python-format
msgid "Could not find envelope sender attendee: %r"
msgstr ""

#: ../wallace/module_resources.py:285
#, python-format
msgid ""
"The iTip reply sequence (%r) doesn't match the referred event version (%r). "
"Ignoring."
msgstr ""

#: ../wallace/module_resources.py:304
#, python-format
msgid "Invalid response (%r) received from resource owner for event %r"
msgstr ""

#: ../wallace/module_resources.py:308
#, python-format
msgid "Event referenced by this REPLY (%r) not found in resource calendar"
msgstr ""

#: ../wallace/module_resources.py:311
msgid "No event reference found in this REPLY. Ignoring."
msgstr ""

#: ../wallace/module_resources.py:320
#, python-format
msgid "Receiving Resource: %r; %r"
msgstr "Empfange Ressource: %r; %r"

#: ../wallace/module_resources.py:322
#, python-format
msgid "Could not find envelope attendee: %r"
msgstr "Kann Umschlag-Teilnehmer nicht finden: %r"

#: ../wallace/module_resources.py:328
#, python-format
msgid "Recipient %r is non-participant, ignoring message"
msgstr "Empfänger %r ist kein Teilnehmer, ignoriere Nachricht"

#: ../wallace/module_resources.py:338
#, python-format
msgid "Cancellation for entire event %r: deleting"
msgstr "Absage für gesamtes Ereignis %r: lösche"

#: ../wallace/module_resources.py:342
#, python-format
msgid "Cancellation for a single occurrence %r of %r: updating..."
msgstr "Absage für einzelne Wiederholung %r von %r: aktualisiere..."

#: ../wallace/module_resources.py:392
#, python-format
msgid "Delegate invitation for resource collection %r to %r"
msgstr "Delegiere Einladung für Ressourcen-Gruppe %r zu %r"

#: ../wallace/module_resources.py:398 ../wallace/module_resources.py:802
#, python-format
msgid "Apply invitation policies %r"
msgstr "Anwenden der Einladungsrichtlinie %r"

#: ../wallace/module_resources.py:407
#, python-format
msgid "Accept invitation for individual resource %r / %r"
msgstr "Akzeptiere Einladung für individuelle Ressource %r / %r"

#. this is the receiving resource record
#: ../wallace/module_resources.py:411
#, python-format
msgid "Decline invitation for individual resource %r / %r"
msgstr ""

#: ../wallace/module_resources.py:427
#, python-format
msgid "module_resources.heartbeat(%d)"
msgstr "module_resources.heartbeat(%d)"

#: ../wallace/module_resources.py:450
#, python-format
msgid "Expunge resource calendar for %s (%s) failed: %r"
msgstr "Entfernen Ressourcen-Kalender für %s (%s) fehlgeschlagen: %r"

#: ../wallace/module_resources.py:474
#, python-format
msgid "Expunge events in resource folder %r older than %d days"
msgstr "Entferne Ereignisse in Ressourcen-Verzeichnis %r älter als %d Tage"

#: ../wallace/module_resources.py:487
#, python-format
msgid "Fetching message ID %r from folder %r"
msgstr "Lade Nachrichten-ID %r aus Verzeichnis %r"

#: ../wallace/module_resources.py:513
#, python-format
msgid "Flag event %s from message %s/%s as deleted (age = %d days)"
msgstr "Kennzeiche Ereigniss %s aus Nachricht %s/%s als gelöscht (Alter = %d Tage)"

#: ../wallace/module_resources.py:538
#, python-format
msgid "Failed to read resource calendar for %r: %r"
msgstr "Lesen des Ressourcen-Kalender for %r fehlgeschlagen: %r"

#: ../wallace/module_resources.py:548
#, python-format
msgid "Polling for resource %r"
msgstr "Suchen für Ressource %r"

#: ../wallace/module_resources.py:551
#, python-format
msgid "Resource %r has been popped from the list"
msgstr "Resource %r wurde von Liste entfernt"

#: ../wallace/module_resources.py:555
msgid "Resource is a collection"
msgstr "Ressource ist eine Sammlung"

#: ../wallace/module_resources.py:566
#, python-format
msgid "Removed conflicting resources from %r: (%r) => %r"
msgstr "Kollidierende Ressourcen von %r entfernt: (%r) => %r"

#: ../wallace/module_resources.py:578
#, python-format
msgid "Conflicting events: %r for resource %r"
msgstr "Kollidierende Ereignisse:  %r für Ressource %r"

#: ../wallace/module_resources.py:601
#, python-format
msgid "Delegate to another resource collection member: %r to %r"
msgstr "Delegiere an anderes Ressource-Gruppenmitglied: %r zu %r"

#: ../wallace/module_resources.py:663
#, python-format
msgid "Checking events in resource folder %r"
msgstr "Prüfe Ereignisse in Ressourcen-Verzeichnis %r"

#: ../wallace/module_resources.py:682
#, python-format
msgid "Fetching message UID %r from folder %r"
msgstr "Lade Nachricht UID %r aus Verzeichnis %r"

#: ../wallace/module_resources.py:715
#, python-format
msgid "Event %r conflicts with event %r"
msgstr "Ereignis %r kollidiert mit Ereignis %r"

#: ../wallace/module_resources.py:737
#, python-format
msgid "Searching %r for event %r"
msgstr "Suchvorgang %r nach Ereignis %r"

#: ../wallace/module_resources.py:743
#, python-format
msgid "Failed to access resource calendar:: %r"
msgstr "Zugriff auf Ressourcenkalender fehlgeschlagen: %r"

#: ../wallace/module_resources.py:770
#, python-format
msgid "Recurrence-ID not matching on message %s, skipping: %r != %r"
msgstr "Recurrence-ID stimmt nicht mit Nachricht %s überein, überspringe: %r != %r"

#: ../wallace/module_resources.py:821
#, python-format
msgid "Adding event to %r: %r"
msgstr "Hinzufügen Termin zu %r: %r"

#: ../wallace/module_resources.py:905
#, python-format
msgid "Failed to save event to resource calendar at %r: %r"
msgstr "Speichern des Termins im Ressourcenkalender fehlgeschlagen in %r: %r"

#: ../wallace/module_resources.py:924
#, python-format
msgid "Delete resource calendar object from %r by UID %r"
msgstr "Lösche Ressourcen-Kalenderobjekt %r mittels UID %r"

#: ../wallace/module_resources.py:932
#, python-format
msgid "Delete resource calendar object %r in %r: %r"
msgstr "Lösche Kalenderobjekt der Ressource %r in %r: %r"

#: ../wallace/module_resources.py:943
#, python-format
msgid "Failed to delete calendar object %r from folder %r: %r"
msgstr "Löschen des Kalenderobjekts %r aus Verzeichnis %r fehlgeschlagen: %r"

#: ../wallace/module_resources.py:983
#, python-format
msgid "Checking if email address %r belongs to a resource (collection)"
msgstr "Prüfe ob E-Mail-Adresse %r zu einer Ressource (Sammlung) gehört"

#: ../wallace/module_resources.py:991 ../wallace/module_resources.py:1063
#: ../wallace/module_resources.py:1097
#, python-format
msgid "Resource record(s): %r"
msgstr "Ressourcen-Eintrag/Einträge: %r"

#: ../wallace/module_resources.py:993 ../wallace/module_resources.py:1065
#: ../wallace/module_resources.py:1100
#, python-format
msgid "No resource (collection) records found for %r"
msgstr "Kein Ressourcen (Sammlung) - Eintrag für %r gefunden"

#: ../wallace/module_resources.py:997 ../wallace/module_resources.py:1069
#: ../wallace/module_resources.py:1104
#, python-format
msgid "Resource record: %r"
msgstr "Ressourceneinträge: %r"

#: ../wallace/module_resources.py:1015
#, python-format
msgid "Raw itip_events: %r"
msgstr "Originale itip_events: %r"

#: ../wallace/module_resources.py:1023
#, python-format
msgid "Raw set of attendees: %r"
msgstr "Originalset der Teilnehmer: %r"

#: ../wallace/module_resources.py:1031
#, python-format
msgid "Raw set of resources: %r"
msgstr "Originalset der Ressourcen: %r"

#: ../wallace/module_resources.py:1036
#, python-format
msgid "Raw set of organizers: %r"
msgstr "Originalset der Organisatoren: %r"

#: ../wallace/module_resources.py:1056
#, python-format
msgid "Checking if attendee %r is a resource (collection)"
msgstr "Prüfe ob Teilnehmer %r eine Ressource (Sammlung) ist"

#: ../wallace/module_resources.py:1072 ../wallace/module_resources.py:1106
msgid "Resource reservation made but no resource records found"
msgstr "Ressourcenbuchung erfolgt, jedoch keine Ressourceneinträge gefunden"

#: ../wallace/module_resources.py:1091
#, python-format
msgid "Checking if resource %r is a resource (collection)"
msgstr "Prüfe ob Resource %r eine Resource (Sammlung)"

#: ../wallace/module_resources.py:1109
#, python-format
msgid "The following resources are being referred to in the iTip: %r"
msgstr "Auf die folgenden Ressourcen wurde im iTip Bezug genommen: %r"

#: ../wallace/module_resources.py:1236
#, python-format
msgid "Check collections %r for kolabinvitationpolicy attributes"
msgstr "Prüfe Gruppe %r auf kolabinvitationpolicy Attribute"

#: ../wallace/module_resources.py:1274
#, python-format
msgid ""
"\n"
"                *** This is an automated response, please do not reply! ***\n"
"\n"
"                Your reservation was delegated to \"%s\" which is available for the requested time.\n"
"            "
msgstr "\n*** Dies ist eine automatisch erstellte E-Mail. Bitte antworten Sie nicht direkt darauf. ***\n\nIhre Reservierung wurde an \"%s\" delegiert, welche(r) zum angeforderten Termin verfügbar ist.\n            "

#: ../wallace/module_resources.py:1293
#, python-format
msgid ""
"\n"
"        *** This is an automated response, please do not reply! ***\n"
"        \n"
"        We hereby inform you that your reservation was %s.\n"
"    "
msgstr "\n*** Dies ist eine automatisch erstellte E-Mail. Bitte antworten Sie nicht direkt darauf. ***\n\nHiermit informieren wir Sie, dass die Buchung %s wurde.\n    "

#: ../wallace/module_resources.py:1300
#, python-format
msgid ""
"\n"
"            If you have questions about this reservation, please contact\n"
"            %s <%s> %s\n"
"        "
msgstr "\nWenn Sie Fragen zu dieser Reservierung haben, kontaktieren Sie bitte\n%s <%s> %s\n        "

#: ../wallace/module_resources.py:1335
#, python-format
msgid "Sending booking notification for event %r to %r from %r"
msgstr "Sende Buchungsbenachrichtigung für Termin %r zu %r von %r"

#: ../wallace/module_resources.py:1353
msgid "failed"
msgstr "fehlgeschlagen"

#: ../wallace/module_resources.py:1373
#, python-format
msgid ""
"\n"
"            The resource booking for %(resource)s by %(orgname)s <%(orgemail)s> has been %(status)s for %(date)s.\n"
"\n"
"            *** This is an automated message, sent to you as the resource owner. ***\n"
"        "
msgstr "\nDie Buchungsanfrage für %(resource)s durch %(orgname)s <%(orgemail)s> ist %(status)s für %(date)s.\n\n*** Dies ist eine automatisch erstellte E-Mail. Bitte antworten Sie nicht direkt darauf. ***\n        "

#: ../wallace/module_resources.py:1379
#, python-format
msgid ""
"\n"
"            A reservation request for %(resource)s could not be processed automatically.\n"
"            Please contact %(orgname)s <%(orgemail)s> who requested this resource for %(date)s. Subject: %(summary)s.\n"
"\n"
"            *** This is an automated message, sent to you as the resource owner. ***\n"
"        "
msgstr "\nEine Buchungsanfrage für %(resource)s konnte nicht automatisch verarbeitet werden.\nBitte kontaktieren Sie %(orgname)s <%(orgemail)s>, welcher die Resource für den %(date)s angefragt hat.\nSubject: %(summary)s.\n\n*** Dies ist eine automatisch erstellte E-Mail. Bitte antworten Sie nicht direkt darauf. ***"

#: ../wallace/module_resources.py:1410
#, python-format
msgid "Clone invitation for owner confirmation: %r from %r"
msgstr "Kopiere Einladung für Eigentümer Bestätigung: %r von %r"

#: ../wallace/module_resources.py:1429
#, python-format
msgid ""
"\n"
"        A reservation request for %(resource)s requires your approval!\n"
"        Please either accept or decline this invitation without saving it to your calendar.\n"
"\n"
"        The reservation request was sent from %(orgname)s <%(orgemail)s>.\n"
"\n"
"        Subject: %(summary)s.\n"
"        Date: %(date)s\n"
"        Participants: %(attendees)s\n"
"\n"
"        *** This is an automated message, please don't reply by email. ***\n"
"    "
msgstr "\nEine Buchungsanfrage für %(resource)s benötigt Ihre Zustimmung!\nBitte akzeptieren Sie die Anfrage oder lehnen Sie diese ab ohne die Anfrage in Ihrem Kalender zu speichern.\n\nDie Buchungsanfrage wurde gesendet von %(orgname)s <%(orgemail)s>.\n\nBetreff: %(summary)s.\nTermin: %(date)s\nTeilnehmer: %(attendees)s\n\n*** Dies ist eine automatisch erstellte E-Mail. Bitte antworten Sie nicht direkt darauf. ***"

#. This is a nested module
#: ../wallace/modules.py:98
#, python-format
msgid "Module Group: %s"
msgstr "Modulgruppe: %s"

#: ../wallace/modules.py:109 ../wallace/modules.py:125
#, python-format
msgid "No such module %r in modules %r (1)."
msgstr "Kein solches Modul %r in Modulen %r  (1)."

#: ../wallace/modules.py:114
#, python-format
msgid "No such module %r in modules %r (2)."
msgstr "Kein solches Modul %r in Modulen %r (2)."

#: ../wallace/modules.py:120 ../wallace/modules.py:172
#, python-format
msgid "Unknown error occurred; %r"
msgstr "Unbekannter Fehler aufgetreten; %r"

#: ../wallace/modules.py:178
#, python-format
msgid "Holding message in queue for manual review (%s by %s)"
msgstr "Behalte Nachricht zur manuellen Prüfung in der Warteliste (%s von %s)"

#: ../wallace/modules.py:181
#, python-format
msgid "Deferring message in %s (by module %s)"
msgstr "Zurückgestellte Nachricht in %s (durch Modul %s)"

#: ../wallace/modules.py:193
#, python-format
msgid "The time when the message was sent: %r"
msgstr "Zeitpunkt des Versands: %r"

#: ../wallace/modules.py:194
#, python-format
msgid "The time now: %r"
msgstr "Die Zeit ist jetzt: %r"

#: ../wallace/modules.py:195
#, python-format
msgid "The time delta: %r"
msgstr "Die Zeitdifferenz: %r"

#. TODO: Send NDR back to user
#: ../wallace/modules.py:199
#, python-format
msgid "Message in file %s older then 5 days, deleting"
msgstr "Nachricht in Datei %s älter als 5 Tage, lösche"

#: ../wallace/modules.py:224
#, python-format
msgid "Rejecting message in %s (by module %s)"
msgstr "Weise Nachricht in %s (durch Modul %s) zurück"

#: ../wallace/modules.py:245
#, python-format
msgid ""
"This is the email system Wallace at %s.\n"
"\n"
"I'm sorry to inform you we could not deliver the attached message\n"
"to the following recipients:\n"
"\n"
"- %s\n"
"\n"
"Your message is being delivered to any other recipients you may have\n"
"sent your message to. There is no need to resend the message to those\n"
"recipients.\n"
msgstr "Ich bin das E-Mail-System Wallace auf %s.\n\nMit Bedauern muß ich Sie informieren, daß die angehängte Nachricht\nnicht an die folgenden Empfänger zugestellt werden konnte:\n\n- %s\n\nFalls Sie noch andere Empfänger angegeben haben wurde die Nachricht\nan diese zugestellt. An diese Empfänger müssen sie die Nachricht\nnicht erneut senden.\n"

#: ../wallace/modules.py:260
#, python-format
msgid ""
"X-Wallace-Module: %s\n"
"X-Wallace-Result: REJECT\n"
msgstr "X-Wallace-Modul: %s\nX-Wallace-Ergebnis: REJECT\n"

#: ../wallace/modules.py:304
#, python-format
msgid "Accepting message in %s (by module %s)"
msgstr "Akzeptiere Nachricht in %s (durch Modul %s)"

#: ../wallace/modules.py:306
#, python-format
msgid "Accepting message in: %r"
msgstr "Akzeptiere Nachricht in: %r"

#: ../wallace/modules.py:313
#, python-format
msgid "recipients: %r"
msgstr "Empfänger: %r"

#: ../wallace/modules.py:369
#, python-format
msgid "Module '%s' already registered"
msgstr "Modul '%s' ist bereits registriert"
