# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Christoph Wickert <christoph.wickert@gmail.com>, 2011
# Grote <grote@kolabsys.com>, 2012
# balin <johannes_graumann@web.de>, 2012
# Jo <jo@caj-augsburg.de>, 2012
# bitnukl <robert@proemper.net>, 2014
# Thomas Brüderli <roundcube@gmail.com>, 2014
# Till Savekoul <till@koul.de>, 2012
msgid ""
msgstr ""
"Project-Id-Version: Kolab Groupware Solution\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-07-10 07:21-0400\n"
"PO-Revision-Date: 2014-07-22 13:01+0000\n"
"Last-Translator: Thomas Brüderli <roundcube@gmail.com>\n"
"Language-Team: German (http://www.transifex.com/projects/p/kolab/language/de/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../bin/kolab_smtp_access_policy.py:209
#, python-format
msgid "Adding policy request to instance %s"
msgstr "Füge Richtlinien-Anfrage zu Instanz %s hinzu"

#: ../bin/kolab_smtp_access_policy.py:479
msgid "Unauthorized access not allowed"
msgstr "Unberechtigter Zugriff nicht erlaubt"

#: ../bin/kolab_smtp_access_policy.py:508
#: ../bin/kolab_smtp_access_policy.py:689
msgid "Could not find recipient"
msgstr "Konnte den Empfänger nicht finden"

#: ../bin/kolab_smtp_access_policy.py:527
#, python-format
msgid "Could not find envelope sender user %s (511)"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:570
#, python-format
msgid "Obtained authenticated user details for %r: %r"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:627
#, python-format
msgid "Could not find envelope sender user %s"
msgstr "Konnte den Absender-Umschlag für den Benutzer %s nicht finden"

#: ../bin/kolab_smtp_access_policy.py:649
#, python-format
msgid "%s is unauthorized to send on behalf of %s"
msgstr "Benutzer %s ist nicht berechtigt als Benutzer %s zu senden"

#: ../bin/kolab_smtp_access_policy.py:659
#, python-format
msgid ""
"User %s attempted to use envelope sender address %s without authorization"
msgstr "Benutzer %s versuchte die Absendeadresse %s ohne Berechtigung zu verwenden"

#: ../bin/kolab_smtp_access_policy.py:713
#: ../bin/kolab_smtp_access_policy.py:724
#, python-format
msgid "Found user %s to be a delegate user of %s"
msgstr "Benutzer %s ist ein delegierter Benutzer von %s"

#: ../bin/kolab_smtp_access_policy.py:748
#, python-format
msgid ""
"Verifying authenticated sender '%(sender)s' with sasl_username "
"'%(sasl_username)s' for recipient '%(recipient)s'"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:751
#, python-format
msgid ""
"Verifying unauthenticated sender '%(sender)s' for recipient '%(recipient)s'"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:767
#, python-format
msgid "Reproducing verify_recipient(%s, %s) from cache"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:804
#, python-format
msgid "Using authentication domain %s instead of %s"
msgstr "Benutze Authentisierungsdomain %s anstelle von %s"

#: ../bin/kolab_smtp_access_policy.py:814
#, python-format
msgid "Domain %s is a primary domain"
msgstr "Die Domain %s ist die primäre Domain"

#: ../bin/kolab_smtp_access_policy.py:822
#, python-format
msgid ""
"Checking the recipient for domain %s that is not ours. This is probably a "
"configuration error."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:837
msgid ""
"This recipient address is related to multiple object entries and the SMTP "
"Access Policy can therefore not restrict message flow"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:854
#, python-format
msgid ""
"Recipient address %r not found. Allowing since the MTA was configured to "
"accept the recipient."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:890
msgid "Invalid recipient"
msgstr "Ungültiger Empfänger"

#: ../bin/kolab_smtp_access_policy.py:901
msgid "Could not find this user, accepting"
msgstr "Konnte keine Einschränkung für diesen Benutzer finden, akzeptiere Nachricht"

#: ../bin/kolab_smtp_access_policy.py:974
#: ../bin/kolab_smtp_access_policy.py:1050
#, python-format
msgid "Sender %s is not allowed to send to recipient %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1038
#, python-format
msgid "Reproducing verify_sender(%r) from cache"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1055
msgid "Unverifiable sender."
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1060
msgid "Sender is not using an alias"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1068
msgid "Sender uses unauthorized envelope sender address"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1085
msgid "Could not verify sender"
msgstr "Konnte den Absender nicht verifizieren"

#: ../bin/kolab_smtp_access_policy.py:1092
msgid ""
"Verifying whether sender is allowed to send to recipient using sender policy"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1105
#, python-format
msgid "Result is %r"
msgstr "Das Ergebnis ist %r"

#: ../bin/kolab_smtp_access_policy.py:1110
msgid "No recipient policy restrictions exist for this sender"
msgstr "Es existiert keine Empfängerrichtlinie für diesen Absender"

#: ../bin/kolab_smtp_access_policy.py:1119
msgid "Found a recipient policy to apply for this sender."
msgstr "Empfänger-Richtlinie für diesen Benutzer gefunden"

#: ../bin/kolab_smtp_access_policy.py:1134
#, python-format
msgid "Sender %s not allowed to send to recipient %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1155
msgid "Cleaning up the cache"
msgstr "Aufräumen des Cache"

#: ../bin/kolab_smtp_access_policy.py:1177
msgid ""
"The 'uri' setting in the kolab_smtp_access_policy section is soon going to "
"be deprecated in favor of 'cache_uri'"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1193
#, python-format
msgid "Operational Error in caching: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1245
#, python-format
msgid "Caching the policy result with timestamp %d"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1319
#, python-format
msgid "Returning action DEFER_IF_PERMIT: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1324
#, python-format
msgid "Returning action DUNNO: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1329
#, python-format
msgid "Returning action HOLD: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1334
#, python-format
msgid "Returning action PERMIT: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1459
#, python-format
msgid "Returning action REJECT: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1505
msgid "Starting to loop for new request"
msgstr "Starte Schleife für neue Anfrage"

#: ../bin/kolab_smtp_access_policy.py:1512
msgid "Timeout for policy request reading exceeded"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1518
msgid "End of current request"
msgstr "Ende der aktuellen Anfrage"

#: ../bin/kolab_smtp_access_policy.py:1522
#, python-format
msgid "Getting line: %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1526
msgid "Returning request"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1555
msgid "Access Policy Options"
msgstr "Zugriffsrichtlinien-Einstellungen"

#: ../bin/kolab_smtp_access_policy.py:1562
msgid "SMTP Policy request timeout."
msgstr "Zeitüberschreitung der SMTP Richtlinien-Anfrage"

#: ../bin/kolab_smtp_access_policy.py:1568
msgid "Verify the recipient access policy."
msgstr "Verifiziere die Empfänger-Zugriffs-Richtlinie."

#: ../bin/kolab_smtp_access_policy.py:1574
msgid "Verify the sender access policy."
msgstr "Verifiziere die Sender-Zugriffs-Richtlinie."

#: ../bin/kolab_smtp_access_policy.py:1580
msgid "Allow unauthenticated senders."
msgstr "Erlaube nicht authentisierte Sender."

#: ../bin/kolab_smtp_access_policy.py:1594
#, python-format
msgid "Got request instance %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1603
#, python-format
msgid "Request instance %s is in state %s"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1611
#, python-format
msgid "Request instance %s is not yet in DATA state"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1623
#, python-format
msgid "Request instance %s reached DATA state"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1643
#, python-format
msgid "Unhandled exception caught: %r"
msgstr ""

#: ../bin/kolab_smtp_access_policy.py:1647
msgid "Sender access denied"
msgstr "Sender Zugriff verweigert"

#: ../bin/kolab_smtp_access_policy.py:1649
msgid "Recipient access denied"
msgstr "Empfänger Zugriff verweigert"

#: ../bin/kolab_smtp_access_policy.py:1651
msgid "No objections"
msgstr "Keine Einwände"

#: ../conf.py:37 ../kolab-cli.py:34 ../saslauthd.py:33
msgid "Cannot load pykolab/logger.py:"
msgstr "Laden von pykolab/logger.py nicht möglich:"

#: ../kolabd/__init__.py:49 ../saslauthd/__init__.py:51
#: ../wallace/__init__.py:85
msgid "Daemon Options"
msgstr "Daemon Optionen"

#: ../kolabd/__init__.py:56 ../saslauthd/__init__.py:58
#: ../wallace/__init__.py:92
msgid "Fork to the background."
msgstr "In den Hintergrund abtauchen"

#: ../kolabd/__init__.py:65 ../saslauthd/__init__.py:67
#: ../wallace/__init__.py:118
msgid "Path to the PID file to use."
msgstr "Pfad zur PID-Datei"

#: ../kolabd/__init__.py:74 ../saslauthd/__init__.py:76
#: ../wallace/__init__.py:135
msgid "Run as user USERNAME"
msgstr "Als Benutzer USERNAME ausführen"

#: ../kolabd/__init__.py:84 ../saslauthd/__init__.py:86
#: ../wallace/__init__.py:109
msgid "Run as group GROUPNAME"
msgstr "Als Gruppe GROUPNAME ausführen"

#: ../kolabd/__init__.py:122 ../pykolab/logger.py:139 ../pykolab/utils.py:234
#: ../saslauthd/__init__.py:292 ../wallace/__init__.py:329
#, python-format
msgid "Group %s does not exist"
msgstr "Gruppe %s exisitert nicht"

#: ../kolabd/__init__.py:131 ../saslauthd/__init__.py:301
#: ../wallace/__init__.py:338
#, python-format
msgid "Switching real and effective group id to %d"
msgstr ""

#: ../kolabd/__init__.py:153 ../pykolab/logger.py:159 ../pykolab/utils.py:258
#: ../saslauthd/__init__.py:323 ../wallace/__init__.py:360
#, python-format
msgid "User %s does not exist"
msgstr "Benutzer %s existiert nicht"

#: ../kolabd/__init__.py:163 ../saslauthd/__init__.py:333
#: ../wallace/__init__.py:370
#, python-format
msgid "Switching real and effective user id to %d"
msgstr ""

#: ../kolabd/__init__.py:172 ../saslauthd/__init__.py:342
#: ../wallace/__init__.py:379
msgid "Could not change real and effective uid and/or gid"
msgstr ""

#: ../kolabd/__init__.py:192 ../saslauthd/__init__.py:133
#: ../wallace/__init__.py:399
msgid "Interrupted by user"
msgstr "Vom Benutzer unterbrochen"

#: ../kolabd/__init__.py:197 ../kolabd/__init__.py:208
msgid "Traceback occurred, please report a "
msgstr ""

#: ../kolabd/__init__.py:203 ../saslauthd/__init__.py:141
#: ../wallace/__init__.py:408
#, python-format
msgid "Type Error: %s"
msgstr "Typ-Fehler: %s"

#: ../kolabd/__init__.py:230
msgid "Could not connect to LDAP, is it running?"
msgstr ""

#: ../kolabd/__init__.py:233 ../pykolab/auth/ldap/__init__.py:2137
#: ../pykolab/cli/cmd_sync.py:36
msgid "Listing domains..."
msgstr "Liste Domains auf..."

#: ../kolabd/__init__.py:244
msgid "No domains. Not syncing"
msgstr ""

#: ../kolabd/__init__.py:275
#, python-format
msgid "added domains: %r, removed domains: %r"
msgstr ""

#: ../kolabd/process.py:33
#, python-format
msgid "Process created for domain %s"
msgstr ""

#: ../kolabd/process.py:42
#, python-format
msgid "Synchronizing for domain %s"
msgstr ""

#: ../kolabd/process.py:59
#, python-format
msgid ""
"Error in process %r, terminating:\n"
"\t%r"
msgstr ""

#: ../kolabd.py:31 ../setup-kolab.py:36 ../wallace.py:31
msgid "Cannot load pykolab/constants.py:"
msgstr "Konnte nicht pykolab/constants.py laden:"

#: ../pykolab/auth/__init__.py:89
#, python-format
msgid "Called for domain %r"
msgstr ""

#: ../pykolab/auth/__init__.py:106 ../pykolab/auth/__init__.py:115
#, python-format
msgid "Using section %s and domain %s"
msgstr ""

#: ../pykolab/auth/__init__.py:120
#, python-format
msgid "Connecting to Authentication backend for domain %s"
msgstr ""

#: ../pykolab/auth/__init__.py:131
#, python-format
msgid "Section %s has no option 'auth_mechanism'"
msgstr ""

#: ../pykolab/auth/__init__.py:138
#, python-format
msgid "Section %s has auth_mechanism: %r"
msgstr ""

#: ../pykolab/auth/__init__.py:147 ../pykolab/auth/__init__.py:156
msgid "Starting LDAP..."
msgstr "Starte LDAP..."

#: ../pykolab/auth/ldap/cache.py:126
#, python-format
msgid "Inserting cache entry %r"
msgstr ""

#: ../pykolab/auth/ldap/cache.py:147
#, python-format
msgid "Updating timestamp for cache entry %r"
msgstr ""

#: ../pykolab/auth/ldap/cache.py:155
#, python-format
msgid "Updating result_attribute for cache entry %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:52
msgid "Python LDAP library does not support persistent search"
msgstr "Die Python LDAP Bibliothek unterstützt keine persistente Suche"

#: ../pykolab/auth/ldap/__init__.py:143
#, python-format
msgid "Attempting to authenticate user %s in realm %s"
msgstr "Versuche Benutzer %s in Bereich %s zu authentisieren"

#: ../pykolab/auth/ldap/__init__.py:175 ../pykolab/auth/ldap/__init__.py:226
#, python-format
msgid "Authentication cache failed: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:216 ../pykolab/auth/ldap/__init__.py:240
#, python-format
msgid "Binding with user_dn %s and password %s"
msgstr "Binde mit user_dn %s und Passwort %s"

#: ../pykolab/auth/ldap/__init__.py:231 ../pykolab/auth/ldap/__init__.py:263
#, python-format
msgid "Failed to authenticate as user %s"
msgstr "Autorisation als Benutzer %s gescheitert"

#: ../pykolab/auth/ldap/__init__.py:249
#, python-format
msgid "Error occured, there is no such object: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:254
msgid "Authentication cache failed to clear entry"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:260
#, python-format
msgid "Exception occured: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:280
msgid "Connecting to LDAP..."
msgstr "Verbinde zum LDAP..."

#: ../pykolab/auth/ldap/__init__.py:284
#, python-format
msgid "Attempting to use LDAP URI %s"
msgstr "Versuche LDAP URI %s zu benutzen"

#: ../pykolab/auth/ldap/__init__.py:371
#, python-format
msgid "Entry ID: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:373
#, python-format
msgid "Entry DN: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:376
#, python-format
msgid ""
"ldap search: (%r, %r, filterstr='(objectclass=*)', attrlist=[ 'dn' ] + %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:453
#, python-format
msgid "Finding recipient with filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:529
#, python-format
msgid "Finding resource with filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:560
#, python-format
msgid "Using timestamp %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:595
msgid "Applying recipient policy disabled through configuration"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:600
#, python-format
msgid "Applying recipient policy to %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:617
#, python-format
msgid "Using mail attributes: %r, with primary %r and "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:628
#, python-format
msgid "key %r not in entry"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:630
#, python-format
msgid "key %r is the prim. mail attr."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:632
msgid "prim. mail pol. is not empty"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:635
#, python-format
msgid "key %r is the sec. mail attr."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:637
msgid "sec. mail pol. is not empty"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:641 ../pykolab/auth/ldap/__init__.py:655
#, python-format
msgid "Attributes %r are not yet available for entry %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:694
#, python-format
msgid "No results for mail address %s found"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:705
#, python-format
msgid "1 result for address %s found, verifying"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:715
#, python-format
msgid "Too bad, primary email address %s "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:726 ../pykolab/auth/ldap/__init__.py:815
msgid "Address assigned to us"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:781
#, python-format
msgid "No results for address %s found"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:792
#, python-format
msgid "1 result for address %s found, "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:803
msgid "Too bad, secondary email "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:830
msgid "Recipient policy composed the following set of secondary "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:841
#, python-format
msgid "Secondary mail addresses that we want is not None: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:852
msgid "Avoiding the duplication of the primary mail "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:863
#, python-format
msgid "Entry is getting secondary mail addresses: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:871
msgid "Entry did not have any secondary mail "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:888 ../pykolab/auth/ldap/__init__.py:894
#, python-format
msgid "secondary_mail_addresses: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:889 ../pykolab/auth/ldap/__init__.py:895
#, python-format
msgid "entry[%s]: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:906
#, python-format
msgid "Entry modifications list: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:934
#, python-format
msgid "Setting entry attribute %r to %r for %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:970
#, python-format
msgid ""
"Could not update dn %r:\n"
"%r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:983
#, python-format
msgid "Using filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:998
#, python-format
msgid "Synchronization is searching against base DN: %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1044
#, python-format
msgid "About to consider the user quota for %r (used: %r, "
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1115
msgid "Invalid DN, username and/or password."
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1236 ../pykolab/auth/ldap/__init__.py:1249
#: ../pykolab/auth/ldap/__init__.py:1614 ../pykolab/auth/ldap/__init__.py:1627
#, python-format
msgid "Found a subject %r with access %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1356
#, python-format
msgid "Entry %s attribute value: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1364
#, python-format
msgid "imap.user_mailbox_server(%r) result: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1684 ../pykolab/auth/ldap/__init__.py:1853
#, python-format
msgid "Result from recipient policy: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:1908
#, python-format
msgid "Kolab user %s does not have a result attribute %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2067
#, python-format
msgid "Finding domain root dn for domain %s"
msgstr "Suche root dn für die Domain %s"

#: ../pykolab/auth/ldap/__init__.py:2164
msgid "Authentication database DOWN"
msgstr "Authentisierungsdatenbank UNTEN"

#: ../pykolab/auth/ldap/__init__.py:2248 ../pykolab/auth/ldap/__init__.py:2296
#, python-format
msgid "Entry type: %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2321
#, python-format
msgid "Done with _synchronize_callback() for entry %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2393
msgid "LDAP Search Result Data Entry:"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2409
msgid "Entry Change Notification attributes:"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2414
#, python-format
msgid "Change Type: %r (%r)"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2422
#, python-format
msgid "Previous DN: %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2477
#, python-format
msgid "Object %s searched no longer exists"
msgstr "Das gesuchte Objekt %s existiert nicht mehr"

#: ../pykolab/auth/ldap/__init__.py:2487
#, python-format
msgid "%d results..."
msgstr "%d Ergebnisse..."

#: ../pykolab/auth/ldap/__init__.py:2590
#, python-format
msgid "Searching with filter %r"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2642
#, python-format
msgid "Checking for support for %s on %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2661
#, python-format
msgid "Found support for %s"
msgstr ""

#: ../pykolab/auth/ldap/__init__.py:2706
#, python-format
msgid "An error occured using %s: %r"
msgstr ""

#: ../pykolab/auth/ldap/syncrepl.py:46
msgid "The name of the persistent, unique attribute "
msgstr ""

#: ../pykolab/cli/cmd_acl_cleanup.py:34
msgid "Clean up ACLs that use identifiers that no longer exist"
msgstr ""

#: ../pykolab/cli/cmd_acl_cleanup.py:56
#, python-format
msgid "Deleting ACL %s for subject %s on folder %s"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:42
msgid "Specify the (new) alias address"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:45
msgid "Specify the existing recipient address"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:66 ../pykolab/cli/cmd_add_alias.py:70
#, python-format
msgid "Domain %r is not a local domain"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:75
msgid "Primary and secondary domain do not have the same parent domain"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:81
#, python-format
msgid "No such recipient %r"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:87
#, python-format
msgid "Recipient for alias %r already exists"
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:97
msgid "Environment is not configured for "
msgstr ""

#: ../pykolab/cli/cmd_add_alias.py:105
#, python-format
msgid "Recipient %r is not the primary recipient for address %r"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:36
#: ../pykolab/cli/cmd_count_domain_mailboxes.py:38
#: ../pykolab/cli/cmd_create_mailbox.py:36
#: ../pykolab/cli/cmd_export_mailbox.py:33
#: ../pykolab/cli/cmd_list_deleted_mailboxes.py:38
#: ../pykolab/cli/cmd_list_domain_mailboxes.py:36
#: ../pykolab/cli/cmd_list_mailboxes.py:40
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:37
#: ../pykolab/cli/cmd_list_messages.py:37 ../pykolab/cli/cmd_list_quota.py:36
#: ../pykolab/cli/cmd_list_user_subscriptions.py:36
#: ../pykolab/cli/cmd_server_info.py:34
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:38
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:39
#: ../pykolab/cli/cmd_undelete_mailbox.py:34
msgid "CLI Options"
msgstr "Kommandozeilen-Parameter"

#: ../pykolab/cli/cmd_add_domain.py:42
msgid "Add alias domain."
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:47
msgid "Add a new domain."
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:55 ../pykolab/cli/cmd_delete_domain.py:44
#: ../pykolab/cli/cmd_find_domain.py:44
msgid "Could not find credentials with sufficient permissions"
msgstr ""

#: ../pykolab/cli/cmd_add_domain.py:67 ../pykolab/cli/cmd_delete_domain.py:56
#: ../pykolab/cli/cmd_find_domain.py:56
msgid "Domain name"
msgstr "Name der Domain"

#: ../pykolab/cli/cmd_add_user_subscription.py:37
msgid "Subscribe a user to a folder."
msgstr "Aboniere einen Ordner für einen Benutzer."

#: ../pykolab/cli/cmd_add_user_subscription.py:47
#: ../pykolab/cli/cmd_add_user_subscription.py:51
#: ../pykolab/cli/cmd_remove_user_subscription.py:47
#: ../pykolab/cli/cmd_remove_user_subscription.py:51
msgid "Folder pattern"
msgstr ""

#: ../pykolab/cli/cmd_add_user_subscription.py:50
#: ../pykolab/cli/cmd_list_user_subscriptions.py:63
#: ../pykolab/cli/cmd_remove_user_subscription.py:50
msgid "User ID"
msgstr "Benutzer ID"

#: ../pykolab/cli/cmd_add_user_subscription.py:72
#: ../pykolab/cli/cmd_remove_user_subscription.py:72
#, python-format
msgid "Cannot subscribe user to folder %r:"
msgstr ""

#: ../pykolab/cli/cmd_add_user_subscription.py:73
#: ../pykolab/cli/cmd_delete_message.py:61
#: ../pykolab/cli/cmd_list_messages.py:67
#: ../pykolab/cli/cmd_remove_user_subscription.py:73
msgid "No such folder"
msgstr "Dieser Ordner ist nicht vorhanden"

#: ../pykolab/cli/cmd_count_domain_mailboxes.py:44
#: ../pykolab/cli/cmd_list_deleted_mailboxes.py:50
#: ../pykolab/cli/cmd_list_domain_mailboxes.py:48
#: ../pykolab/cli/cmd_list_mailboxes.py:52 ../pykolab/cli/cmd_list_quota.py:42
#: ../pykolab/cli/cmd_server_info.py:40
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:57
msgid "List mailboxes on server SERVER only."
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:42
msgid "Set metadata for folder to ANNOTATION=VALUE"
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:50
msgid "Create folder on PARTITION."
msgstr ""

#: ../pykolab/cli/cmd_create_mailbox.py:60
msgid "Invalid argument"
msgstr "Ungültiges Argument"

#: ../pykolab/cli/cmd_create_mailbox.py:68
msgid "Invalid argument for metadata"
msgstr "Ungültiges Argument für die Metadaten"

#: ../pykolab/cli/cmd_delete_domain.py:36
msgid "Delete a domain."
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:45
#: ../pykolab/cli/cmd_delete_mailbox_acl.py:49
#: ../pykolab/cli/cmd_set_mailbox_acl.py:50
#: ../pykolab/cli/cmd_set_mailbox_acl.py:55
msgid "ACI Subject"
msgstr ""

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:48
#: ../pykolab/cli/cmd_list_mailbox_acls.py:43
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:54
#: ../pykolab/cli/cmd_set_mailbox_acl.py:54
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:66
#: ../pykolab/cli/cmd_set_quota.py:46 ../tests/unit/test-015-translate.py:12
#: ../tests/unit/test-015-translate.py:16
#: ../tests/unit/test-015-translate.py:18
#: ../tests/unit/test-015-translate.py:20
msgid "Folder name"
msgstr "Ordnername"

#: ../pykolab/cli/cmd_delete_mailbox_acl.py:60
#: ../pykolab/cli/cmd_list_mailbox_acls.py:54
#: ../pykolab/cli/cmd_list_mailbox_metadata.py:80
#: ../pykolab/cli/cmd_set_mailbox_acl.py:67
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:94
#: ../pykolab/cli/cmd_set_quota.py:58
#, python-format
msgid "No such folder %r"
msgstr "Kein Ordner %r verfügbar"

#: ../pykolab/cli/cmd_delete_mailbox.py:46
msgid "No mailbox specified"
msgstr "Keine Mailbox angegeben"

#: ../pykolab/cli/cmd_delete_mailbox.py:56
msgid "No such folder(s)"
msgstr ""

#: ../pykolab/cli/cmd_delete_message.py:36
msgid "Delete a message from a folder"
msgstr ""

#: ../pykolab/cli/cmd_delete_message.py:49
msgid "Specify a UID"
msgstr ""

#: ../pykolab/cli/cmd_delete_message.py:52
#: ../pykolab/cli/cmd_list_messages.py:58
msgid "Specify a folder"
msgstr ""

#: ../pykolab/cli/cmd_export_mailbox.py:38
msgid "All folders this user has access to"
msgstr ""

#: ../pykolab/cli/cmd_export_mailbox.py:108
#, python-format
msgid "%s is not a directory"
msgstr "%s ist kein Verzeichnis"

#: ../pykolab/cli/cmd_export_mailbox.py:118
#, python-format
msgid "ZIP file at %s.zip"
msgstr "ZIP-Datei unter %s.zip"

#: ../pykolab/cli/cmd_export_mailbox.py:120
#, python-format
msgid "No directories found for user %s"
msgstr ""

#: ../pykolab/cli/cmd_find_domain.py:36
msgid "Find a domain."
msgstr ""

#: ../pykolab/cli/cmd_list_deleted_mailboxes.py:43
#: ../pykolab/cli/cmd_list_domain_mailboxes.py:41
#: ../pykolab/cli/cmd_list_mailboxes.py:45
#: ../pykolab/cli/cmd_list_user_subscriptions.py:41
msgid "Display raw IMAP UTF-7 folder names"
msgstr ""

#: ../pykolab/cli/cmd_list_domain_mailboxes.py:58
msgid "Domain"
msgstr "Domäne"

#: ../pykolab/cli/cmd_list_mailboxes.py:87
#, python-format
msgid "Appending folder search for %r"
msgstr ""

#: ../pykolab/cli/cmd_list_mailbox_metadata.py:44
msgid "List annotations as user USER"
msgstr ""

#: ../pykolab/cli/cmd_list_messages.py:43
msgid "Include messages flagged as \\Deleted"
msgstr ""

#: ../pykolab/cli/cmd_list_messages.py:47
msgid "List messages in a folder"
msgstr ""

#: ../pykolab/cli/cmd_list_quota.py:73 ../pykolab/cli/cmd_list_quota.py:89
#, python-format
msgid "The quota for folder %s is set to literally allow 0KB of storage."
msgstr ""

#: ../pykolab/cli/cmd_list_user_subscriptions.py:47
msgid "List unsubscribed folders"
msgstr "Liste nicht abonnierte Ordner"

#: ../pykolab/cli/cmd_list_user_subscriptions.py:50
msgid "List the folders a user is subscribed to."
msgstr "Liste die Ordner, die ein Benutzer abonniert hat."

#: ../pykolab/cli/cmd_list_user_subscriptions.py:98
#, python-format
msgid "No unsubscribed folders for user %s"
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:37
msgid "Clean up mailboxes that do no longer have an owner."
msgstr ""

#: ../pykolab/cli/cmd_mailbox_cleanup.py:61
#, python-format
msgid "Deleting folder 'user/%s'"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:49
msgid "Invalid or unqualified email address."
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:57
#, python-format
msgid "No recipient found for email address %r"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:60
#, python-format
msgid "Found the following recipient(s): %r"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:66
#, python-format
msgid "Using the following mail attributes: %r"
msgstr ""

#: ../pykolab/cli/cmd_remove_mailaddress.py:90
msgid "Found the following recipients:"
msgstr ""

#: ../pykolab/cli/cmd_remove_user_subscription.py:37
msgid "Unsubscribe a user from a folder."
msgstr "Entferne einen Benutzer-Abonement von einem Ordner."

#: ../pykolab/cli/cmd_remove_user_subscription.py:86
#, python-format
msgid "Successfully unsubscribed user %s from the following folders:"
msgstr ""

#: ../pykolab/cli/cmd_remove_user_subscription.py:92
#, python-format
msgid "User %s was not unsubscribed from any folders."
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:52
msgid "No target mailbox name specified"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:54
msgid "No source mailbox name specified"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:66
#, python-format
msgid "Source folder %r does not exist"
msgstr ""

#: ../pykolab/cli/cmd_rename_mailbox.py:70
#, python-format
msgid "Target folder %r already exists"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_acl.py:47
#: ../pykolab/cli/cmd_set_mailbox_acl.py:51
#: ../pykolab/cli/cmd_set_mailbox_acl.py:56
msgid "ACI Permissions"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:45
msgid "Set annotation as user USER"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:59
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:63
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:68
msgid "Metadata value"
msgstr ""

#: ../pykolab/cli/cmd_set_mailbox_metadata.py:62
#: ../pykolab/cli/cmd_set_mailbox_metadata.py:67
msgid "Metadata path"
msgstr ""

#: ../pykolab/cli/cmd_set_quota.py:43 ../pykolab/cli/cmd_set_quota.py:47
msgid "New quota"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:44
msgid "Delete mailboxes for recipients that do not appear to exist in LDAP."
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:50
msgid "Display changes, do not apply them."
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:88
#, python-format
msgid "Domains in IMAP not in LDAP: %r"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:101
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:142
#, python-format
msgid ""
"No recipients for '%s' (would have deleted the mailbox if not for --dry-"
"run)!"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:106
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:147
#, python-format
msgid "Deleting mailbox '%s' because it has no recipients"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:110
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:151
#, python-format
msgid "An error occurred removing mailbox %r: %r"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:112
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:153
#, python-format
msgid "Not automatically deleting shared folder '%s'"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:114
#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:155
#, python-format
msgid "No recipients for '%s' (use --delete to delete)!"
msgstr ""

#: ../pykolab/cli/cmd_sync_mailhost_attrs.py:136
#, python-format
msgid "Multiple recipients for '%s'!"
msgstr ""

#: ../pykolab/cli/cmd_sync.py:41
#, python-format
msgid "Found %d domains in %d seconds"
msgstr "%d Domains in %d Sekunden gefunden"

#: ../pykolab/cli/cmd_sync.py:51
#, python-format
msgid "Running for domain %s"
msgstr "Starte für Domain %s"

#: ../pykolab/cli/cmd_sync.py:58
#, python-format
msgid "Synchronizing users for %s took %d seconds"
msgstr "Benutzer für %s zu synchronisieren dauerte %d Sekunden"

#: ../pykolab/cli/cmd_undelete_mailbox.py:39
msgid "Do not actually execute, but state what would have been executed."
msgstr ""

#: ../pykolab/cli/cmd_undelete_mailbox.py:42
msgid "Recover mailboxes previously deleted."
msgstr ""

#: ../pykolab/cli/cmd_user_info.py:39
msgid "Email address"
msgstr "E-Mail-Adresse"

#. This is a nested command
#. This is a nested component
#: ../pykolab/cli/commands.py:98 ../pykolab/setup/components.py:90
#, python-format
msgid "Command Group: %s"
msgstr ""

#: ../pykolab/cli/commands.py:113 ../pykolab/cli/commands.py:118
msgid "No such command."
msgstr "Dieses Kommando existiert nicht."

#: ../pykolab/cli/commands.py:168 ../pykolab/setup/components.py:231
#, python-format
msgid "Command '%s' already registered"
msgstr ""

#: ../pykolab/cli/commands.py:193 ../pykolab/setup/components.py:257
#: ../wallace/modules.py:369
#, python-format
msgid "Alias for %s"
msgstr "Alias für %s"

#: ../pykolab/cli/commands.py:201 ../pykolab/setup/components.py:265
msgid "Not yet implemented"
msgstr "Diese Funktion ist noch nicht implementiert"

#: ../pykolab/cli/sieve/cmd_list.py:43 ../pykolab/cli/sieve/cmd_put.py:42
#: ../pykolab/cli/sieve/cmd_refresh.py:44 ../pykolab/cli/sieve/cmd_test.py:43
msgid "Email Address"
msgstr "E-mail-Adresse"

#: ../pykolab/cli/sieve/cmd_refresh.py:99
#: ../pykolab/plugins/sievemgmt/__init__.py:111
#, python-format
msgid "Found the following scripts for user %s: %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:100
#: ../pykolab/plugins/sievemgmt/__init__.py:112
#, python-format
msgid "And the following script is active for user %s: %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:178
#: ../pykolab/plugins/sievemgmt/__init__.py:190
#, python-format
msgid ""
"Delivery to folder active, but no folder name attribute available for user "
"%r"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:181
#: ../pykolab/plugins/sievemgmt/__init__.py:193
msgid "Delivery to folder active, but no folder name attribute configured"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:359
#, python-format
msgid "MANAGEMENT script for user %s contents: %r"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:364
#: ../pykolab/plugins/sievemgmt/__init__.py:374
#, python-format
msgid "Uploading script MANAGEMENT failed for user %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:366
#: ../pykolab/plugins/sievemgmt/__init__.py:376
#, python-format
msgid "Uploading script MANAGEMENT for user %s succeeded"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:377
#: ../pykolab/plugins/sievemgmt/__init__.py:387
#, python-format
msgid "Including script %s in USER (for user %s)"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:386
#: ../pykolab/plugins/sievemgmt/__init__.py:396
#, python-format
msgid "Uploading script USER failed for user %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:388
#: ../pykolab/plugins/sievemgmt/__init__.py:398
#, python-format
msgid "Uploading script USER for user %s succeeded"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:416
#: ../pykolab/plugins/sievemgmt/__init__.py:426
#, python-format
msgid "Uploading script MASTER failed for user %s"
msgstr ""

#: ../pykolab/cli/sieve/cmd_refresh.py:418
#: ../pykolab/plugins/sievemgmt/__init__.py:428
#, python-format
msgid "Uploading script MASTER for user %s succeeded"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:40
msgid "Unspecified command issue identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:50
msgid "Invalid command issue identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:60
#: ../pykolab/cli/telemetry/cmd_examine_session.py:65
msgid "Invalid session identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_command_issue.py:75
#: ../pykolab/cli/telemetry/cmd_examine_session.py:100
#, python-format
msgid "Session by %s on server %s"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_examine_session.py:43
msgid "Unspecified session identifier"
msgstr ""

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:35
msgid "List Options"
msgstr "Liste Optionen"

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:40
msgid "Display sessions since ..."
msgstr "Zeige Sitzungen seit..."

#: ../pykolab/cli/telemetry/cmd_list_sessions.py:58
#, python-format
msgid "Session for user %s started at %s with ID %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:57 ../pykolab/conf/entitlement.py:80
#: ../pykolab/conf/entitlement.py:98 ../pykolab/conf/entitlement.py:116
#: ../pykolab/conf/entitlement.py:230 ../pykolab/conf/entitlement.py:246
#: ../pykolab/conf/entitlement.py:262
msgid "Invalid entitlement verification "
msgstr ""

#: ../pykolab/conf/entitlement.py:120 ../pykolab/conf/entitlement.py:123
msgid "Invalid entitlement certificate"
msgstr ""

#: ../pykolab/conf/entitlement.py:132
#, python-format
msgid "Parsing entitlement file %s"
msgstr ""

#: ../pykolab/conf/entitlement.py:141
#, python-format
msgid "License file %s not readable!"
msgstr ""

#: ../pykolab/conf/entitlement.py:147
msgid "No entitlement directory found"
msgstr ""

#: ../pykolab/conf/__init__.py:87
#, python-format
msgid "Setting %s to %r (from defaults)"
msgstr "Setze %s auf %r (aus den Standardeinstellungen)"

#: ../pykolab/conf/__init__.py:106
#, python-format
msgid "Setting %s to %r (from CLI, verified)"
msgstr "Setze %s auf %r (von der Kommandozeile, überprüft)"

#: ../pykolab/conf/__init__.py:109
#, python-format
msgid "Setting %s to %r (from CLI, not checked)"
msgstr "Setze %s auf %r (von der Kommandozeile, nicht überprüft)"

#: ../pykolab/conf/__init__.py:150 ../pykolab/conf/__init__.py:207
#, python-format
msgid "Setting %s_%s to '****' (from configuration file)"
msgstr "Setze %s_%s auf '****' (aus Konfigurationsdatei)"

#: ../pykolab/conf/__init__.py:152 ../pykolab/conf/__init__.py:209
#, python-format
msgid "Setting %s_%s to %r (from configuration file)"
msgstr "Setze %s_%s auf %r (aus Konfigurationsdatei)"

#: ../pykolab/conf/__init__.py:162
msgid "Setting options from configuration file"
msgstr "Hole Optionen aus Konfigurationsdatei"

#: ../pykolab/conf/__init__.py:223
#, python-format
msgid "Configuration file %s not readable"
msgstr "Konfigurationsdatei %s ist nicht lesbar"

#: ../pykolab/conf/__init__.py:226
#, python-format
msgid "Reading configuration file %s"
msgstr "Lese Konfigurationsdatei %s"

#: ../pykolab/conf/__init__.py:230
#, python-format
msgid "Invalid configuration file %s"
msgstr "Ungültige Konfigurationsdatei %s"

#: ../pykolab/conf/__init__.py:233
#, python-format
msgid "No master configuration section [kolab] in configuration file %s"
msgstr ""

#. #
#. # Runtime Options
#. #
#: ../pykolab/conf/__init__.py:267
msgid "Runtime Options"
msgstr "Laufzeit-Einstellungen"

#: ../pykolab/conf/__init__.py:272
msgid "Configuration file to use"
msgstr "Konfigurationsdatei, die benutzt werden soll"

#: ../pykolab/conf/__init__.py:278
msgid "Set the debugging "
msgstr "Stelle Fehlerbehebung ein"

#: ../pykolab/conf/__init__.py:286
msgid "Set the logging level. "
msgstr "Setze das Protokollniveau"

#: ../pykolab/conf/__init__.py:294
msgid "Log file to use"
msgstr "Protokolldatei"

#: ../pykolab/conf/__init__.py:300
msgid "Be quiet."
msgstr "Sei still."

#: ../pykolab/conf/__init__.py:306
msgid "Answer yes to all questions."
msgstr "Ja auf alle Fragen."

#: ../pykolab/conf/__init__.py:328
msgid "No command supplied"
msgstr "Kein Befehl angegeben"

#: ../pykolab/conf/__init__.py:416
msgid "Insufficient options. Need section, key and value -in that order."
msgstr "Unzureichende Optionen. Brauche Sektion, Schlüssel und Wert in dieser Reihenfolge."

#: ../pykolab/conf/__init__.py:419
#, python-format
msgid "No section '%s' exists."
msgstr "Es existiert keine Sektion '%s'."

#: ../pykolab/conf/__init__.py:461
#, python-format
msgid "Setting %s to %r (from the default values for CLI options)"
msgstr "Setze %s auf %r (aus den Standardwerten für Kommandozeilenoptionen)"

#: ../pykolab/conf/__init__.py:534
#, python-format
msgid "Could not execute configuration function: %s"
msgstr "Konnte die Konfigurationsfunktion nicht ausführen: %s"

#: ../pykolab/conf/__init__.py:542
#, python-format
msgid "Option %s/%s does not exist in config file %s, pulling from defaults"
msgstr "Die Option %s/%s existiert in der Konfigurationsdatei %s nicht, sie wird aus den Standardeinstellungen geholt"

#: ../pykolab/conf/__init__.py:550 ../pykolab/conf/__init__.py:553
msgid "Option does not exist in defaults."
msgstr "Diese Option hat keinen Standardwert."

#: ../pykolab/conf/__init__.py:563
#, python-format
msgid "Configuration file %s not readable."
msgstr "Konfigurationsdatei %s ist nicht lesbar."

#: ../pykolab/conf/__init__.py:566
#, python-format
msgid "Configuration file %s does not exist."
msgstr "Konfigurationsdatei %s existiert nicht."

#: ../pykolab/conf/__init__.py:571
msgid ""
"WARNING: A negative debug level value does not make this program be any more"
" silent."
msgstr "Warnung: Eine negative Fehlerprotokollierungszahl macht dieses Programm nicht noch stiller."

#: ../pykolab/conf/__init__.py:577
msgid "This program has 9 levels of verbosity. Using the maximum of 9."
msgstr "Dieses Programm hat 9 Ebenen der Detailliertheit. Benutze das Maximum 9."

#: ../pykolab/conf/__init__.py:585 ../pykolab/conf/__init__.py:591
msgid "Cannot start SASL authentication daemon"
msgstr "Konnte SASL Authentisierungsdaemon nicht starten"

#: ../pykolab/conf/__init__.py:602
msgid "No imaplib library found."
msgstr "Keine imaplib-Bibliothek gefunden."

#: ../pykolab/conf/__init__.py:612
msgid "No LMTP class found in the smtplib library."
msgstr "Keine Klasse namens LMTP in der smtplib-Bibliothek gefunden."

#: ../pykolab/conf/__init__.py:622
msgid "No SMTP class found in the smtplib library."
msgstr "Keine Klasse namens SMTP in der smtplib-Bibliothek gefunden."

#: ../pykolab/conf/__init__.py:636
#, python-format
msgid "Found you specified a specific set of items to test: %s"
msgstr ""

#: ../pykolab/conf/__init__.py:644
#, python-format
msgid "Selectively selecting: %s"
msgstr ""

#: ../pykolab/constants.py.in:40
msgid ""
"PyKolab is a Kolab Systems product. For more information about Kolab or "
"PyKolab, visit http://www.kolabsys.com"
msgstr ""

#: ../pykolab/constants.py.in:53
msgid "WARNING"
msgstr "WARNUNG"

#: ../pykolab/constants.py.in:53
msgid ""
"The Fully Qualified Domain Name or FQDN for this system is incorrect. "
"Falling back to 'localdomain'."
msgstr ""

#: ../pykolab/constants.py.in:72
msgid "389 Directory Server or Red Hat Directory Server"
msgstr "389 Verzeichnisserver oder Red Hat Verzeichnisserver"

#: ../pykolab/constants.py.in:76 ../pykolab/constants.py.in:80
msgid "OpenLDAP or compatible"
msgstr "OpenLDAP oder kompatibel"

#: ../pykolab/imap/cyrus.py:80
#, python-format
msgid "Could not connect to Cyrus IMAP server %r"
msgstr "Verbindung zum Cyrus IMAP-Server %r nicht möglich"

#: ../pykolab/imap/cyrus.py:137
#, python-format
msgid "Continuing with separator: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:142
msgid "Detected we are running in a Murder topology"
msgstr ""

#: ../pykolab/imap/cyrus.py:146
msgid "This system is not part of a murder topology"
msgstr ""

#: ../pykolab/imap/cyrus.py:167
#, python-format
msgid "Checking actual backend server for folder %s through annotations"
msgstr ""

#: ../pykolab/imap/cyrus.py:172
msgid "Possibly reproducing the find "
msgstr ""

#: ../pykolab/imap/cyrus.py:195
#, python-format
msgid "Could not get the annotations after %s tries."
msgstr ""

#: ../pykolab/imap/cyrus.py:199
#, python-format
msgid "No annotations for %s: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:206
#, python-format
msgid "Server for INBOX folder %s is %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:226
#, python-format
msgid "Setting quota for folder %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:230
#, python-format
msgid "Could not set quota for mailfolder %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:239
#, python-format
msgid "Moving INBOX folder %s to %s"
msgstr "Verschiebe Eingangsordner %s nach %s"

#: ../pykolab/imap/cyrus.py:254
#, python-format
msgid "Setting annotation %s on folder %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:259
#, python-format
msgid "Could not set annotation %r on mail folder %r: %r"
msgstr ""

#: ../pykolab/imap/cyrus.py:263
#, python-format
msgid "Transferring folder %s from %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:323
#, python-format
msgid "Undeleting %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:334
#, python-format
msgid "Would have transfered %s from %s to %s"
msgstr ""

#: ../pykolab/imap/cyrus.py:336
#, python-format
msgid "Would have renamed %s to %s"
msgstr ""

#: ../pykolab/imap/__init__.py:46
#, python-format
msgid "Cleaning up ACL entries for %s across all folders"
msgstr ""

#: ../pykolab/imap/__init__.py:61
#, python-format
msgid "Cleaning up ACL entries referring to identifier %s"
msgstr ""

#: ../pykolab/imap/__init__.py:70
#, python-format
msgid "Iterating over %d folders"
msgstr ""

#. Set the ACL to '' (effectively deleting the ACL entry)
#: ../pykolab/imap/__init__.py:83
#, python-format
msgid "Removing acl %r for subject %r from folder %r"
msgstr ""

#: ../pykolab/imap/__init__.py:145
msgid "No administrator password is available."
msgstr ""

#: ../pykolab/imap/__init__.py:153
#, python-format
msgid "Logging on to Cyrus IMAP server %s"
msgstr "Anmeldung am Cyrus IMAP Server %s"

#: ../pykolab/imap/__init__.py:162
#, python-format
msgid "Logging on to Dovecot IMAP server %s"
msgstr "Anmeldung am Dovecot IMAP Server %s"

#: ../pykolab/imap/__init__.py:171
#, python-format
msgid "Logging on to generic IMAP server %s"
msgstr "Anmeldung am generischen IMAP Server %s"

#: ../pykolab/imap/__init__.py:189
#, python-format
msgid "Reusing existing IMAP server connection to %s"
msgstr "Benutze Verbindung zum IMAP Server %s wieder"

#: ../pykolab/imap/__init__.py:191
#, python-format
msgid "Reconnecting to IMAP server %s"
msgstr "Verbinde nochmal zum IMAP Server %s"

#: ../pykolab/imap/__init__.py:208
msgid "Called imap.disconnect() on a server that we had no connection to."
msgstr ""

#: ../pykolab/imap/__init__.py:222 ../pykolab/imap/__init__.py:234
#, python-format
msgid "Could not create folder %r"
msgstr ""

#: ../pykolab/imap/__init__.py:223
#, python-format
msgid " on server %r"
msgstr ""

#: ../pykolab/imap/__init__.py:244 ../pykolab/imap/__init__.py:246
#, python-format
msgid "%r has no attribute %s"
msgstr "%r hat kein Attribut %s"

#: ../pykolab/imap/__init__.py:393 ../pykolab/imap/__init__.py:428
#, python-format
msgid "Creating new shared folder %s"
msgstr "Erzeuge einen neuen geteilten Ordner %s"

#: ../pykolab/imap/__init__.py:453 ../pykolab/imap/__init__.py:675
#, python-format
msgid "Downcasing mailbox name %r"
msgstr ""

#: ../pykolab/imap/__init__.py:457
#, python-format
msgid "Creating new mailbox for user %s"
msgstr "Erzeuge eine neue Mailbox für Benutzer %s"

#: ../pykolab/imap/__init__.py:470
msgid "Waiting for the Cyrus IMAP Murder to settle..."
msgstr ""

#: ../pykolab/imap/__init__.py:516
#, python-format
msgid "Creating additional folders for user %s"
msgstr "Erzeuge weitere Order für Benutzer %s"

#: ../pykolab/imap/__init__.py:535
#, python-format
msgid "Waiting for the Cyrus murder to settle... %r"
msgstr ""

#: ../pykolab/imap/__init__.py:547
#, python-format
msgid "Correcting additional folder name from %r to %r"
msgstr ""

#: ../pykolab/imap/__init__.py:553
#, python-format
msgid "Mailbox already exists: %s"
msgstr "Mailbox existiert bereits: %s"

#: ../pykolab/imap/__init__.py:593
msgid "Subscribing user to the additional folders"
msgstr "Abonniere weitere Ordner für den Benutzer"

#: ../pykolab/imap/__init__.py:607
msgid "Using the following tests for folder subscriptions:"
msgstr ""

#: ../pykolab/imap/__init__.py:609
#, python-format
msgid "    %r"
msgstr ""

#: ../pykolab/imap/__init__.py:612
#, python-format
msgid "Folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:624
#, python-format
msgid "Subscribing %s to folder %s"
msgstr ""

#: ../pykolab/imap/__init__.py:628
#, python-format
msgid "Subscribing %s to folder %s failed: %r"
msgstr ""

#: ../pykolab/imap/__init__.py:658
#, python-format
msgid "Could not rename %s to reside on partition %s"
msgstr ""

#: ../pykolab/imap/__init__.py:691
#, python-format
msgid "INBOX folder to rename (%s) does not exist"
msgstr ""

#: ../pykolab/imap/__init__.py:694 ../pykolab/imap/__init__.py:770
#, python-format
msgid "Renaming INBOX from %s to %s"
msgstr "Benenne INBOX Ordner von %s in %s um"

#: ../pykolab/imap/__init__.py:698
#, python-format
msgid "Could not rename INBOX folder %s to %s"
msgstr "Konnte INBOX Ordner nicht von %s in %s umbenennen"

#: ../pykolab/imap/__init__.py:700 ../pykolab/imap/__init__.py:774
#, python-format
msgid ""
"Moving INBOX folder %s won't succeed as target folder %s already exists"
msgstr "Der INBOX-Ordner %s kann nicht verschoben werden, weil der Zielordner %s bereits existiert"

#: ../pykolab/imap/__init__.py:704
#, python-format
msgid "Server for mailbox %r is %r"
msgstr ""

#: ../pykolab/imap/__init__.py:712
#, python-format
msgid "Looking for folder '%s', we found folders: %r"
msgstr "Auf der Suche nach dem Ordner '%s' haben wir diese Ordner gefunden: %r"

#: ../pykolab/imap/__init__.py:735
#, python-format
msgid "Setting ACL rights %s for subject %s on folder "
msgstr "Richte ACL Rechte %s für Subjekt %s des Ordners ein"

#: ../pykolab/imap/__init__.py:746
#, python-format
msgid "Removing ACL rights %s for subject %s on folder "
msgstr ""

#: ../pykolab/imap/__init__.py:767
#, python-format
msgid "Found old INBOX folder %s"
msgstr "Alter INBOX-Ordner %s gefunden"

#: ../pykolab/imap/__init__.py:776
#, python-format
msgid "Did not find old folder user/%s to rename"
msgstr "Konnte alten Ordner user/%s nicht zum umbenennen finden."

#: ../pykolab/imap/__init__.py:778
msgid "Value for user is not a dictionary"
msgstr "Der Wert für user ist kein dictionary"

#. TODO: Go in fact correct the quota.
#: ../pykolab/imap/__init__.py:846
#, python-format
msgid "Cannot get current IMAP quota for folder %s"
msgstr "Kann aktuelles IMAP Kontingent für den Ordner %s nicht bekommen"

#: ../pykolab/imap/__init__.py:859
#, python-format
msgid "Quota for %s currently is %s"
msgstr "Kontingent für %s ist aktuell %s"

#: ../pykolab/imap/__init__.py:865
#, python-format
msgid "Adjusting authentication database quota for folder %s to %d"
msgstr ""

#: ../pykolab/imap/__init__.py:870
#, python-format
msgid "Correcting quota for %s to %s (currently %s)"
msgstr ""

#: ../pykolab/imap/__init__.py:947
#, python-format
msgid "Checking folder: %s"
msgstr "Überprüfe Ordner: %s"

#: ../pykolab/imap/__init__.py:952
#, python-format
msgid "Folder has no corresponding user (1): %s"
msgstr ""

#: ../pykolab/imap/__init__.py:955
#, python-format
msgid "Folder has no corresponding user (2): %s"
msgstr ""

#. We got user identifier only
#: ../pykolab/imap/__init__.py:970
msgid "Please don't give us just a user identifier"
msgstr ""

#: ../pykolab/imap/__init__.py:973
#, python-format
msgid "Deleting folder %s"
msgstr "Lösche Verzeichnis %s"

#: ../pykolab/__init__.py:50
msgid "Returning thread local configuration"
msgstr ""

#: ../pykolab/itip/__init__.py:43
#, python-format
msgid "Method %r not really interesting for us."
msgstr ""

#: ../pykolab/itip/__init__.py:49
#, python-format
msgid "Raw iTip payload: %s"
msgstr ""

#: ../pykolab/itip/__init__.py:59
msgid "Could not read iTip from message."
msgstr ""

#: ../pykolab/itip/__init__.py:67
#, python-format
msgid "Duplicate iTip object: %s"
msgstr ""

#: ../pykolab/itip/__init__.py:90
msgid "iTip event without a start"
msgstr ""

#: ../pykolab/itip/__init__.py:132
msgid "Message is not an iTip message (non-multipart message)"
msgstr ""

#: ../pykolab/itip/__init__.py:225
#, python-format
msgid "Failed to compose iTip reply message: %r"
msgstr ""

#: ../pykolab/itip/__init__.py:236 ../wallace/module_invitationpolicy.py:936
#: ../wallace/module_resources.py:964
#, python-format
msgid "SMTP sendmail error: %r"
msgstr ""

#: ../pykolab/logger.py:173 ../pykolab/logger.py:179
#, python-format
msgid "Could not change permissions on %s: %r"
msgstr ""

#: ../pykolab/logger.py:196
#, python-format
msgid "Cannot log to file %s: %s"
msgstr ""

#: ../pykolab/plugins/defaultfolders/__init__.py:47
#, python-format
msgid "Plugin %s called without required keyword %s."
msgstr ""

#: ../pykolab/plugins/defaultfolders/__init__.py:53
msgid "Could not parse additional_folders"
msgstr ""

#: ../pykolab/plugins/dynamicquota/__init__.py:58
#, python-format
msgid "No keyword %s passed to set_user_folder_quota"
msgstr ""

#: ../pykolab/plugins/dynamicquota/__init__.py:70
#, python-format
msgid "Quota '%s' not an integer!"
msgstr ""

#: ../pykolab/plugins/__init__.py:70
#, python-format
msgid "ImportError for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:74
#, python-format
msgid "RuntimeError for plugin %s: %s"
msgstr "Laufzeitfehler von Plugin %s: %s"

#: ../pykolab/plugins/__init__.py:78
#, python-format
msgid "Plugin %s failed to load (%s: %s)"
msgstr "Plugin %s konnte nicht geladen werden (%s: %s)"

#: ../pykolab/plugins/__init__.py:116 ../pykolab/plugins/__init__.py:118
#, python-format
msgid "Cannot set defaults for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:120
#, python-format
msgid "Cannot set defaults for plugin %s: Unknown Error"
msgstr ""

#: ../pykolab/plugins/__init__.py:123
#, python-format
msgid "Not setting defaults for plugin %s: No function 'set_defaults()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:142
#, python-format
msgid "Cannot set runtime for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:144
#, python-format
msgid "Not setting runtime for plugin %s: No function 'set_runtime()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:163 ../pykolab/plugins/__init__.py:165
#, python-format
msgid "Cannot add options for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:167
#, python-format
msgid "Not adding options for plugin %s: No function 'add_options()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:187
#, python-format
msgid "Cannot check options for plugin %s: %s"
msgstr "Kein Zugriff auf Einstellungen des Plugins %s: %s"

#: ../pykolab/plugins/__init__.py:189
#, python-format
msgid "Not checking options for plugin %s: No function 'check_options()'"
msgstr ""

#: ../pykolab/plugins/__init__.py:227
#, python-format
msgid "Executing hook %s for plugin %s"
msgstr ""

#: ../pykolab/plugins/__init__.py:231 ../pykolab/plugins/__init__.py:233
#, python-format
msgid "Cannot execute hook %s for plugin %s: %s"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:79
msgid "Attribute substitution for 'mail' failed in Recipient Policy"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:116
msgid "Could not parse the alternative mail routines"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:120
#, python-format
msgid "Alternative mail routines: %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:127
#, python-format
msgid ""
"An error occurred in composing the secondary mail attribute for entry %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:138
#: ../pykolab/plugins/recipientpolicy/__init__.py:153
#, python-format
msgid "Appending additional mail address: %s"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:142
#, python-format
msgid "Policy for secondary email address failed: %r"
msgstr ""

#: ../pykolab/plugins/recipientpolicy/__init__.py:157
msgid ""
"Attribute substitution for 'alternative_mail' failed in Recipient Policy"
msgstr ""

#: ../pykolab/plugins/roundcubedb/__init__.py:48
#, python-format
msgid "user_delete: %r"
msgstr ""

#: ../pykolab/plugins/roundcubedb/__init__.py:55
#: ../pykolab/setup/setup_roundcube.py:160
msgid "Roundcube installation path not found."
msgstr ""

#: ../pykolab/plugins/sievemgmt/__init__.py:51
msgid "Wrong number of arguments for sieve management plugin"
msgstr ""

#: ../pykolab/setup/components.py:58
msgid "Display this help."
msgstr "Zeige diese Hilfe."

#: ../pykolab/setup/components.py:149
msgid "No component selected, continuing for all components"
msgstr ""

#: ../pykolab/setup/components.py:187 ../pykolab/setup/components.py:192
msgid "No such component."
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:46
msgid "Setup Free/Busy."
msgstr ""

#: ../pykolab/setup/setup_freebusy.py:50
msgid "Free/Busy is not installed on this system"
msgstr ""

#: ../pykolab/setup/setup_imap.py:45
msgid "Setup IMAP."
msgstr "Richte IMAP ein."

#: ../pykolab/setup/setup_imap.py:89
msgid "Could not write out Cyrus IMAP configuration file /etc/imapd.conf"
msgstr ""

#: ../pykolab/setup/setup_imap.py:114
msgid "Could not write out Cyrus IMAP configuration file /etc/cyrus.conf"
msgstr ""

#: ../pykolab/setup/setup_imap.py:158
msgid "Could not start the cyrus-imapd and kolab-saslauthd services."
msgstr ""

#: ../pykolab/setup/setup_imap.py:173 ../pykolab/setup/setup_kolabd.py:81
#: ../pykolab/setup/setup_ldap.py:426 ../pykolab/setup/setup_mta.py:455
#: ../pykolab/setup/setup_mysql.py:58 ../pykolab/setup/setup_roundcube.py:237
#: ../pykolab/setup/setup_syncroton.py:102
msgid "Could not configure to start on boot, the "
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:43
msgid "Setup the Kolab daemon."
msgstr "Richte den Kolab Daemon ein."

#: ../pykolab/setup/setup_kolabd.py:51
#, python-format
msgid ""
"\n"
"                            Copying the configuration section for 'example.org' over to\n"
"                            a section applicable to your domain '%s'.\n"
"                        "
msgstr ""

#: ../pykolab/setup/setup_kolabd.py:72
msgid "Could not start the kolab server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:45
msgid "LDAP Options"
msgstr "LDAP Optionen"

#: ../pykolab/setup/setup_ldap.py:52
msgid "Specify FQDN (overriding defaults)."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:60
msgid "Allow anonymous binds (default: no)."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:68
msgid "Skip setting up the LDAP server."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:76
msgid "Setup configuration for OpenLDAP compatibility."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:84
msgid "Setup configuration for Active Directory compatibility."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:88
msgid "Setup LDAP."
msgstr "LDAP Einrichten"

#: ../pykolab/setup/setup_ldap.py:97
msgid "Skipping setup of LDAP, as specified"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:126
msgid ""
"\n"
"                        You can not configure Kolab to run against OpenLDAP\n"
"                        and Active Directory simultaneously.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:139
msgid ""
"\n"
"                                It seems 389 Directory Server has an existing\n"
"                                instance configured. This setup script does not\n"
"                                intend to destroy or overwrite your data. Please\n"
"                                make sure /etc/dirsrv/ and /var/lib/dirsrv/ are\n"
"                                clean so that this setup does not have to worry.\n"
"                            "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:154
msgid ""
"\n"
"                        Please supply a password for the LDAP administrator user\n"
"                        'admin', used to login to the graphical console of 389\n"
"                        Directory server.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:162
msgid "Administrator password"
msgstr "Administrator Passwort"

#: ../pykolab/setup/setup_ldap.py:169
msgid ""
"\n"
"                        Please supply a password for the LDAP Directory Manager\n"
"                        user, which is the administrator user you will be using\n"
"                        to at least initially log in to the Web Admin, and that\n"
"                        Kolab uses to perform administrative tasks.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:178
msgid "Directory Manager password"
msgstr "Verzeichnismanager Passwort"

#: ../pykolab/setup/setup_ldap.py:185
msgid ""
"\n"
"                        Please choose the system user and group the service\n"
"                        should use to run under. These should be existing,\n"
"                        unprivileged, local system POSIX accounts with no shell.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:195 ../pykolab/setup/setup_ldap.py:198
msgid "User"
msgstr "Benutzer"

#: ../pykolab/setup/setup_ldap.py:196 ../pykolab/setup/setup_ldap.py:199
msgid "Group"
msgstr "Gruppe"

#: ../pykolab/setup/setup_ldap.py:234
msgid ""
"\n"
"                        This setup procedure plans to set up Kolab Groupware for\n"
"                        the following domain name space. This domain name is\n"
"                        obtained from the reverse DNS entry on your network\n"
"                        interface. Please confirm this is the appropriate domain\n"
"                        name space.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:248
msgid "Domain name to use"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:253 ../pykolab/setup/setup_ldap.py:278
msgid ""
"\n"
"                                    Invalid input. Please try again.\n"
"                                "
msgstr "\n                                    Ungültige Eingabe. Bitte nochmals versuchen.\n                                "

#: ../pykolab/setup/setup_ldap.py:262
msgid ""
"\n"
"                        The standard root dn we composed for you follows. Please\n"
"                        confirm this is the root dn you wish to use.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:273
msgid "Root DN to use"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:325
msgid "No directory server setup tool available."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:337
msgid ""
"\n"
"                    Setup is now going to set up the 389 Directory Server. This\n"
"                    may take a little while (during which period there is no\n"
"                    output and no progress indication).\n"
"                "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:344
msgid "Setting up 389 Directory Server"
msgstr "Richte 389 Verzeichnisserver ein"

#: ../pykolab/setup/setup_ldap.py:356
msgid ""
"\n"
"                        An error was detected in the setup procedure for 389\n"
"                        Directory Server. This setup will write out stderr and\n"
"                        stdout to /var/log/kolab/setup.error.log and\n"
"                        /var/log/kolab/setup.out.log respectively, before it\n"
"                        exits.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:373
msgid "Setup DS stdout:"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:376
msgid "Setup DS stderr:"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:402
msgid "Could not copy the LDAP extensions for Kolab"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:405
msgid "Could not find the ldap Kolab schema file"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:417
msgid "Could not start the directory server service."
msgstr ""

#: ../pykolab/setup/setup_ldap.py:431
msgid ""
"\n"
"                        Please supply a Cyrus Administrator password. This\n"
"                        password is used by Kolab to execute administrative\n"
"                        tasks in Cyrus IMAP. You may also need the password\n"
"                        yourself to troubleshoot Cyrus IMAP and/or perform\n"
"                        other administrative tasks against Cyrus IMAP directly.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:441
msgid "Cyrus Administrator password"
msgstr "Cyrus Administrator Passwort"

#: ../pykolab/setup/setup_ldap.py:448
msgid ""
"\n"
"                        Please supply a Kolab Service account password. This\n"
"                        account is used by various services such as Postfix,\n"
"                        and Roundcube, as anonymous binds to the LDAP server\n"
"                        will not be allowed.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_ldap.py:457
msgid "Kolab Service password"
msgstr "Kolab-Dienst-Passwort"

#: ../pykolab/setup/setup_ldap.py:467
msgid "Writing out configuration to kolab.conf"
msgstr "Schreibe Einstellungen in kolab.conf"

#: ../pykolab/setup/setup_ldap.py:481
msgid "Inserting service users into LDAP."
msgstr "Füge Service-Benutzer ins LDAP ein."

#: ../pykolab/setup/setup_ldap.py:555
msgid "Writing out cn=kolab,cn=config"
msgstr "Schreibe cn=kolab,cn=config"

#. TODO: Add kolab-admin role
#. TODO: Assign kolab-admin admin ACLs
#: ../pykolab/setup/setup_ldap.py:579
#, python-format
msgid "Adding domain %s to list of domains for this deployment"
msgstr "Füge Domain %s zu dieser Installation hinzu"

#: ../pykolab/setup/setup_ldap.py:607
msgid "Disabling anonymous binds"
msgstr "Stelle anonymes Binden ab"

#. TODO: Ensure the uid attribute is unique
#. TODO^2: Consider renaming the general "attribute uniqueness to "uid
#. attribute uniqueness"
#: ../pykolab/setup/setup_ldap.py:615
msgid "Enabling attribute uniqueness plugin"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:621
msgid "Enabling referential integrity plugin"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:627
msgid "Enabling and configuring account policy plugin"
msgstr ""

#. TODO: Add kolab-admin role
#: ../pykolab/setup/setup_ldap.py:642
msgid "Adding the kolab-admin role"
msgstr "Füge Kolab-Admin Rolle hinzu"

#. TODO: User writeable attributes on root_dn
#: ../pykolab/setup/setup_ldap.py:653
#, python-format
msgid "Setting access control to %s"
msgstr ""

#: ../pykolab/setup/setup_ldap.py:679
msgid "Could not start and configure to start on boot, the "
msgstr ""

#: ../pykolab/setup/setup_mta.py:41
msgid "Setup MTA."
msgstr "Richte MTA ein."

#: ../pykolab/setup/setup_mta.py:317 ../pykolab/setup/setup_php.py:106
#, python-format
msgid "Setting key %r to %r"
msgstr ""

#: ../pykolab/setup/setup_mta.py:350
msgid "Could not write out Postfix configuration file /etc/postfix/master.cf"
msgstr ""

#: ../pykolab/setup/setup_mta.py:397
msgid "Could not write out Amavis configuration file amavisd.conf"
msgstr ""

#: ../pykolab/setup/setup_mta.py:405
msgid "Not writing out any configuration for Amavis."
msgstr ""

#: ../pykolab/setup/setup_mta.py:437
msgid "Could not start the postfix, clamav and amavisd services services."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:39
msgid "Setup MySQL."
msgstr "Richte MySQL ein."

#: ../pykolab/setup/setup_mysql.py:49
msgid "Could not start the MySQL database service."
msgstr ""

#: ../pykolab/setup/setup_mysql.py:71
msgid "What MySQL server are we setting up?"
msgstr ""

#: ../pykolab/setup/setup_mysql.py:75
msgid ""
"\n"
"                        Please supply the root password for MySQL, so we can set\n"
"                        up user accounts for other components that use MySQL.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:82 ../pykolab/setup/setup_mysql.py:99
#: ../pykolab/setup/setup_roundcube.py:183
#: ../pykolab/setup/setup_syncroton.py:63
msgid "MySQL root password"
msgstr "MySQL root Password"

#: ../pykolab/setup/setup_mysql.py:88
msgid ""
"\n"
"                        Please supply a root password for MySQL. This password\n"
"                        will be the administrative user for this MySQL server,\n"
"                        and it should be kept a secret. After this setup process\n"
"                        has completed, Kolab is going to discard and forget\n"
"                        about this password, but you will need it for\n"
"                        administrative tasks in MySQL.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:139
msgid ""
"\n"
"                        Please supply a password for the MySQL user 'kolab'.\n"
"                        This password will be used by Kolab services, such as\n"
"                        the Web Administration Panel.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_mysql.py:147
msgid "MySQL kolab password"
msgstr "MySQL-kolab Password"

#: ../pykolab/setup/setup_mysql.py:165
msgid "Could not find the MySQL Kolab schema file"
msgstr ""

#: ../pykolab/setup/setup_php.py:42
msgid "PHP Options"
msgstr "PHP Optionen"

#: ../pykolab/setup/setup_php.py:49
msgid "Specify the timezone for PHP."
msgstr "Zeitzone für PHP definieren."

#: ../pykolab/setup/setup_php.py:57
msgid "Specify the path to the php.ini file used with the webserver."
msgstr ""

#: ../pykolab/setup/setup_php.py:61
msgid "Setup PHP."
msgstr "Richte PHP ein."

#: ../pykolab/setup/setup_php.py:66
msgid ""
"\n"
"                        Please supply the timezone PHP should be using.\n"
"                        You have to use a Continent or Country / City locality name\n"
"                        like 'Europe/Berlin', but not just 'CEST'.\n"
"                    "
msgstr ""

#: ../pykolab/setup/setup_php.py:74
msgid "Timezone ID"
msgstr "Zeitzonen ID"

#: ../pykolab/setup/setup_php.py:80
#, python-format
msgid "Cannot configure PHP through %r (No such file or directory)"
msgstr ""

#: ../pykolab/setup/setup_php.py:91
msgid "Could not find PHP configuration file php.ini"
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:44
msgid "Setup Roundcube."
msgstr "Stelle Roundcube ein."

#: ../pykolab/setup/setup_roundcube.py:48
msgid ""
"\n"
"                    Please supply a password for the MySQL user 'roundcube'.\n"
"                    This password will be used by the Roundcube webmail\n"
"                    interface.\n"
"                "
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:56
msgid "MySQL roundcube password"
msgstr "MySQL roundcube Passwort"

#: ../pykolab/setup/setup_roundcube.py:120
#, python-format
msgid "Using template file %r"
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:127
#, python-format
msgid "Successfully compiled template %r, writing out to %r"
msgstr ""

#: ../pykolab/setup/setup_roundcube.py:228
#: ../pykolab/setup/setup_syncroton.py:93
msgid "Could not start the webserver server service."
msgstr ""

#: ../pykolab/setup/setup_syncroton.py:40
msgid "Setup Syncroton."
msgstr "Richte Syncroton ein."

#. start_max = (int)(time.time())
#: ../pykolab/telemetry.py:588
#, python-format
msgid "Expiring sessions that started before or on %d"
msgstr ""

#: ../pykolab/telemetry.py:601
#, python-format
msgid "Expiring session ID: %d"
msgstr ""

#: ../pykolab/telemetry.py:620
#, python-format
msgid "Session with ID %d expired from database"
msgstr ""

#: ../pykolab/telemetry.py:646
#, python-format
msgid "Operational Error in telemetry database: %s"
msgstr ""

#: ../pykolab/telemetry.py:652
msgid "No database available"
msgstr "Keine Datenbank verfügbar"

#: ../pykolab/utils.py:62 ../pykolab/utils.py:64
#, python-format
msgid "Confirm %s: "
msgstr "Bestätige %s:"

#: ../pykolab/utils.py:67
msgid "Incorrect confirmation. "
msgstr "Ungültige Bestätigung."

#: ../pykolab/utils.py:72 ../pykolab/utils.py:77
#, python-format
msgid "%s: "
msgstr "%s:"

#: ../pykolab/utils.py:74 ../pykolab/utils.py:79
#, python-format
msgid "%s [%s]: "
msgstr "%s [%s]: "

#: ../pykolab/utils.py:124
msgid "Please answer 'yes' or 'no'."
msgstr "Bitte antworten Sie mit 'yes' (ja) oder 'no' (nein)."

#: ../pykolab/utils.py:164
msgid "Choice"
msgstr ""

#: ../pykolab/utils.py:167
msgid "Choice (type '?' for options)"
msgstr ""

#: ../pykolab/utils.py:268
#, python-format
msgid "Could not change the permissions on %s"
msgstr ""

#: ../pykolab/utils.py:479
#, python-format
msgid "Transliterating string %r with locale %r"
msgstr ""

#: ../pykolab/utils.py:487
msgid "Attempting to set locale"
msgstr ""

#: ../pykolab/utils.py:489
msgid "Success setting locale"
msgstr ""

#: ../pykolab/utils.py:491
msgid "Failure to set locale"
msgstr ""

#: ../pykolab/utils.py:499
#, python-format
msgid "Executing '%s | %s'"
msgstr ""

#: ../pykolab/utils.py:510
#, python-format
msgid "Could not translate %s using locale %s"
msgstr ""

#: ../pykolab/wap_client/__init__.py:320
#, python-format
msgid "Requesting %r with params %r"
msgstr ""

#: ../pykolab/wap_client/__init__.py:328
#, python-format
msgid "Got response: %r"
msgstr ""

#. Some data is not JSON
#: ../pykolab/wap_client/__init__.py:334
msgid "Response data is not JSON"
msgstr ""

#. support integer values, too
#: ../pykolab/xml/attendee.py:9 ../pykolab/xml/attendee.py:17
msgid "Needs Action"
msgstr ""

#: ../pykolab/xml/attendee.py:10 ../pykolab/xml/attendee.py:18
msgid "Accepted"
msgstr "Akzeptiert"

#: ../pykolab/xml/attendee.py:11 ../pykolab/xml/attendee.py:19
msgid "Declined"
msgstr "Abgelehnt"

#: ../pykolab/xml/attendee.py:12 ../pykolab/xml/attendee.py:20
msgid "Tentatively Accepted"
msgstr "Provisorisch Akzeptiert"

#: ../pykolab/xml/attendee.py:13 ../pykolab/xml/attendee.py:21
msgid "Delegated"
msgstr "Delegiert"

#: ../pykolab/xml/attendee.py:14
msgid "Completed"
msgstr ""

#: ../pykolab/xml/attendee.py:15
msgid "In Process"
msgstr ""

#: ../pykolab/xml/attendee.py:108 ../pykolab/xml/attendee.py:130
msgid "Not a valid attendee"
msgstr ""

#: ../pykolab/xml/attendee.py:115
msgid "No valid delegator references found"
msgstr ""

#: ../pykolab/xml/attendee.py:135
msgid "No valid delegatee references found"
msgstr ""

#: ../pykolab/xml/attendee.py:180
#, python-format
msgid "Invalid cutype %r"
msgstr ""

#: ../pykolab/xml/attendee.py:192
#, python-format
msgid "Invalid participant status %r"
msgstr ""

#: ../pykolab/xml/attendee.py:200
#, python-format
msgid "Invalid role %r"
msgstr ""

#: ../pykolab/xml/event.py:100 ../pykolab/xml/event.py:708
#: ../pykolab/xml/event.py:751
msgid "Event start needs datetime.date or datetime.datetime instance"
msgstr ""

#: ../pykolab/xml/event.py:241
#, python-format
msgid "No attendee with email or name %r"
msgstr ""

#: ../pykolab/xml/event.py:249
#, python-format
msgid "Invalid argument value attendee %r, must be basestring or Attendee"
msgstr ""

#: ../pykolab/xml/event.py:255
#, python-format
msgid "No attendee with email %r"
msgstr ""

#: ../pykolab/xml/event.py:261
#, python-format
msgid "No attendee with name %r"
msgstr ""

#: ../pykolab/xml/event.py:426
msgid "Invalid participant status"
msgstr ""

#: ../pykolab/xml/event.py:542
#, python-format
msgid "Invalid status %r"
msgstr ""

#: ../pykolab/xml/event.py:550
#, python-format
msgid "Invalid classification %r"
msgstr ""

#: ../pykolab/xml/event.py:577
msgid "Event end needs datetime.date or datetime.datetime instance"
msgstr ""

#: ../pykolab/xml/event.py:761
#, python-format
msgid "Invalid status set: %r"
msgstr ""

#: ../pykolab/xml/event.py:923
msgid "No sender specified"
msgstr ""

#: ../pykolab/xml/event.py:932
#, python-format
msgid "Invitation for %s was %s"
msgstr ""

#: ../pykolab/xml/event.py:937
msgid "This is an automated response to one of your event requests."
msgstr ""

#: ../saslauthd/__init__.py:99
#, python-format
msgid "Could not create %r: %r"
msgstr ""

#: ../saslauthd/__init__.py:137 ../saslauthd/__init__.py:145
#: ../wallace/__init__.py:403 ../wallace/__init__.py:412
msgid ""
"Traceback occurred, please report a bug at http://bugzilla.kolabsys.com"
msgstr "Ein Fehler mit Traceback trat auf, bitte legen Sie einen Bericht auf  http://bugzilla.kolabsys.com an"

#: ../saslauthd/__init__.py:185
msgid "kolab-saslauthd could not accept "
msgstr ""

#: ../saslauthd/__init__.py:190
msgid "Maximum tries exceeded, exiting"
msgstr ""

#: ../tests/functional/test_wallace/test_005_resource_invitation.py:190
#: ../wallace/module_resources.py:879
#, python-format
msgid "Reservation Request for %(summary)s was %(status)s"
msgstr ""

#. check notification message sent to resource owner (jane)
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:605
#: ../tests/functional/test_wallace/test_005_resource_invitation.py:621
#: ../wallace/module_resources.py:954
#, python-format
msgid "Booking for %s has been %s"
msgstr "Buchung für %s wurde %s"

#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:146
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:720
#: ../wallace/module_invitationpolicy.py:374
#, python-format
msgid "\"%(summary)s\" has been %(status)s"
msgstr "\"%(summary)s\" wurde %(status)s"

#. check for notification message
#. this notification should be suppressed until mark has replied, too
#. this triggers an additional notification
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:616
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:622
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:635
#: ../wallace/module_invitationpolicy.py:925
#, python-format
msgid "\"%s\" has been updated"
msgstr "\"%s\" wurde aktualisiert"

#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:627
#: ../tests/functional/test_wallace/test_007_invitationpolicy.py:639
msgid "PENDING"
msgstr ""

#: ../wallace/__init__.py:57
#, python-format
msgid "Wallace modules: %r"
msgstr ""

#: ../wallace/__init__.py:69
#, python-format
msgid "Module %s.execute() failed on message %r with error: %s"
msgstr ""

#: ../wallace/__init__.py:78
#, python-format
msgid "Worker process %s initializing"
msgstr ""

#: ../wallace/__init__.py:100
msgid "Bind address for Wallace."
msgstr "Bind-Adresse für Wallace."

#: ../wallace/__init__.py:126
msgid "Port that Wallace is supposed to use."
msgstr "Port, den Wallace benutzen soll."

#: ../wallace/__init__.py:177
#, python-format
msgid "Could not bind to socket on port %d on bind "
msgstr ""

#: ../wallace/__init__.py:189
msgid "Could not shut down socket"
msgstr "Konnte Socket nicht schließen"

#: ../wallace/__init__.py:253
msgid "Accepted connection"
msgstr "Verbindung akzeptiert"

#: ../wallace/__init__.py:428
#, python-format
msgid "Could not write pid file %s"
msgstr ""

#: ../wallace/module_footer.py:60 ../wallace/module_gpgencrypt.py:60
#: ../wallace/module_invitationpolicy.py:168 ../wallace/module_optout.py:61
#: ../wallace/module_resources.py:120
#, python-format
msgid "Issuing callback after processing to stage %s"
msgstr ""

#: ../wallace/module_footer.py:61 ../wallace/module_gpgencrypt.py:61
#: ../wallace/module_invitationpolicy.py:170 ../wallace/module_optout.py:62
#: ../wallace/module_resources.py:126
#, python-format
msgid "Testing cb_action_%s()"
msgstr ""

#: ../wallace/module_footer.py:63 ../wallace/module_gpgencrypt.py:63
#: ../wallace/module_invitationpolicy.py:172 ../wallace/module_optout.py:64
#: ../wallace/module_resources.py:129
#, python-format
msgid "Attempting to execute cb_action_%s()"
msgstr ""

#: ../wallace/module_footer.py:67
#, python-format
msgid "Executing module footer for %r, %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:66
#, python-format
msgid "Executing module gpgencrypt for %r, %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:98
msgid "Message is already encrypted (app/pgp-enc content-type)"
msgstr ""

#: ../wallace/module_gpgencrypt.py:102
msgid "Message already encrypted by main content-type header"
msgstr ""

#: ../wallace/module_gpgencrypt.py:131
msgid ""
"Configured to encrypt to a key not configured, and strict policy enabled. "
"Bailing out."
msgstr ""

#: ../wallace/module_gpgencrypt.py:134
msgid ""
"Configured to encrypt to a key not configured, but continuing anyway (see "
"'gpgencrypt_strict')."
msgstr ""

#: ../wallace/module_gpgencrypt.py:171
#, python-format
msgid "Recipients: %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:183
#, python-format
msgid "Current keys: %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:188
#, python-format
msgid "Retrieving key for recipient: %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:192 ../wallace/module_gpgencrypt.py:208
#, python-format
msgid "Found matching address %r"
msgstr ""

#: ../wallace/module_gpgencrypt.py:200
#, python-format
msgid "Found matching address %r in remote keys"
msgstr ""

#: ../wallace/module_gpgencrypt.py:232
#, python-format
msgid "An error occurred: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:154
#, python-format
msgid "Invitation policy called for %r, %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:211
#: ../wallace/module_resources.py:169
#, python-format
msgid "Failed to parse iTip events from message: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:215
msgid ""
"Message is not an iTip message or does not contain any (valid) iTip events."
msgstr ""

#: ../wallace/module_invitationpolicy.py:219
#, python-format
msgid ""
"iTip events attached to this message contain the following information: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:232
#, python-format
msgid "No itips, no users, pass along %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:235
#, python-format
msgid "iTips, but no users, pass along %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:255
#, python-format
msgid "No user attendee matching envelope recipient %s, skip message"
msgstr ""

#: ../wallace/module_invitationpolicy.py:259
#, python-format
msgid "Receiving user: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:284
#, python-format
msgid "Apply invitation policy %r for domain %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:295
#, python-format
msgid "Ignoring '%s' iTip method"
msgstr ""

#: ../wallace/module_invitationpolicy.py:299
#, python-format
msgid "iTip message %r consumed by the invitationpolicy module"
msgstr ""

#: ../wallace/module_invitationpolicy.py:315
msgid "Pass invitation for manual processing"
msgstr ""

#: ../wallace/module_invitationpolicy.py:320
#, python-format
msgid "Receiving Attendee: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:339
#, python-format
msgid "Existing event: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:350
#, python-format
msgid "Precondition for event %r fulfilled: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:386
#, python-format
msgid "No RSVP for recipient %r requested"
msgstr ""

#: ../wallace/module_invitationpolicy.py:412
msgid "Pass reply for manual processing"
msgstr ""

#: ../wallace/module_invitationpolicy.py:419
#, python-format
msgid "Sender Attendee: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:431
#, python-format
msgid ""
"The iTip reply sequence (%r) doesn't match the referred event version (%r). "
"Forwarding to Inbox."
msgstr ""

#: ../wallace/module_invitationpolicy.py:437
#, python-format
msgid "Auto-updating event %r on iTip REPLY"
msgstr ""

#: ../wallace/module_invitationpolicy.py:459
#: ../wallace/module_invitationpolicy.py:488
msgid ""
"The event referred by this reply was not found in the user's calendars. "
"Forwarding to Inbox."
msgstr ""

#: ../wallace/module_invitationpolicy.py:472
msgid "Pass cancellation for manual processing"
msgstr ""

#: ../wallace/module_invitationpolicy.py:517
#, python-format
msgid "Checking if email address %r belongs to a local user"
msgstr ""

#: ../wallace/module_invitationpolicy.py:522
#, python-format
msgid "User DN: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:524
#, python-format
msgid "No user record(s) found for %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:577
#, python-format
msgid "User record doesn't have the mailbox attribute %r set"
msgstr ""

#: ../wallace/module_invitationpolicy.py:590
#, python-format
msgid "IMAP proxy authentication failed: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:612
#, python-format
msgid "List calendar folders for user %r: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:628
#, python-format
msgid "IMAP metadata for %r: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:658
#, python-format
msgid "Searching folder %r for event %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:670
#: ../wallace/module_invitationpolicy.py:709
#: ../wallace/module_resources.py:486
#, python-format
msgid "Failed to parse event from message %s/%s: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:696
#, python-format
msgid "Listing events from folder %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:715
#, python-format
msgid "Existing event %r conflicts with invitation %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:722
#: ../wallace/module_resources.py:344
#, python-format
msgid "start: %r, end: %r, total: %r, messages: %d"
msgstr ""

#: ../wallace/module_invitationpolicy.py:748
#, python-format
msgid "%r is locked, waiting..."
msgstr ""

#: ../wallace/module_invitationpolicy.py:811
#, python-format
msgid "Failed to save event: no calendar folder found for user %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:814
#, python-format
msgid "Save event %r to user calendar %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:827
#, python-format
msgid "Failed to save event to user calendar at %r: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:843
#, python-format
msgid "Delete event %r in %r: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:863
#, python-format
msgid "Compose participation status summary for event %r to user %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:901
#, python-format
msgid ""
"Waiting for more automated replies (got %d of %d); skipping notification"
msgstr ""

#: ../wallace/module_invitationpolicy.py:998
#, python-format
msgid "Updated %s's copy of %r: %r"
msgstr ""

#: ../wallace/module_invitationpolicy.py:1001
#, python-format
msgid "Attendee %s's copy of %r not found"
msgstr ""

#: ../wallace/module_invitationpolicy.py:1004
#, python-format
msgid "Attendee %r not found in LDAP"
msgstr ""

#: ../wallace/module_invitationpolicy.py:1008
#, python-format
msgid ""
"\n"
"        %(name)s has %(status)s your invitation for %(summary)s.\n"
"\n"
"        *** This is an automated response sent by the Kolab Invitation system ***\n"
"    "
msgstr ""

#. modules.next_module('optout')
#: ../wallace/module_optout.py:70
#, python-format
msgid "Consulting opt-out service for %r, %r"
msgstr ""

#: ../wallace/module_optout.py:96
#, python-format
msgid "Running opt-out consult from envelope sender '%s "
msgstr ""

#: ../wallace/module_optout.py:160
#, python-format
msgid "Attempting to execute cb_action_%s(%r, %r)"
msgstr ""

#: ../wallace/module_optout.py:181
#, python-format
msgid "Could not send request to optout_url %s"
msgstr ""

#: ../wallace/module_resources.py:110
#, python-format
msgid "Resource Management called for %r, %r"
msgstr ""

#: ../wallace/module_resources.py:174
msgid "Message is not an iTip message or does not contain any "
msgstr ""

#: ../wallace/module_resources.py:182
msgid "iTip events attached to this message contain the "
msgstr ""

#: ../wallace/module_resources.py:205
msgid "Not an iTip message, but sent to resource nonetheless. Reject message"
msgstr ""

#: ../wallace/module_resources.py:213
#, python-format
msgid "No itips, no resources, pass along %r"
msgstr ""

#: ../wallace/module_resources.py:216
#, python-format
msgid "iTips, but no resources, pass along %r"
msgstr ""

#: ../wallace/module_resources.py:225
#, python-format
msgid "No resource attendees matching envelope recipient %s, Reject message"
msgstr ""

#: ../wallace/module_resources.py:234
#, python-format
msgid "Resources: %r; %r"
msgstr ""

#: ../wallace/module_resources.py:244
#, python-format
msgid "Receiving Resource: %r; %r"
msgstr ""

#: ../wallace/module_resources.py:252
#, python-format
msgid "Recipient %r is non-participant, ignoring message"
msgstr ""

#: ../wallace/module_resources.py:279
#, python-format
msgid "Accept invitation for individual resource %r / %r"
msgstr ""

#: ../wallace/module_resources.py:308
#, python-format
msgid "Delegate invitation for resource collection %r to %r"
msgstr ""

#: ../wallace/module_resources.py:340
#, python-format
msgid "Failed to read resource calendar for %r: %r"
msgstr ""

#: ../wallace/module_resources.py:350
#, python-format
msgid "Polling for resource %r"
msgstr ""

#: ../wallace/module_resources.py:353
#, python-format
msgid "Resource %r has been popped from the list"
msgstr ""

#: ../wallace/module_resources.py:357
msgid "Resource is a collection"
msgstr ""

#: ../wallace/module_resources.py:368
#, python-format
msgid "Removed conflicting resources from %r: (%r) => %r"
msgstr ""

#: ../wallace/module_resources.py:380
#, python-format
msgid "Conflicting events: %r for resource %r"
msgstr ""

#: ../wallace/module_resources.py:397
#, python-format
msgid "Delegate to another resource collection member: %r to %r"
msgstr ""

#: ../wallace/module_resources.py:459
#, python-format
msgid "Checking events in resource folder %r"
msgstr ""

#: ../wallace/module_resources.py:475
#, python-format
msgid "Fetching message UID %r from folder %r"
msgstr ""

#: ../wallace/module_resources.py:498
#, python-format
msgid "Event %r conflicts with event %r"
msgstr ""

#: ../wallace/module_resources.py:525
#, python-format
msgid "Adding event to %r: %r"
msgstr ""

#: ../wallace/module_resources.py:573
#, python-format
msgid "Failed to save event to resource calendar at %r: %r"
msgstr ""

#: ../wallace/module_resources.py:590
#, python-format
msgid "Delete resource calendar object %r in %r: %r"
msgstr ""

#: ../wallace/module_resources.py:633
#, python-format
msgid "Checking if email address %r belongs to a resource (collection)"
msgstr ""

#: ../wallace/module_resources.py:641 ../wallace/module_resources.py:709
#: ../wallace/module_resources.py:743
#, python-format
msgid "Resource record(s): %r"
msgstr ""

#: ../wallace/module_resources.py:643 ../wallace/module_resources.py:711
#: ../wallace/module_resources.py:746
#, python-format
msgid "No resource (collection) records found for %r"
msgstr ""

#: ../wallace/module_resources.py:647 ../wallace/module_resources.py:715
#: ../wallace/module_resources.py:750
#, python-format
msgid "Resource record: %r"
msgstr ""

#: ../wallace/module_resources.py:667
#, python-format
msgid "Raw itip_events: %r"
msgstr ""

#: ../wallace/module_resources.py:675
#, python-format
msgid "Raw set of attendees: %r"
msgstr ""

#: ../wallace/module_resources.py:683
#, python-format
msgid "Raw set of resources: %r"
msgstr ""

#: ../wallace/module_resources.py:702
#, python-format
msgid "Checking if attendee %r is a resource (collection)"
msgstr ""

#: ../wallace/module_resources.py:718 ../wallace/module_resources.py:752
msgid "Resource reservation made but no resource records found"
msgstr ""

#: ../wallace/module_resources.py:737
#, python-format
msgid "Checking if resource %r is a resource (collection)"
msgstr ""

#: ../wallace/module_resources.py:755
msgid "The following resources are being referred to in the "
msgstr ""

#: ../wallace/module_resources.py:894
#, python-format
msgid ""
"\n"
"                *** This is an automated response, please do not reply! ***\n"
"\n"
"                Your reservation was delegated to \"%s\" which is available for the requested time.\n"
"            "
msgstr ""

#: ../wallace/module_resources.py:905
#, python-format
msgid ""
"\n"
"        *** This is an automated response, please do not reply! ***\n"
"        \n"
"        We hereby inform you that your reservation was %s.\n"
"    "
msgstr ""

#: ../wallace/module_resources.py:912
#, python-format
msgid ""
"\n"
"            If you have questions about this reservation, please contact\n"
"            %s <%s> %s\n"
"        "
msgstr ""

#: ../wallace/module_resources.py:941
#, python-format
msgid "Sending booking notification for event %r to %r from %r"
msgstr ""

#: ../wallace/module_resources.py:954
msgid "failed"
msgstr ""

#: ../wallace/module_resources.py:973
#, python-format
msgid ""
"\n"
"            The resource booking for %(resource)s by %(orgname)s <%(orgemail)s> has been %(status)s for %(date)s.\n"
"\n"
"            *** This is an automated message, sent to you as the resource owner. ***\n"
"        "
msgstr ""

#: ../wallace/module_resources.py:979
#, python-format
msgid ""
"\n"
"            A reservation request for %(resource)s could not be processed automatically.\n"
"            Please contact %(orgname)s <%(orgemail)s> who requested this resource for %(date)s. Subject: %(summary)s.\n"
"\n"
"            *** This is an automated message, sent to you as the resource owner. ***\n"
"        "
msgstr ""

#. This is a nested module
#: ../wallace/modules.py:97
#, python-format
msgid "Module Group: %s"
msgstr "Modulgruppe: %s"

#: ../wallace/modules.py:108
#, python-format
msgid "No such module %r in modules %r (1)."
msgstr ""

#: ../wallace/modules.py:113
#, python-format
msgid "No such module %r in modules %r (2)."
msgstr ""

#: ../wallace/modules.py:119
#, python-format
msgid "Holding message in queue for manual review (%s by %s)"
msgstr "Behalte Nachricht zur manuellen Prüfung in der Warteliste (%s von %s)"

#: ../wallace/modules.py:122
#, python-format
msgid "Deferring message in %s (by module %s)"
msgstr ""

#: ../wallace/modules.py:134
#, python-format
msgid "The time when the message was sent: %r"
msgstr "Zeitpunkt des Versandts: %r"

#: ../wallace/modules.py:135
#, python-format
msgid "The time now: %r"
msgstr "Die Zeit ist jetzt: %r"

#: ../wallace/modules.py:136
#, python-format
msgid "The time delta: %r"
msgstr "Die Zeitdifferenz: %r"

#. TODO: Send NDR back to user
#: ../wallace/modules.py:140
#, python-format
msgid "Message in file %s older then 5 days, deleting"
msgstr ""

#: ../wallace/modules.py:165
#, python-format
msgid "Rejecting message in %s (by module %s)"
msgstr ""

#: ../wallace/modules.py:186
#, python-format
msgid ""
"This is the email system Wallace at %s.\n"
"\n"
"I'm sorry to inform you we could not deliver the attached message\n"
"to the following recipients:\n"
"\n"
"- %s\n"
"\n"
"Your message is being delivered to any other recipients you may have\n"
"sent your message to. There is no need to resend the message to those\n"
"recipients.\n"
msgstr "Ich bin das E-Mail-System Wallace auf %s.\n\nMit Bedauern muß ich Sie informieren, daß die angehängte Nachricht\nnicht an die folgenden Empfänger zugestellt werden konnte:\n\n- %s\n\nFalls Sie noch andere Empfänger angegeben haben wurde die Nachricht\nan diese zugestellt. An diese Empfänger müssen sie die Nachricht\nnicht erneut senden.\n"

#: ../wallace/modules.py:201
#, python-format
msgid ""
"X-Wallace-Module: %s\n"
"X-Wallace-Result: REJECT\n"
msgstr ""

#: ../wallace/modules.py:260
#, python-format
msgid "Accepting message in %s (by module %s)"
msgstr ""

#: ../wallace/modules.py:262
#, python-format
msgid "Accepting message in: %r"
msgstr ""

#: ../wallace/modules.py:269
#, python-format
msgid "recipients: %r"
msgstr ""

#: ../wallace/modules.py:347
#, python-format
msgid "Module '%s' already registered"
msgstr "Modul '%s' ist bereits registriert"
